#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   juice.yml
# Desc      :   Deploy JuiceFS with PostgreSQL backend
# Ctime     :   2025-01-20
# Mtime     :   2025-01-20
# Docs      :   https://pigsty.io/docs/juice/
# Author    :   Ruohang Feng (rh@vonng.com)
# License   :   Apache-2.0
#==============================================================#
- name: JUICE
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - { role: node_id ,tags: id }  # get node identity (always)
    - { role: juice   ,tags: juice, when: juice_pgurl is defined }

...
