#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   jupyter.yml
# Desc      :   deploy jupyter lab on nodes
# Ctime     :   2025-01-22
# Mtime     :   2025-01-22
# Path      :   jupyter.yml
# Docs      :   https://pigsty.io/docs/jupyter
# License   :   Apache-2.0 @ https://pigsty.io/docs/about/license/
# Copyright :   2018-2026  Ruohang Feng / Vonng (rh@vonng.com)
#==============================================================#
- name: JUPYTER LAB
  hosts: all
  gather_facts: no
  become: true
  vars:
    #jupyter_enabled: false        # enable jupyter on this node?
    #jupyter_port: 8888            # jupyter listen port
    #jupyter_home: /fs/jupyter     # jupyter working directory (notebook root)
    #jupyter_data: /data/jupyter   # jupyter data directory
    #jupyter_password: Jupyter.Lab # jupyter login token
    #jupyter_venv: /data/venv      # python venv path
  roles:
    - { role: node_id , tags: id      }
    - { role: jupyter , tags: jupyter , when: jupyter_enabled is defined and jupyter_enabled|bool }


#---------------------------------------------------------------
# Usage
#---------------------------------------------------------------
# Set parameter `jupyter_enabled: true` on target nodes, then:
#
#   ./jupyter.yml -l <host>
#
# Access jupyter at: https://i.pigsty/jupyter/
#
# one-liner to enable jupyter on infra node:
#   ./jupyter.yml -l infra -e jupyter_enabled=true
#
#---------------------------------------------------------------
# Tasks
#---------------------------------------------------------------
# jupyter               : setup jupyter lab on node
#   - jupyter_dir       : create jupyter directories
#   - jupyter_config    : render jupyter config and systemd unit
#   - jupyter_launch    : launch jupyter systemd service
#---------------------------------------------------------------
...
