---
- name: restart kafka
  when: not ansible_check_mode
  systemd:
    name: kafka
    state: restarted
    enabled: true
    daemon_reload: true

- name: restart kafka exporter
  when: kafka_has_broker | bool and not ansible_check_mode
  systemd:
    name: kafka_exporter
    state: restarted
    enabled: true
    daemon_reload: true
...
