---
#-----------------------------------------------------------------
# OPENBAO
#-----------------------------------------------------------------
#openbao_seq: 1                   # bao instance identifier, explicitly required
openbao_cluster: openbao          # bao cluster & group name, openbao by default
openbao_data: /data/openbao       # bao data dir, `/data/openbao` by default
openbao_log_dir: /data/openbao/log # bao log dir, `/data/openbao/log` by default
openbao_domain: bao.pigsty        # bao domain name, `bao.pigsty` by default
openbao_api_port: 8200            # used to advertise other servers in the cluster for client redirection, `8200` by default
openbao_cluster_port: 8201        # used to advertise other servers in the cluster for request forwarding, `8201` by default

#-----------------------------------------------------------------
# CA (Reference)
#-----------------------------------------------------------------
cert_validity: 7300d              # cert validity, 20 years by default
#-----------------------------------------------------------------
# NODE (Reference)
#-----------------------------------------------------------------
node_data: /data                  # node main data directory, /data by default
node_admin_enabled: true          # create a admin user on target node?
node_admin_username: dba          # name of node admin user, `dba` by default
...
