---
#--------------------------------------------------------------#
# Cleanup ETCD cluster info                               [etcd]
#--------------------------------------------------------------#
# when pitr from another cluster, we'll need to remove the current
# cluster's metadata from etcd /pg/<cluster>/
- name: delete postgres metadata from etcd for pitr
  delegate_to: "{{ groups['etcd'] | first }}"
  become: true
  environment:
    ETCDCTL_ENDPOINTS: "{{ groups['etcd'] | map('regex_replace', '^(.*)$', 'https://\\1:' + etcd_port|string) | join(',') }}"
    ETCDCTL_CACERT: "/etc/etcd/ca.crt"
    ETCDCTL_CERT: "/etc/etcd/server.crt"
    ETCDCTL_KEY: "/etc/etcd/server.key"
    ETCDCTL_USER: "root:{{ etcd_root_password }}"
  vars:
    pg_meta_prefix: "{{ pg_namespace }}/{{ (pg_shard ~ '/' ~ pg_group) if pg_mode == 'citus' else pg_cluster }}"
  shell: etcdctl del "{{ pg_meta_prefix }}/" --prefix=true
  args: { executable: /bin/bash }
  ignore_errors: true
  no_log: true
...
