---
#--------------------------------------------------------------#
# PRINT PITR PLAN                                        [print]
#--------------------------------------------------------------#
- import_tasks: print.yml
  tags: [ print, always ]

#--------------------------------------------------------------#
# PAUSE PATRONI HA                                       [pause]
#--------------------------------------------------------------#
- import_tasks: pause.yml
  tags: [ down, pause ]

#--------------------------------------------------------------#
# STOP SERVICES                                           [stop]
#--------------------------------------------------------------#
# stop_primary, stop_replica, stop_postgres
- import_tasks: stop.yml
  tags: [ down, stop ]

#--------------------------------------------------------------#
# PERFORM PITR                                            [pitr]
#--------------------------------------------------------------#
# config, restore, recovery, verify
- import_tasks: pitr.yml
  tags: pitr

#--------------------------------------------------------------#
# REMOVE ETCD META                                        [etcd]
#--------------------------------------------------------------#
# remove the old cluster identifier from etcd
- name: remove postgres metadata from etcd
  tags: [ up, etcd, pg_meta ]
  when:
    - pg_role == 'primary'
    - pg_cluster != ''
    - pg_cluster != 'root'  # fail if you choose 'root' as cluster name
    - groups['etcd'] is defined
    - groups['etcd'] | length > 0
    # - pg_pitr.cluster is defined
    # - pg_pitr.cluster != pg_cluster
  # wrapper owns tag selection; child always runs once included
  include_tasks: { file: etcd.yml, apply: { tags: [ always ] } }

#--------------------------------------------------------------#
# START PRIMARY                                          [start]
#--------------------------------------------------------------#
# etcd start_primary start_replica
- import_tasks: start.yml
  tags: [ up, start ]
...
