{
 "title": "Node ZFS",
 "description": "ZFS Pool Dashboard",
 "tags": [
  "ZFS",
  "POOL",
  "Dataset",
  "NODE",
  "Pigsty"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Environment", "query": { "query": "label_values(node_load1, job)" } },
   { "name": "id", "label": "Node ID", "query": { "query": "label_values(node:ins, id)" } },
   {
    "name": "ip",
    "label": "IP Address",
    "query": {
     "query": "label_values(node:ins{id=~\"$id\"}, ip)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(node:zfs:pool_metrics{metric_type=\"health\", pool=~\"$pool\"}, pool)"
    }
   },
   { "name": "dataset", "label": "Dataset" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(ALERTS{alertstate=\"firing\", job=\"$job\", alertname=~\"ZPool.+\"}) or on() vector(0))\n+ (count(ALERTS{alertstate=\"firing\", job=\"$job\", alertname=~\"ZDataset.+\"}) or on() vector(0))\n+ (count(ALERTS{alertstate=\"firing\", job=\"$job\", fstype=\"zfs\"}) or on() vector(0))\n",
     "legendFormat": "Firing Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\", alertname=~\"ZPool.+\"}) by (alertname, severity)\nor\ncount(ALERTS{alertstate=\"firing\", job=\"$job\", fstype=\"zfs\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", job=\"$job\",alertname=~\"ZPool.+\"}\nor\nALERTS{alertstate=\"firing\", job=\"$job\",alertname=~\"ZDataset.+\"}\nor\nALERTS{alertstate=\"firing\", job=\"$job\",fstype=\"zfs\"}\n",
     "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"size_gib\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"capacity\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"free_mib\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"fragmentation_ratio\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"leaked_kib\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"freeing_kib\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"readonly\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"health\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"autotrim\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"ashift\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:pool_metrics{metric_type=\"dedupratio\", ip=~\"$ip\", pool=~\"$pool\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "zfs_exporter_up{ip=~\"$ip\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Datasets",
   "type": "table",
   "description": "ZFS Datasets",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"used_mib\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"avail_mib\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"logical_used_mib\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"quota_mib\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"written_mib\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"capacity\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"refer_bytes\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"size_gib\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"atime\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"creation\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"exec\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"mounted\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"recordsize_kib\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"relatime\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"compression\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"compressratio\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"sync\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"logbias\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(node:zfs:dataset_metrics{metric_type=\"primarycache\", ip=~\"$ip\", pool=~\"$pool\", name=~\"$dataset\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}