{
 "title": "Node Instance",
 "description": "Node: Instance Dashboard",
 "tags": [
  "Pigsty",
  "NODE",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "id", "label": "Node ID", "query": { "query": "label_values(node:ins, id)" } },
   {
    "name": "ip",
    "label": "IP Address",
    "query": {
     "query": "label_values(node:ins{id=\"$id\"}, ip)"
    }
   },
   {
    "name": "node",
    "label": "Hostname",
    "query": {
     "query": "label_values(node:ins{id=\"$id\"}, nodename)"
    }
   },
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(node:ins{id=\"$id\"}, ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(node:ins{id=\"$id\"}, cls)"
    }
   },
   {
    "name": "pg_ins",
    "label": "PG Instance",
    "query": {
     "query": "label_values(pg_up{ip=\"$ip\"},ins)"
    }
   },
   {
    "name": "vip",
    "label": "VIP Address",
    "query": {
     "query": "label_values(probe_success{ip=\"$ip\"},vip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_up{ip=\"$ip\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "min by (job,ip,vip) (probe_success{ip=\"$ip\", job=~'(node|pgsql)-vip'})",
     "legendFormat": "{{ job }} : {{ vip }}"
    }
   ]
  },
  {
   "type": "table",
   "description": "All nodes among cluster ${cls}",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "node_up{cls=\"$cls\"}"
    },
    {
     "expr": "group without(ins,cls,instance) (node_uname_info{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_usage{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:mem_usage{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ip,instance) (node:ins:space_usage_max{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_count{cls=\"$cls\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{cls=\"$cls\"}) / 1073741824"
    },
    {
     "expr": "sum(node:fs:size_bytes{cls=\"$cls\", fstype!~\"fuse.juicefs\"}) by (ip) / 1073741824"
    },
    {
     "expr": "count by (ip) (up{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (probe_duration_seconds{cls=\"$cls\", job=\"ping\"})"
    },
    {
     "expr": "sum by (ip) (haproxy_backend_current_sessions{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ip) (node_up{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ins=\"$ins\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_count{ip=\"$ip\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "sum by (ins) (node_memory_MemTotal_bytes{ip=\"$ip\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum by (ins) (node_memory_SwapTotal_bytes{ip=\"$ip\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(max by (mountpoint)(node_filesystem_size_bytes{ip=\"$ip\"}))",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{ip=\"$ip\", device=~\"/dev/(nvme.*|dfa.*)\"})",
     "legendFormat": "NVMe"
    },
    {
     "expr": "- absent(node_network_speed_bytes{ip=\"$ip\"}) OR max by (ins) (node_network_speed_bytes{ip=\"$ip\"}) * 8",
     "legendFormat": "Link"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (ip) (node_up{ip=\"$ip\"})",
     "legendFormat": "Alive"
    },
    {
     "expr": "max(time() - node_boot_time_seconds{ip=\"$ip\"})",
     "legendFormat": "Uptime"
    },
    {
     "expr": "- absent(node_vmstat_numa_hit{ip=\"$ip\"}) OR rate(node_vmstat_numa_hit{ip=\"$ip\"}[1m]) > bool 0",
     "legendFormat": "Numa"
    },
    {
     "expr": "sum by (ins) (node_memory_Hugepagesize_bytes{ip=\"$ip\"} * node_memory_HugePages_Total{ip=\"$ip\"})",
     "legendFormat": "HugePage"
    },
    {
     "expr": "-absent(node_bonding_active{ip=\"$ip\"}) or node_bonding_active{ip=\"$ip\"}",
     "legendFormat": "Bond"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ip=\"$ip\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:stdload1{ip=\"$ip\"}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:ins:mem_usage{ip=\"$ip\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{ip=\"$ip\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:fd_usage{ip=\"$ip\"}",
     "legendFormat": "FD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:inode_usage{ip=\"$ip\"})",
     "legendFormat": "iNode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:dev:disk_iops_1m{ip=\"$ip\"})",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:disk_io_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "Disk IO"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:network_io_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "Net Traff"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:tcp_error_rate1m{ip=\"$ip\"}",
     "legendFormat": "TCP Errs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:tcp_retrans_ratio1m{ip=\"$ip\"}",
     "legendFormat": "Retrans"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_timex_sync_status{ip=\"$ip\"})",
     "legendFormat": "Time Sync"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (proxy) (haproxy_backend_current_sessions{ins=\"$ins\", proxy!=\"stats\"}))",
     "legendFormat": "Service"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{ins=\"$ins\"})",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:fs:space_usage{ip=\"$ip\"}",
     "legendFormat": "{{ device }} → {{ mountpoint }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow = Agent (Patroni / PG Exporters)\n\nPink = MinIO\n\nRustFS Blue = RustFS\n\nTeal = Kafka\n\nMySQL Blue = MySQL\n\nKubernetes Blue = Kubernetes",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ip=\"$ip\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_up{ip=\"$ip\"}",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": "patroni_up{ip=\"$ip\"}",
     "legendFormat": "patroni"
    },
    {
     "expr": "pg_exporter_agent_up{ip=\"$ip\"}",
     "legendFormat": "pg_exporter"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ip=\"$ip\"}",
     "legendFormat": "pgb_exporter"
    },
    {
     "expr": "node_up{ip=\"$ip\"}",
     "legendFormat": "node"
    },
    {
     "expr": "haproxy_up{ip=\"$ip\"}",
     "legendFormat": "haproxy"
    },
    {
     "expr": "docker_up{ip=\"$ip\"}",
     "legendFormat": "docker"
    },
    {
     "expr": "vector_up{ip=\"$ip\"}",
     "legendFormat": "vector"
    },
    {
     "expr": "max by (ins) (up{job=\"juice\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"nginx\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"grafana\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmetrics\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vlogs\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vtraces\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmalert\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"alertmanager\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "etcd_up{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "redis_up{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "minio_up{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "rustfs_up{job=\"minio\",flavor=\"rustfs\",ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mysql_up{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "keepalived_up{ip=\"$ip\"}",
     "legendFormat": "{{ vip }}"
    },
    {
     "expr": "mysql_exporter_up{ip=\"$ip\"}",
     "legendFormat": "mysql exporter"
    },
    {
     "expr": "kafka_up{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min by (ins) (up{job=\"kube\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ip=\"$ip\"}",
     "legendFormat": "Realtime"
    },
    {
     "expr": "node:ins:cpu_usage_1m{ip=\"$ip\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node:ins:cpu_usage_5m{ip=\"$ip\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node:ins:cpu_usage_15m{ip=\"$ip\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{ip=\"$ip\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}"
    },
    {
     "expr": "ALERTS{ip=\"$ip\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:cpu_usage{ip=\"$ip\"}",
       "legendFormat": "Realtime"
      },
      {
       "expr": "node:ins:cpu_usage_1m{ip=\"$ip\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node:ins:cpu_usage_5m{ip=\"$ip\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node:ins:cpu_usage_15m{ip=\"$ip\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "CPU Time by State (per Second)",
     "type": "timeseries",
     "description": "Sum of all state will approximately to the number of cpu core",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{ip=\"$ip\"}[1m]))",
       "legendFormat": "{{ mode }}"
      },
      {
       "expr": "sum(node:ins:cpu_count{ip=\"$ip\"})",
       "legendFormat": "CPU Count"
      }
     ]
    },
    {
     "title": "Core Usage Realtime",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(node:cpu:usage{ip=\"$ip\"}[1m])",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node:cpu:usage_avg15m{ip=\"$ip\"}",
       "legendFormat": "C{{ cpu }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load (1m, 5m, 15m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load1{ip=\"$ip\"}",
       "legendFormat": "load1"
      },
      {
       "expr": "node_load5{ip=\"$ip\"}",
       "legendFormat": "load5"
      },
      {
       "expr": "node_load15{ip=\"$ip\"}",
       "legendFormat": "load15"
      }
     ]
    },
    {
     "title": "Normalized Load (1m, 5m, 15m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:stdload1{ip=\"$ip\"}",
       "legendFormat": "load1"
      },
      {
       "expr": "node:ins:stdload5{ip=\"$ip\"}",
       "legendFormat": "load5"
      },
      {
       "expr": "node:ins:stdload15{ip=\"$ip\"}",
       "legendFormat": "load15"
      }
     ]
    },
    {
     "title": "Scheduled Timeslices",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:cpu:sched_timeslices_rate1m{ip=\"$ip\"}",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "Schedule Waiting Time",
     "type": "timeseries",
     "description": "How long processes had to be wait to be scheduled on that CPU.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_schedstat_waiting_seconds_total{ip=\"$ip\"}[1m])",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "Process State",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_procs_running{ip=\"$ip\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "node_procs_blocked{ip=\"$ip\"}",
       "legendFormat": "Blocked"
      }
     ]
    },
    {
     "title": "Non-Sleep Process State",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_processes_state{ip=\"$ip\", state!=\"S\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Thread",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_processes_threads{ip=\"$ip\"}",
       "legendFormat": "Thread"
      }
     ]
    },
    {
     "title": "Context Switch",
     "type": "timeseries",
     "description": "Context switch rate 1m",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:ctx_switch_rate1m{ip=\"$ip\"}",
       "legendFormat": "Ctx Switch"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_processes_max_processes{ip=\"$ip\"}",
       "legendFormat": "Max Process"
      },
      {
       "expr": "node_processes_max_threads{ip=\"$ip\"}",
       "legendFormat": "Max Thread"
      }
     ]
    },
    {
     "title": "Fork",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:forks_rate1m{ip=\"$ip\"}",
       "legendFormat": "Fork"
      }
     ]
    },
    {
     "title": "Interrupt",
     "type": "timeseries",
     "description": "Interrupt Rate 1m",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:interrupt_rate1m{ip=\"$ip\"}",
       "legendFormat": "Interrupt"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory & Swap Usage",
     "type": "timeseries",
     "description": "Memory Usage : 1 - mem_avail / mem_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:mem_usage{ip=\"$ip\"}",
       "legendFormat": "Memory"
      },
      {
       "expr": "node:ins:swap_usage{ip=\"$ip\"}",
       "legendFormat": "Swap"
      }
     ]
    },
    {
     "title": "Committed Ratio",
     "type": "timeseries",
     "description": "Commit Ratio = CommittedAS / CommitLimit",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{ip=\"$ip\"} / node_memory_CommitLimit_bytes{ip=\"$ip\"}",
       "legendFormat": "Commit Ratio"
      }
     ]
    },
    {
     "title": "Memory Structure: App/Kernel",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{ip=\"$ip\"} \n* node_memory_HugePages_Total{ip=\"$ip\"}",
       "legendFormat": "HugePage"
      },
      {
       "expr": "node:ins:mem_kernel{ip=\"$ip\"}",
       "legendFormat": "Kernel"
      },
      {
       "expr": "node:ins:mem_rss{ip=\"$ip\"}",
       "legendFormat": "Application RSS"
      },
      {
       "expr": "node_memory_Cached_bytes{ip=\"$ip\"} - node_memory_Mapped_bytes{ip=\"$ip\"}",
       "legendFormat": "Cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{ip=\"$ip\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{ip=\"$ip\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{ip=\"$ip\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Committed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{ip=\"$ip\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{ip=\"$ip\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory Structure: PageCache",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{ip=\"$ip\"} \n* node_memory_HugePages_Total{ip=\"$ip\"}",
       "legendFormat": "HugePage"
      },
      {
       "expr": "node_memory_KernelStack_bytes{ip=\"$ip\"} +\nnode_memory_VmallocUsed_bytes{ip=\"$ip\"} +\nnode_memory_HardwareCorrupted_bytes{ip=\"$ip\"} +\nnode_memory_PageTables_bytes{ip=\"$ip\"} +\nnode_memory_Slab_bytes{ip=\"$ip\"} +\nnode_memory_PageTables_bytes{ip=\"$ip\"}",
       "legendFormat": "Kernel"
      },
      {
       "expr": "node_memory_Cached_bytes{ip=\"$ip\"}",
       "legendFormat": "Cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{ip=\"$ip\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_AnonPages_bytes{ip=\"$ip\"}",
       "legendFormat": "Anon"
      },
      {
       "expr": "node_memory_MemFree_bytes{ip=\"$ip\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{ip=\"$ip\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory Structure: LRU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{ip=\"$ip\"} \n* node_memory_HugePages_Total{ip=\"$ip\"}",
       "legendFormat": "HugePage"
      },
      {
       "expr": "node_memory_KernelStack_bytes{ip=\"$ip\"} +\nnode_memory_VmallocUsed_bytes{ip=\"$ip\"} +\nnode_memory_HardwareCorrupted_bytes{ip=\"$ip\"} +\nnode_memory_PageTables_bytes{ip=\"$ip\"} +\nnode_memory_Slab_bytes{ip=\"$ip\"} +\nnode_memory_PageTables_bytes{ip=\"$ip\"}",
       "legendFormat": "Kernel"
      },
      {
       "expr": "node_memory_Active_bytes{ip=\"$ip\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_Inactive_bytes{ip=\"$ip\"}",
       "legendFormat": "InActive"
      },
      {
       "expr": "node_memory_Unevictable_bytes{ip=\"$ip\"}",
       "legendFormat": "Unevictable"
      },
      {
       "expr": "node_memory_MemFree_bytes{ip=\"$ip\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{ip=\"$ip\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory Structure: Kernel",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{ip=\"$ip\"}",
       "legendFormat": "KernelStack"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{ip=\"$ip\"}",
       "legendFormat": "VmallocUsed"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{ip=\"$ip\"}",
       "legendFormat": "HardwareCorrupted"
      },
      {
       "expr": "node_memory_PageTables_bytes{ip=\"$ip\"}",
       "legendFormat": "PageTable"
      },
      {
       "expr": "node_memory_Slab_bytes{ip=\"$ip\"}",
       "legendFormat": "Slab"
      }
     ]
    },
    {
     "title": "Mem Struct: LRU Details",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{ip=\"$ip\"}",
       "legendFormat": "Inactive-File"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{ip=\"$ip\"}",
       "legendFormat": "Inactive-Anon"
      },
      {
       "expr": "node_memory_Active_file_bytes{ip=\"$ip\"}",
       "legendFormat": "Active-File"
      },
      {
       "expr": "node_memory_Active_anon_bytes{ip=\"$ip\"}",
       "legendFormat": "Active-Anon"
      },
      {
       "expr": "node_memory_Unevictable_bytes{ip=\"$ip\"}",
       "legendFormat": "Unevictable"
      }
     ]
    },
    {
     "title": "HugePage Allocation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{ip=\"$ip\"} * node_memory_HugePages_Free{ip=\"$ip\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{ip=\"$ip\"} * (node_memory_HugePages_Total{ip=\"$ip\"} - node_memory_HugePages_Free{ip=\"$ip\"})",
       "legendFormat": "Alloc"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{ip=\"$ip\"} * node_memory_HugePages_Rsvd{ip=\"$ip\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{ip=\"$ip\"} * node_memory_HugePages_Total{ip=\"$ip\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{ip=\"$ip\"}",
       "legendFormat": "PageSize"
      },
      {
       "expr": "node_memory_HugePages_Total{ip=\"$ip\"}",
       "legendFormat": "Total Pages"
      },
      {
       "expr": "(node_memory_HugePages_Total{ip=\"$ip\"} - node_memory_HugePages_Free{ip=\"$ip\"} + node_memory_HugePages_Rsvd{ip=\"$ip\"}) / node_memory_HugePages_Total{ip=\"$ip\"}",
       "legendFormat": "Alloc%"
      },
      {
       "expr": "node_memory_HugePages_Free{ip=\"$ip\"} * node_memory_Hugepagesize_bytes{ip=\"$ip\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{ip=\"$ip\"} * node_memory_Hugepagesize_bytes{ip=\"$ip\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "(node_memory_HugePages_Total{ip=\"$ip\"} - node_memory_HugePages_Free{ip=\"$ip\"}) * node_memory_Hugepagesize_bytes{ip=\"$ip\"}",
       "legendFormat": "Alloc"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "-absent(node_edac_correctable_errors_total) or sum(node_edac_correctable_errors_total{ip=\"$ip\"})",
       "legendFormat": "EDAC Errors"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "-absent(node_edac_uncorrectable_errors_total{ip=\"$ip\"}) or sum(node_edac_uncorrectable_errors_total{ip=\"$ip\"})",
       "legendFormat": "Uncorrectable"
      }
     ]
    }
   ]
  },
  {
   "title": "VMSTAT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Page In/Out Rate",
     "type": "timeseries",
     "description": "Rate of pages in/out/swapin/swapout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:pagein_rate1m{ip=\"$ip\"}",
       "legendFormat": "▲PageIn"
      },
      {
       "expr": "- node:ins:pageout_rate1m{ip=\"$ip\"}",
       "legendFormat": "▼PageOut"
      }
     ]
    },
    {
     "title": "Swap In/Out Rate",
     "type": "timeseries",
     "description": "Rate of pages in/out/swapin/swapout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:swapin_rate1m{ip=\"$ip\"}",
       "legendFormat": "▲SwapIn"
      },
      {
       "expr": "- node:ins:swapout_rate1m{ip=\"$ip\"}",
       "legendFormat": "▼SwapOut"
      }
     ]
    },
    {
     "title": "Major Page Fault",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:ins:pgmajfault_rate1m{ip=\"$ip\"}",
       "legendFormat": "PageFault"
      }
     ]
    },
    {
     "title": "Page Fault",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:ins:pagefault_rate1m{ip=\"$ip\"}",
       "legendFormat": "PageFault"
      }
     ]
    },
    {
     "title": "Writeback",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{ip=\"$ip\"}",
       "legendFormat": "Writeback"
      }
     ]
    },
    {
     "title": "Dirty Bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Dirty_bytes{ip=\"$ip\"}",
       "legendFormat": "Writeback"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk iostat",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (device) (irate(node_disk_io_time_seconds_total{ip=\"$ip\"}[1m]))",
       "legendFormat": "util"
      },
      {
       "expr": "max by (device) (irate(node_disk_io_time_weighted_seconds_total{ip=\"$ip\"}[1m]))",
       "legendFormat": "queue"
      },
      {
       "expr": "max by (device) (irate(node_disk_reads_completed_total{ip=\"$ip\"}[1m]))",
       "legendFormat": "r/s"
      },
      {
       "expr": "max by (device) (irate(node_disk_writes_completed_total{ip=\"$ip\"}[1m]))",
       "legendFormat": "w/s"
      },
      {
       "expr": "max by (device) (irate(node_disk_reads_merged_total{ip=\"$ip\"}[1m]))",
       "legendFormat": "mr/s"
      },
      {
       "expr": "max by (device) (irate(node_disk_writes_merged_total{ip=\"$ip\"}[1m]))",
       "legendFormat": "mw/s"
      },
      {
       "expr": "max by (device) (node:dev:disk_read_bytes_rate1m{ip=\"$ip\"})",
       "legendFormat": "rb/s"
      },
      {
       "expr": "max by (device) (irate(node_disk_written_bytes_total{ip=\"$ip\"}[1m]))",
       "legendFormat": "wb/s"
      },
      {
       "expr": "max by (device) (node:dev:disk_read_rt_1m{ip=\"$ip\"})",
       "legendFormat": "r_await"
      },
      {
       "expr": "max by (device) (node:dev:disk_write_rt_1m{ip=\"$ip\"})",
       "legendFormat": "w_await"
      },
      {
       "expr": "max by (device) (node:dev:disk_read_batch_1m{ip=\"$ip\"})",
       "legendFormat": "rreq-sz"
      },
      {
       "expr": "max by (device) (node:dev:disk_write_batch_1m{ip=\"$ip\"})",
       "legendFormat": "wreq-sz"
      }
     ]
    },
    {
     "title": "Read/Write IOPS",
     "type": "timeseries",
     "description": "▲ for read IOPS, ▼ for write IOPS",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:dev:disk_reads_rate1m{ip=\"$ip\"}",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- node:dev:disk_writes_rate1m{ip=\"$ip\"}",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Bandwidth",
     "type": "timeseries",
     "description": "▲ for read bandwidth, ▼ for write bandwidth",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:dev:disk_read_bytes_rate1m{ip=\"$ip\"}",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- node:dev:disk_write_bytes_rate1m{ip=\"$ip\"}",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Reads/Writes Merged Ratio",
     "type": "timeseries",
     "description": "Merged ratio of read / write requests\n▲ for read ▼ for write",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:dev:disk_mreads_ratio1m{ip=\"$ip\"}",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- node:dev:disk_mwrites_ratio1m{ip=\"$ip\"}",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Request Size (areq-sz)",
     "type": "timeseries",
     "description": "▲ for read, ▼ for write, Showing I/O pattern",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node:dev:disk_read_batch_1m{ip=\"$ip\"}",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- node:dev:disk_write_batch_1m{ip=\"$ip\"}",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Await Time",
     "type": "timeseries",
     "description": "▲ for read rt, ▼ for write rt",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node:dev:disk_read_rt_1m{ip=\"$ip\"}",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- node:dev:disk_write_rt_1m{ip=\"$ip\"}",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Average Service Time (svctm)",
     "type": "timeseries",
     "description": "▲ for read rt, ▼ for write rt",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node:dev:disk_io_rt_1m{ip=\"$ip\"}",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Instant Queue Size",
     "type": "timeseries",
     "description": "Number of items which were in the queue at the sampling time point",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_disk_io_now{ip=\"$ip\"}",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "average number of operations waiting to be serviced.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:dev:disk_avg_queue_size{ip=\"$ip\"}",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node:fs:size_bytes{ip=\"$ip\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "max by (device) (node:fs:avail_bytes{ip=\"$ip\"})",
       "legendFormat": "Avail"
      },
      {
       "expr": "max by (device) (node:fs:size_bytes{ip=\"$ip\"} - node:fs:avail_bytes{ip=\"$ip\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "max by (device) (node:fs:space_usage{ip=\"$ip\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "max by (device) (node:fs:inode_total{ip=\"$ip\"})",
       "legendFormat": "iNodes"
      },
      {
       "expr": "max by (device) (node:fs:inode_free{ip=\"$ip\"})",
       "legendFormat": "iNode Free"
      },
      {
       "expr": "max by (device) (node:fs:inode_used{ip=\"$ip\"})",
       "legendFormat": "iNode Used"
      },
      {
       "expr": "max by (device) (node:fs:inode_usage{ip=\"$ip\"})",
       "legendFormat": "iNode Usage"
      },
      {
       "expr": "min by (device) (node_filesystem_readonly{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "iNode Usage"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:space_usage{ip=\"$ip\"}",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Avail Space 1D Prediction",
     "type": "stat",
     "description": "Prediction of avail filesystem space a day later!",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:space_predict_1d{ip=\"$ip\"}",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "iNode Usage",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:inode_usage{ip=\"$ip\"}",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Device Error",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_device_error{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Derive 1h",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node:fs:space_deriv1h{ip=\"$ip\"}",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:fs:space_usage{ip=\"$ip\"}",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Exhaust Estimate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time(node:fs:space_exhaust{ip=\"$ip\"}[5m])",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "FD Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{ip=\"$ip\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "node:ins:fd_usage{ip=\"$ip\"}",
       "legendFormat": "Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_network_info{ip=\"$ip\"}",
       "legendFormat": "INFO"
      },
      {
       "expr": "max by (device) (node_network_mtu_bytes{ip=\"$ip\"})",
       "legendFormat": "MTU"
      },
      {
       "expr": "max by (device) (node_network_speed_bytes{ip=\"$ip\"}) * 8",
       "legendFormat": "Link Speed"
      },
      {
       "expr": "min by (device) (node:dev:network_tx_bytes_rate1m{ip=\"$ip\"})",
       "legendFormat": "Transmit"
      },
      {
       "expr": "min by (device) (node:dev:network_rx_bytes_rate1m{ip=\"$ip\"})",
       "legendFormat": "Receive"
      },
      {
       "expr": "min by (device) (node:dev:network_tx_pps1m{ip=\"$ip\"})",
       "legendFormat": "TX PPS"
      },
      {
       "expr": "min by (device) (node:dev:network_rx_bytes_rate1m{ip=\"$ip\"})",
       "legendFormat": "RX PPS"
      }
     ]
    },
    {
     "title": "Transmit/Receive Packets",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:ins:network_tx_pps1m{ip=\"$ip\"}",
       "legendFormat": "▲TX"
      },
      {
       "expr": "- node:ins:network_rx_pps1m{ip=\"$ip\"}",
       "legendFormat": "▼RX"
      }
     ]
    },
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:ins:network_tx_bytes_rate1m{ip=\"$ip\"}",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- node:ins:network_rx_bytes_rate1m{ip=\"$ip\"}",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Packets (Interface)",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:dev:network_tx_pps1m{ip=\"$ip\", device!=\"lo\"}",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- node:dev:network_rx_pps1m{ip=\"$ip\", device!=\"lo\"}",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Bandwidth (Interface)",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:dev:network_tx_bytes_rate1m{ip=\"$ip\"}",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- node:dev:network_rx_bytes_rate1m{ip=\"$ip\"}",
       "legendFormat": "▼{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Segments",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:ins:tcp_insegs_rate1m{ip=\"$ip\"}",
       "legendFormat": "▼in"
      },
      {
       "expr": "- node:ins:tcp_outsegs_rate1m{ip=\"$ip\"}",
       "legendFormat": "▲out"
      }
     ]
    },
    {
     "title": "UDP Datagrams",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_InDatagrams{ip=\"$ip\"}[1m])",
       "legendFormat": "▼in"
      },
      {
       "expr": "- rate(node_netstat_Udp_OutDatagrams{ip=\"$ip\"}[1m])",
       "legendFormat": "▲out"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{ip=\"$ip\"}",
       "legendFormat": "Current"
      }
     ]
    },
    {
     "title": "TCP Socket Stat",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_inuse{ip=\"$ip\"}",
       "legendFormat": "Using"
      },
      {
       "expr": "- node_sockstat_TCP_tw{ip=\"$ip\"}",
       "legendFormat": "Time Wait"
      }
     ]
    },
    {
     "title": "TCP Open",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens{ip=\"$ip\"}[1m])",
       "legendFormat": "active"
      },
      {
       "expr": "- rate(node_netstat_Tcp_PassiveOpens{ip=\"$ip\"}[1m])",
       "legendFormat": "passive"
      }
     ]
    },
    {
     "title": "TCP Retransmit",
     "type": "timeseries",
     "description": "TCP retransmission segments and rate",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:ins:tcp_retranssegs_rate1m{ip=\"$ip\"}",
       "legendFormat": "Retrans Segs"
      },
      {
       "expr": "node:ins:tcp_retrans_ratio1m{ip=\"$ip\"}",
       "legendFormat": "Rate"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{ip=\"$ip\"}[1m])",
       "legendFormat": "Listen Overflows"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{ip=\"$ip\"}[1m])",
       "legendFormat": "Listen Drop"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{ip=\"$ip\"}[1m])",
       "legendFormat": "Retrans"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{ip=\"$ip\"}[1m])",
       "legendFormat": "In Error"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (ins) (node_timex_sync_status{ip=\"$ip\"})",
       "legendFormat": "{{ ins }}"
      },
      {
       "expr": "max by (ins) (node_timex_status{ip=\"$ip\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (node_timex_offset_seconds{ip=\"$ip\"})",
       "legendFormat": "{{ ins }}"
      },
      {
       "expr": "max by (ins) (node_timex_frequency_adjustment_ratio{ip=\"$ip\"}) - 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Offset (s)",
     "type": "timeseries",
     "description": "node_timex_offset_seconds: This metric represents the current time offset in seconds between the system clock and a reference time source.",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_offset_seconds{ip=\"$ip\"}",
       "legendFormat": "Offset"
      }
     ]
    },
    {
     "title": "Time Sync Status & Clock Freq Adjust%",
     "type": "timeseries",
     "description": "node_timex_sync_status: This metric indicates the synchronization status of the timekeeping system. if != 1 then time out of sync.\n\nnode_timex_frequency_adjustment_ratio: It indicates the ratio of the current frequency adjustment to the nominal frequency, used to keep the system clock synchronized.",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_sync_status{ip=\"$ip\"}",
       "legendFormat": "Synced"
      },
      {
       "expr": "node_timex_frequency_adjustment_ratio{ip=\"$ip\"} - 1",
       "legendFormat": "Adjust"
      }
     ]
    },
    {
     "title": "Node Exporter Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{ip=\"$ip\"}",
       "legendFormat": "{{ collector }}"
      }
     ]
    },
    {
     "title": "Hardware Temperature",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{ip=\"$ip\"}",
       "legendFormat": "{{ chip }}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Syslog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ip:$ip job:syslog | stats by (app) count() as count",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "type": "logs",
   "description": "Recent syslog logs for this node instance",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "ip:$ip job:syslog | fields level,unit,_msg"
    }
   ]
  }
 ]
}