{
 "title": "Node Cluster",
 "description": "Node: Cluster Dashboard",
 "tags": [
  "Pigsty",
  "NODE",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(node_load1, cls)" } },
   {
    "name": "members",
    "label": "IP Address",
    "query": {
     "query": "label_values(node_load1{cls=\"$cls\"}, ip)"
    }
   },
   {
    "name": "pg_cls",
    "label": "IP Address",
    "query": {
     "query": "label_values(pg_up{ip=~\"$members\"},cls)"
    }
   },
   {
    "name": "vip",
    "label": "VIP Address",
    "query": {
     "query": "label_values(probe_success{cls=\"$cls\"},vip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "All nodes among cluster ${cls}",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "node_up{cls=\"$cls\"}"
    },
    {
     "expr": "group without(ins,cls,instance) (node_uname_info{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_usage{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:mem_usage{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ip,instance) (node:ins:space_usage_max{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_count{cls=\"$cls\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{cls=\"$cls\"}) / 1073741824"
    },
    {
     "expr": "sum(node:fs:size_bytes{cls=\"$cls\", fstype!~\"fuse.juicefs\"}) by (ip) / 1073741824"
    },
    {
     "expr": "count by (ip) (up{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ip) (probe_duration_seconds{cls=\"$cls\", job=\"ping\"})"
    },
    {
     "expr": "sum by (ip) (haproxy_backend_current_sessions{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ip) (node_up{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_load1{cls=\"$cls\"}) by (ip))",
     "legendFormat": "Node"
    },
    {
     "expr": "node:cls:cpu_count{cls=\"$cls\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{cls=\"$cls\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node:cls:size_bytes{cls=\"$cls\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,vip) (probe_duration_seconds{cls=\"$cls\", job=~\".*vip\"})",
     "legendFormat": "{{ vip }} @ {{ job }}"
    },
    {
     "expr": "probe_duration_seconds{cls=\"$cls\", job=\"ping\"}",
     "legendFormat": "{{ ip }} : {{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow = Agent (Patroni / PG Exporters)\n\nPink = MinIO / RustFS\n\nTeal = Kafka\n\nMySQL Blue = MySQL\n\nKubernetes Blue = Kubernetes",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ip=~\"$members\"}",
     "legendFormat": "postgres {{ ins }}"
    },
    {
     "expr": "pgbouncer_up{ip=~\"$members\"}",
     "legendFormat": "pgbouncer {{ ins }}"
    },
    {
     "expr": "patroni_up{ip=~\"$members\"}",
     "legendFormat": "patroni {{ ins }}"
    },
    {
     "expr": "pg_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pg_exporter {{ ins }}"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pgb_exporter {{ ins }}"
    },
    {
     "expr": "node_up{ip=~\"$members\"}",
     "legendFormat": "node {{ ins }}"
    },
    {
     "expr": "haproxy_up{ip=~\"$members\"}",
     "legendFormat": "haproxy {{ ins }}"
    },
    {
     "expr": "docker_up{ip=~\"$members\"}",
     "legendFormat": "docker {{ ins }}"
    },
    {
     "expr": "vector_up{ip=~\"$members\"}",
     "legendFormat": "vector {{ ins }}"
    },
    {
     "expr": "max by (ins) (up{job=\"juice\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"nginx\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"grafana\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmetrics\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vlogs\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vtraces\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmalert\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"alertmanager\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "etcd_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "redis_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "minio_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "rustfs_up{job=\"minio\",flavor=\"rustfs\",ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mongo_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mysql_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mysql_exporter_up{ip=~\"$members\"}",
     "legendFormat": "mysql_exporter"
    },
    {
     "expr": "kafka_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min by (ins) (up{job=\"kube\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pgbackrest {{ ins }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:cls:cpu_usage_1m{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "node:ins:cpu_usage_1m{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}} @ {{ instance }}"
    },
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:cpu_usage{cls=\"$cls\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:stdload1{cls=\"$cls\"}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:ins:mem_usage{cls=\"$cls\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{cls=\"$cls\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:ins:fd_usage{cls=\"$cls\"})",
     "legendFormat": "FD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:inode_usage{cls=\"$cls\"})",
     "legendFormat": "iNode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:cls:disk_iops_1m{cls=\"$cls\"})",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:disk_io_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "Disk IO"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:cls:network_io_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "Net Traff"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:ins:tcp_error_rate1m{cls=\"$cls\"})",
     "legendFormat": "TCP Errs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:ins:tcp_retrans_ratio1m{cls=\"$cls\"})",
     "legendFormat": "Retrans"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_timex_sync_status{cls=\"$cls\"})",
     "legendFormat": "Time Sync"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:cls:cpu_usage{cls=\"$cls\"}",
       "legendFormat": "Realtime"
      },
      {
       "expr": "node:cls:cpu_usage_1m{cls=\"$cls\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node:cls:cpu_usage_5m{cls=\"$cls\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node:cls:cpu_usage_15m{cls=\"$cls\"}",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "Cluster CPU Time by State (per Second)",
     "type": "timeseries",
     "description": "Sum of all state will approximately to the number of cpu core",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{cls=\"$cls\"}[1m]))",
       "legendFormat": "{{ mode }}"
      },
      {
       "expr": "sum(node:cls:cpu_count{cls=\"$cls\"})",
       "legendFormat": "CPU Count"
      }
     ]
    },
    {
     "title": "Instance CPU Usage (1m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:cpu_usage_1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node:ins:cpu_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Normalized Load (1m, 5m, 15m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:cls:stdload1{cls=\"$cls\"}",
       "legendFormat": "load1"
      },
      {
       "expr": "node:cls:stdload5{cls=\"$cls\"}",
       "legendFormat": "load5"
      },
      {
       "expr": "node:cls:stdload15{cls=\"$cls\"}",
       "legendFormat": "load15"
      }
     ]
    },
    {
     "title": "Instance Normalized Load (1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:stdload1{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Blocked Processes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_procs_blocked{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Process in D State",
     "type": "timeseries",
     "description": "Uninterruptible sleep (usually IO)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_processes_state{cls=\"$cls\", state=\"D\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Thread",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_processes_threads{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Context Switch",
     "type": "timeseries",
     "description": "Context switch rate 1m",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:ctx_switch_rate1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Fork",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:forks_rate1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Interrupt",
     "type": "timeseries",
     "description": "Interrupt Rate 1m",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:interrupt_rate1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Memory usage ratio for each nodes:\n(total - avail) / total",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:mem_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Memory Committed Ratio",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{cls=\"$cls\"} / node_memory_CommitLimit_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:swap_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Cluster Memory Structure",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_Hugepagesize_bytes{cls=\"$cls\"} * node_memory_HugePages_Total{cls=\"$cls\"} )",
       "legendFormat": "HugePage"
      },
      {
       "expr": "sum(node:ins:mem_kernel{cls=\"$cls\"})",
       "legendFormat": "Kernel"
      },
      {
       "expr": "sum(node:ins:mem_rss{cls=\"$cls\"})",
       "legendFormat": "Application RSS"
      },
      {
       "expr": "sum(node_memory_Cached_bytes{cls=\"$cls\"}  - node_memory_Mapped_bytes{cls=\"$cls\"})",
       "legendFormat": "Cache"
      },
      {
       "expr": "sum(node_memory_Buffers_bytes{cls=\"$cls\"})",
       "legendFormat": "Buffer"
      },
      {
       "expr": "sum(node_memory_MemFree_bytes{cls=\"$cls\"})",
       "legendFormat": "Free"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{cls=\"$cls\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Page In/Out Rate",
     "type": "timeseries",
     "description": "Rate of pages in/out/swapin/swapout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:pagein_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:pageout_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Swap In/Out Rate",
     "type": "timeseries",
     "description": "Rate of pages in/out/swapin/swapout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:ins:swapin_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:swapout_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Dirty Bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Dirty_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Write Back",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Major Page Fault (Rate1m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:ins:pgmajfault_rate1m{cls=\"$cls\"}",
       "legendFormat": "PageFault"
      }
     ]
    },
    {
     "title": "Page Fault (Rate1m)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:ins:pagefault_rate1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read/Write IOPS",
     "type": "timeseries",
     "description": "▲ for read IOPS, ▼ for write IOPS",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node:ins:disk_reads_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:disk_writes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Read/Write Bandwidth",
     "type": "timeseries",
     "description": "▲ for read bandwidth, ▼ for write bandwidth",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:ins:disk_read_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:disk_write_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Reads/Writes Merged Ratio",
     "type": "timeseries",
     "description": "Merged ratio of read / write requests\n▲ for read ▼ for write",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:dev:disk_mreads_ratio1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:dev:disk_mwrites_ratio1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Request Size (areq-sz)",
     "type": "timeseries",
     "description": "▲ for read, ▼ for write, Showing I/O pattern",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node:dev:disk_read_batch_1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:dev:disk_write_batch_1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Await Time",
     "type": "timeseries",
     "description": "▲ for read rt, ▼ for write rt",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node:dev:disk_read_rt_1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:dev:disk_write_rt_1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Average Service Time (svctm)",
     "type": "timeseries",
     "description": "▲ for read rt, ▼ for write rt",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node:dev:disk_io_rt_1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Instant Queue Size",
     "type": "timeseries",
     "description": "Number of items which were in the queue at the sampling time point",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_disk_io_now{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "average number of operations waiting to be serviced.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node:dev:disk_avg_queue_size{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Space Usage",
     "type": "stat",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:space_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Avail Space 1D Prediction",
     "type": "stat",
     "description": "Prediction of avail filesystem space a day later!",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:space_predict_1d{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "iNode Usage",
     "type": "stat",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node:fs:inode_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Device Error",
     "type": "stat",
     "gridPos": { "h": 14, "w": 6, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_device_error{cls=\"$cls\", fstype!~\"(n|root|tmp)fs.*\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Derive 1h",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node:fs:space_deriv1h{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:fs:space_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Exhaust Estimate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node:fs:space_exhaust{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "FD Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:fd_usage{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transmit/Receive Packets",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:ins:network_tx_pps1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:network_rx_pps1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:ins:network_tx_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "- node:ins:network_rx_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Packets (Interface)",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:dev:network_tx_pps1m{cls=\"$cls\", device!=\"lo\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:ins:network_rx_pps1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Bandwidth (Interface)",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "node:dev:network_tx_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}:{{ device }}"
      },
      {
       "expr": "- node:dev:network_rx_bytes_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}:{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Segments",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "node:ins:tcp_insegs_rate1m{cls=\"$cls\"}",
       "legendFormat": "▼{{ ins }}"
      },
      {
       "expr": "- node:ins:tcp_outsegs_rate1m{cls=\"$cls\"}",
       "legendFormat": "▲{{ ins }}"
      }
     ]
    },
    {
     "title": "UDP Datagrams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "- rate(node_netstat_Udp_OutDatagrams{cls=\"$cls\"}[1m])",
       "legendFormat": "▲{{ ins }}"
      },
      {
       "expr": "rate(node_netstat_Udp_InDatagrams{cls=\"$cls\"}[1m])",
       "legendFormat": "▼{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Socket InUse",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_inuse{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Socket TimeWait",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_tw{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      },
      { "legendFormat": "Time Wait" }
     ]
    },
    {
     "title": "TCP Retransmission Rate",
     "type": "timeseries",
     "description": "TCP retransmission segments and rate",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node:ins:tcp_retrans_ratio1m{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Active Open (Rate1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Passive Open (Rate1m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_PassiveOpens{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }} Listen Overflows"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }} Listen Drop"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }} In Error"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{cls=\"$cls\"}[1m])",
       "legendFormat": "{{ ins }} Retrans"
      }
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ping Overview",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (job,vip) (probe_duration_seconds{cls=\"$cls\", job=~\".*vip\"})",
       "legendFormat": "{{ vip }} @ {{ job }}"
      },
      {
       "expr": "probe_duration_seconds{cls=\"$cls\", job=\"ping\"}",
       "legendFormat": "{{ ip }} : {{ ins }}"
      }
     ]
    },
    {
     "title": "Ping Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 29 },
     "targets": [
      {
       "expr": "probe_success{ip=~\"$members\", job=\"ping\"}"
      },
      {
       "expr": "max by (ip) (probe_duration_seconds{ip=~\"$members\", job=\"ping\"})"
      },
      {
       "expr": "max by (ip) (probe_dns_lookup_time_seconds{ip=~\"$members\", job=\"ping\"})"
      },
      {
       "expr": "max by (ip) (probe_icmp_duration_seconds{ip=~\"$members\", job=\"ping\", phase=\"setup\"})"
      },
      {
       "expr": "max by (ip) (probe_icmp_duration_seconds{ip=~\"$members\", job=\"ping\", phase=\"rtt\"})"
      },
      {
       "expr": "max by (ip) (probe_icmp_duration_seconds{ip=~\"$members\", job=\"ping\", phase=\"resolve\"})"
      }
     ]
    },
    {
     "title": "Ping RT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_duration_seconds{ip=~\"$members\", job=\"ping\"}",
       "legendFormat": "{{ ins }}@{{ ip }}"
      },
      {
       "expr": "avg by (job,vip) (probe_duration_seconds{ip=~\"$members\", job=~\".*-vip\"})",
       "legendFormat": "{{ job }} @ {{ vip }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Keepalived",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Keepalived Role",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "keepalived_vrrp_become_master{vip=\"$vip\"}",
       "legendFormat": "{{ state }} : {{ ip }}"
      }
     ]
    },
    {
     "title": "Keepalived Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 30 },
     "targets": [
      {
       "expr": "keepalived_exporter_up{vip=\"$vip\"} * on(ins) group_left()\nkeepalived_up{vip=\"$vip\"} or on (ins) keepalived_exporter_up{vip=\"$vip\"}"
      },
      {
       "expr": "max by (ins,state,vrid,name) (keepalived_vrrp_become_master{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_release_master{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (rate(keepalived_vrrp_advert_rcvd{vip=\"$vip\"}[1m]))"
      },
      {
       "expr": "max by (ins) (rate(keepalived_vrrp_advert_sent{vip=\"$vip\"}[1m]))"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_pri_zero_rcvd{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_pri_zero_sent{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_ip_ttl_err{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_invalid_type_rcvd{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_addr_list_err{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_invalid_authtype{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_authtype_mismatch{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_auth_failure{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_packet_len_err{vip=\"$vip\"})"
      },
      {
       "expr": "max by (ins) (keepalived_vrrp_advert_interval_err{vip=\"$vip\"})"
      }
     ]
    },
    {
     "title": "VIP MASTER Status",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "keepalived_vrrp_advert_sent{cls=\"$cls\", state=\"MASTER\"} > bool 0",
       "legendFormat": "{{ ip }} : {{ ins }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (ins) (node_timex_sync_status{cls=\"$cls\"})",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Node Time Metrics",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by (ins) (node_timex_sync_status{cls=\"$cls\"})",
       "legendFormat": "{{ ins }}"
      },
      {
       "expr": "max by (ins) (node_timex_status{cls=\"$cls\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (ins) (node_timex_offset_seconds{cls=\"$cls\"})",
       "legendFormat": "{{ ins }}"
      },
      {
       "expr": "max by (ins) (node_timex_frequency_adjustment_ratio{cls=\"$cls\"}) - 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Frequency Adjustment Ratio",
     "type": "timeseries",
     "description": "node_timex_frequency_adjustment_ratio: It indicates the ratio of the current frequency adjustment to the nominal frequency, used to keep the system clock synchronized.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_timex_frequency_adjustment_ratio{cls=\"$cls\"}-1",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Node Exporter Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (collector) (node_scrape_collector_duration_seconds{cls=\"$cls\"})",
       "legendFormat": "{{ collector }}"
      }
     ]
    },
    {
     "title": "Hardware Temperature (Max of Instance)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "max by (ins) (node_hwmon_temp_celsius{cls=\"$cls\"})",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Syslog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "job:syslog ip:in($members) | stats by (app) count() as count",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "type": "logs",
   "description": "Recent syslog logs for selected nodes in this cluster",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "expr": "job:syslog ip:in($members)" }
   ]
  }
 ]
}