{
 "title": "Node Alert",
 "description": "Node key metrics and alerts",
 "tags": [
  "Pigsty",
  "NODE",
  "Overview",
  "Alert"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"node\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"node\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,ip,instance,datname) (ALERTS{alertstate=\"firing\", job=\"node\"})",
     "legendFormat": "[{{ severity }}] {{alertname}} @ {{ cls }}"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{job=\"node\"}"
    }
   ]
  },
  {
   "title": "NodeCpuHigh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "node:ins:cpu_usage_1m", "legendFormat": "{{ ip }}" }
   ]
  },
  { "title": "Error Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Node Syslog Error",
   "type": "logs",
   "description": "Filter syslog with priority < 4, emerg, alert, crit, error",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "job:syslog p:<4 | fields level,unit,ins,ip,_msg"
    }
   ]
  },
  {
   "title": "Node: Schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeLoadHigh",
     "type": "timeseries",
     "description": "Standard Load (divide by cpu count) > 100%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:stdload1", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "Node: Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeOutOfMem",
     "type": "timeseries",
     "description": "Available memory < 10%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:mem_avail", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "Node: Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeMemSwapped",
     "type": "timeseries",
     "description": "Available memory < 10%",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:swap_usage", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "NODE: Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeDiskSlow",
     "type": "timeseries",
     "description": "Disk read/write avg latency > 32ms",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (ip,device) (node:dev:disk_write_rt_1m > node:dev:disk_read_rt_1m or node:dev:disk_read_rt_1m)",
       "legendFormat": "{{ ip}}-{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NODE: Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeFsFull",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:fs:space_usage", "legendFormat": "{{ ip }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFsExhaust",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "node:fs:space_exhaust{}", "legendFormat": "{{ ip }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFsFilesFull",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:fs:inode_usage", "legendFormat": "{{ ins }}:{{ mountpoint }}" }
     ]
    },
    {
     "title": "NodeFdFull",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "node:ins:fd_usage", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "Node: Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeTcpErrHigh",
     "type": "timeseries",
     "description": "TCP Error Rate > 1 / s",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      { "expr": "rate(node:ins:tcp_error[1m])", "legendFormat": "{{ ip }}" }
     ]
    },
    {
     "title": "NodeTcpRetransHigh",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "sci" } },
     "targets": [
      { "expr": "node:ins:tcp_retrans_ratio1m", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  },
  {
   "title": "Node: Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "NodeTimeSync",
     "type": "timeseries",
     "description": "Check ntp protocol / clock sanity",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "min by (ins, ip) (node_timex_sync_status)",
       "legendFormat": "{{ ip }}"
      }
     ]
    },
    {
     "title": "NodeClockSkew",
     "type": "timeseries",
     "description": "Clock time offset alert > 64ms",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "abs(node_timex_offset_seconds)", "legendFormat": "{{ ip }}" }
     ]
    }
   ]
  }
 ]
}