{
 "title": "Redis Cluster",
 "description": "Redis Cluster Dashboard",
 "tags": [
  "Pigsty",
  "REDIS",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_instance_info{job=\"redis\"}, cls)"
    }
   },
   {
    "name": "mode",
    "label": "Mode",
    "query": {
     "query": "label_values(redis_instance_info{job=\"redis\", cls=\"$cls\"}, redis_mode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Cluster" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (ip) (label_replace(redis_up{cls=\"$cls\"}, \"ip\", \"$1\", \"instance\", \"(.*)\\\\:\\\\d+\")))",
     "legendFormat": "Node"
    },
    {
     "expr": "count(redis_up{cls=\"$cls\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(redis_instance_info{cls=\"$cls\", role=\"master\"})",
     "legendFormat": "Primary"
    },
    {
     "expr": "count(redis_instance_info{cls=\"$cls\", role=\"slave\"})",
     "legendFormat": "Replica"
    },
    {
     "expr": "count((count by (db) (redis_db_keys{cls=\"$cls\"})))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(max by (ip) (label_replace(redis_total_system_memory_bytes{cls=\"$cls\"}, \"ip\", \"$1\", \"instance\", \"(.*)\\\\:\\\\d+\")))",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(redis_memory_max_bytes{cls=\"$cls\"})",
     "legendFormat": "Spec"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (redis_mode,maxmemory_policy,version,engine) (label_replace(label_replace(label_replace(redis_instance_info{cls=\"$cls\"}, \"version\", \"$1\", \"redis_version\", \"(.+)\"), \"version\", \"$1\", \"valkey_version\", \"(.+)\"), \"engine\", \"Valkey\", \"valkey_version\", \"(.+)\"))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_enabled{cls=\"$cls\"})",
     "legendFormat": "Cluster"
    },
    {
     "expr": "max(redis_cluster_state{cls=\"$cls\"})",
     "legendFormat": "Status"
    },
    {
     "expr": "avg(redis_cluster_size{cls=\"$cls\"})",
     "legendFormat": "Shards"
    },
    {
     "expr": "min(redis_cluster_known_nodes{cls=\"$cls\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "max(redis_cluster_current_epoch{cls=\"$cls\"})",
     "legendFormat": "Epoch"
    },
    {
     "expr": "min(redis_cluster_my_epoch{cls=\"$cls\"})",
     "legendFormat": "Epoch Min"
    },
    {
     "expr": "max(redis_cluster_slots_assigned{cls=\"$cls\"})",
     "legendFormat": "Slot Assigned"
    },
    {
     "expr": "max(redis_cluster_slots_ok{cls=\"$cls\"})",
     "legendFormat": "Slot OK"
    },
    {
     "expr": "max(redis_cluster_slots_fail{cls=\"$cls\"})",
     "legendFormat": "Slot Fail"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this redis cluster ${cls}.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_instance_info{cls=\"$cls\", role='master'} > 0",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "redis_up{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:cpu_usage{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:mem_usage{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:qps{cls=\"$cls\"}"
    },
    {
     "expr": "redis_memory_max_bytes{cls=\"$cls\"}"
    },
    {
     "expr": "label_replace(label_replace(redis_instance_info{cls=\"$cls\"}, \"version\", \"$1\", \"redis_version\", \"(.+)\"), \"version\", \"$1\", \"valkey_version\", \"(.+)\")"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "redis:node:ip{cls=\"$cls\"}"
    },
    {
     "expr": "redis:node:mem_total{cls=\"$cls\"}"
    },
    {
     "expr": "redis:node:mem_used{cls=\"$cls\"} / redis:node:mem_alloc{cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:cls:cpu_usage{cls=\"$cls\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:cls:mem_usage{cls=\"$cls\"} ",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:cls:qps{cls=\"$cls\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:cls:rt{cls=\"$cls\"}",
     "legendFormat": "RT"
    }
   ]
  },
  {
   "title": "Instance QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{cls=\"$cls\"})",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Number of Keys in this cluster",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum by (ins) (redis_db_keys{cls=\"$cls\"}))",
     "legendFormat": "Keys"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(redis_connections_received_total{cls=\"$cls\"}[1m]))",
     "legendFormat": "Conn Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(redis_errors_total{cls=\"$cls\"}[1m]))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  { "title": "Alert & Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cls=\"$cls\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cls=\"$cls\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}} @ {{ ins }}"
    },
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}} @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Redis Errors",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_errors_total{cls=\"$cls\"}[1m])",
     "legendFormat": "{{ err }} @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Error" }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Node QPS",
   "type": "stat",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:node:qps{cls=\"$cls\"}",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:ins:cpu_usage{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:ins:mem_usage{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis:ins:cpu_usage{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "CPU Usage (Child)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis:ins:cpu_usage_child{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "redis:ins:tx{cls=\"$cls\"}",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "redis:ins:rx{cls=\"$cls\"}",
     "legendFormat": "▼{{ ins }}"
    },
    { "expr": "0", "legendFormat": "Zero" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min(redis_memory_max_bytes{cls=\"$cls\"} )",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Cluster QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:cls:qps{cls=\"$cls\"}",
     "legendFormat": "QPS"
    },
    {
     "expr": "redis:cls:qps_mu{cls=\"$cls\"}",
     "legendFormat": "µ"
    },
    {
     "expr": "redis:cls:qps_mu{cls=\"$cls\"} + redis:cls:qps_sigma{cls=\"$cls\"}",
     "legendFormat": "+σ"
    },
    {
     "expr": "redis:cls:qps_mu{cls=\"$cls\"} - redis:cls:qps_sigma{cls=\"$cls\"}",
     "legendFormat": "-σ"
    },
    {
     "expr": "redis:cls:qps_mu{cls=\"$cls\"} +  3 * redis:cls:qps_sigma{cls=\"$cls\"}",
     "legendFormat": "+3σ"
    },
    {
     "expr": "redis:cls:qps_mu{cls=\"$cls\"} - 3 * redis:cls:qps_sigma{cls=\"$cls\"}",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "Cluster RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis:cls:rt{cls=\"$cls\"}",
     "legendFormat": "RT"
    },
    {
     "expr": "redis:cls:rt_mu{cls=\"$cls\"}",
     "legendFormat": "µ"
    },
    {
     "expr": "redis:cls:rt_mu{cls=\"$cls\"} + redis:cls:rt_sigma{cls=\"$cls\"}",
     "legendFormat": "+σ"
    },
    {
     "expr": "redis:cls:rt_mu{cls=\"$cls\"} - redis:cls:rt_sigma{cls=\"$cls\"}",
     "legendFormat": "-σ"
    },
    {
     "expr": "redis:cls:rt_mu{cls=\"$cls\"} +  3 * redis:cls:rt_sigma{cls=\"$cls\"}",
     "legendFormat": "+3σ"
    },
    {
     "expr": "redis:cls:rt_mu{cls=\"$cls\"} - 3 * redis:cls:rt_sigma{cls=\"$cls\"}",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "Command QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis:cls:cmd_qps{cls=\"$cls\"}",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Instance RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis:ins:rt{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Instance-Command QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis:ins:cmd_qps{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}:{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command QPS Distribution",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:cls:cmd_qps{cls=\"$cls\"}",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis:cls:cmd_rt{cls=\"$cls\"}",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:ins:clients{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Connected Replicas",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_slaves{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Received Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:ins:conn_rate{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Incoming Connection 1 Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "expr": "topk(100,increase(redis_connections_received_total{cls=\"$cls\"}[1d]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Reject Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:ins:conn_reject{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Blocked Client Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "redis:ins:blocked_clients{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Key Expired",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis:ins:key_expire{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Keys (per DB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{cls=\"$cls\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Key Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis:ins:key_evict{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Keys (per Instance)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (redis_db_keys{cls=\"$cls\"})",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Average TTL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "redis_db_avg_ttl_seconds{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Key Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis:ins:key_hit_rate{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "Replication",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "label_join(label_replace(redis_slave_info{cls=\"$cls\"}, \"replica_ins\", \"$1\", \"ins\", \"(.+)\"), 'ins', ':', 'master_host', 'master_port')"
    }
   ]
  },
  {
   "title": "Replication Offset Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis:ins:lsn_rate{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Sentinel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "type": "table",
   "description": "Sentinel Instance that monitoring this cluster leader",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "min by (ins,master_name, master_address,master_status) (redis_sentinel_master_status{master_name='$cls'})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins) (redis_sentinel_master_slaves{master_name='$cls'})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins) (redis_sentinel_master_ok_slaves{master_name='$cls'})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins) (redis_sentinel_master_sentinels{master_name='$cls'})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins) (redis_sentinel_master_ok_sentinels{master_name='$cls'})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins) (redis_sentinel_master_ckquorum_status{master_name='$cls'})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "Redis Cluster Logs",
   "type": "timeseries",
   "description": "Redis Log Events of this cluster $cls",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cls:$cls job:redis | stats by (ins) count() as count",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 164 },
   "targets": [
    { "expr": "cls:$cls job:redis", "legendFormat": "{{ ins }}" }
   ]
  }
 ]
}