{
 "title": "Redis Instance",
 "description": "Redis Instance Dashboard",
 "tags": [
  "Pigsty",
  "REDIS",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "id", "label": "Instance", "query": { "query": "label_values(redis:ins, id)" } },
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(redis:ins{id=\"$id\"}, ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(redis_instance_info{job=\"redis\", ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(redis:ins{id=\"$id\"}, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(redis:ins{id=\"$id\"}, instance)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"}, nodename)"
    }
   },
   {
    "name": "addr",
    "label": "Address",
    "query": {
     "query": "label_values(redis:ins{id=\"$id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Instance" },
    { "expr": "1", "legendFormat": "Addr" },
    { "expr": "1", "legendFormat": "Cluster" },
    { "expr": "1", "legendFormat": "IP" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "redis_up{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:cpu_usage{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:mem_usage{cls=\"$cls\"}"
    },
    {
     "expr": "redis:ins:qps{cls=\"$cls\"}"
    },
    {
     "expr": "redis_memory_max_bytes{cls=\"$cls\"}"
    },
    {
     "expr": "label_replace(label_replace(redis_instance_info{cls=\"$cls\"}, \"version\", \"$1\", \"redis_version\", \"(.+)\"), \"version\", \"$1\", \"valkey_version\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "Config",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(redis_instance_info{ins=\"$ins\"}, \"version\", \"$1\", \"redis_version\", \"(.+)\"), \"version\", \"$1\", \"valkey_version\", \"(.+)\"), \"engine\", \"Redis\", \"redis_version\", \"(.+)\"), \"engine\", \"Valkey\", \"valkey_version\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_slave_info{master_host=\"$ip\", master_port=\"$port\"}",
     "legendFormat": "Leading {{ instance }}"
    },
    {
     "expr": "max by (upstream) (label_join(redis_slave_info{ins=\"$ins\"}, 'upstream', ':', 'master_host', 'master_port'))",
     "legendFormat": "Following {{ upstream }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{ins=\"$ins\"} / redis_memory_max_bytes{ins=\"$ins\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "redis_memory_used_bytes{ins=\"$ins\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "redis_memory_max_bytes{ins=\"$ins\"}",
     "legendFormat": "Config"
    },
    {
     "expr": "max(label_replace(redis_total_system_memory_bytes{ins=\"$ins\"}, \"ip\", \"$1\", \"instance\", \"(.*)\\\\:\\\\d+\"))",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_total{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:ins:cpu_usage{ins=\"$ins\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:ins:mem_usage{ins=\"$ins\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:ins:qps{ins=\"$ins\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{ins=\"$ins\"})",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis:ins:rt{ins=\"$ins\"}",
     "legendFormat": "RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{ins=\"$ins\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", ins=\"$ins\"})",
     "legendFormat": "Pending Alert"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 4, "w": 10, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}} @ {{ ins }}"
    },
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}} @ {{ ins }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Redis Errors",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_errors_total{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ err }}"
    },
    { "expr": "0", "legendFormat": "Error" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_enabled{cls=\"$cls\"})",
     "legendFormat": "Cluster"
    },
    {
     "expr": "max(redis_cluster_state{cls=\"$cls\"})",
     "legendFormat": "Status"
    },
    {
     "expr": "avg(redis_cluster_size{cls=\"$cls\"})",
     "legendFormat": "Shards"
    },
    {
     "expr": "min(redis_cluster_known_nodes{cls=\"$cls\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "max(redis_cluster_current_epoch{cls=\"$cls\"})",
     "legendFormat": "Epoch"
    },
    {
     "expr": "min(redis_cluster_my_epoch{cls=\"$cls\"})",
     "legendFormat": "Epoch Min"
    },
    {
     "expr": "max(redis_cluster_slots_assigned{cls=\"$cls\"})",
     "legendFormat": "Slot Assigned"
    },
    {
     "expr": "max(redis_cluster_slots_ok{cls=\"$cls\"})",
     "legendFormat": "Slot OK"
    },
    {
     "expr": "max(redis_cluster_slots_fail{cls=\"$cls\"})",
     "legendFormat": "Slot Fail"
    }
   ]
  },
  { "title": "OS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis:ins:cpu_usage{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "CPU Usage (Child)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis:ins:cpu_usage_child{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "redis:ins:rx{ins=\"$ins\"}",
     "legendFormat": "⬇️RX"
    },
    {
     "expr": "-redis:ins:tx{ins=\"$ins\"}",
     "legendFormat": "⬆️TX"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{ins=\"$ins\"}",
     "legendFormat": "used"
    },
    {
     "expr": "min(redis_memory_max_bytes{ins=\"$ins\"} )",
     "legendFormat": "max"
    },
    {
     "expr": "redis:ins:mem_usage{ins=\"$ins\"}",
     "legendFormat": "usage"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Instance QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:ins:qps{ins=\"$ins\"}",
     "legendFormat": "QPS"
    },
    {
     "expr": "redis:ins:qps_mu{ins=\"$ins\"}",
     "legendFormat": "µ"
    },
    {
     "expr": "redis:ins:qps_mu{ins=\"$ins\"} + redis:ins:qps_sigma{ins=\"$ins\"}",
     "legendFormat": "+σ"
    },
    {
     "expr": "redis:ins:qps_mu{ins=\"$ins\"} - redis:ins:qps_sigma{ins=\"$ins\"}",
     "legendFormat": "-σ"
    },
    {
     "expr": "redis:ins:qps_mu{ins=\"$ins\"} +  3 * redis:ins:qps_sigma{ins=\"$ins\"}",
     "legendFormat": "+3σ"
    },
    {
     "expr": "redis:ins:qps_mu{ins=\"$ins\"} - 3 * redis:ins:qps_sigma{ins=\"$ins\"}",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "Instance RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis:ins:rt{ins=\"$ins\"}",
     "legendFormat": "RT"
    },
    {
     "expr": "redis:ins:rt_mu{ins=\"$ins\"}",
     "legendFormat": "µ"
    },
    {
     "expr": "redis:ins:rt_mu{ins=\"$ins\"} + redis:ins:rt_sigma{ins=\"$ins\"}",
     "legendFormat": "+σ"
    },
    {
     "expr": "redis:ins:rt_mu{ins=\"$ins\"} - redis:ins:rt_sigma{ins=\"$ins\"}",
     "legendFormat": "-σ"
    },
    {
     "expr": "redis:ins:rt_mu{ins=\"$ins\"} +  3 * redis:ins:rt_sigma{ins=\"$ins\"}",
     "legendFormat": "+3σ"
    },
    {
     "expr": "redis:ins:rt_mu{ins=\"$ins\"} - 3 * redis:ins:rt_sigma{ins=\"$ins\"}",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "Command QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis:ins:cmd_qps{ins=\"$ins\"}",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command QPS (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_total{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis:ins:cmd_rt{ins=\"$ins\"}",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command Time (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(redis_commands_duration_seconds_total{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command Distribution (Realtime)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis:ins:cmd_qps{ins=\"$ins\"}",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Command Time Distribution (1 Day)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cmd) (increase(redis_commands_duration_seconds_total{ins=\"$ins\"}[1d]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:ins:clients{ins=\"$ins\"}",
     "legendFormat": "clients"
    }
   ]
  },
  {
   "title": "Connected Replicas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_slaves{ins=\"$ins\"}",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "Received Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:ins:conn_rate{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_blocked_clients{ins=\"$ins\"}",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Reject Connection Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:ins:conn_reject{ins=\"$ins\"}",
     "legendFormat": "reject"
    }
   ]
  },
  {
   "title": "Blocked Client Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis:ins:blocked_clients{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Key Expired",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis:ins:key_expire{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (redis_db_keys{ins=\"$ins\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Key Evicted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis:ins:key_evict{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Keys (per DB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{ins=\"$ins\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Average TTL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_db_avg_ttl_seconds{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Key Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "redis:ins:key_hit_rate{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Persist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Latest Fork Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_latest_fork_seconds{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Latest AOF Rewrite Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_aof_last_rewrite_duration_sec{ins=\"$ins\"} > 0",
     "legendFormat": "{{ ins }}"
    },
    { "expr": "0", "legendFormat": "zero" }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Replication",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "label_join(label_replace(redis_slave_info{cls=\"$cls\"}, \"replica_ins\", \"$1\", \"ins\", \"(.+)\"), 'ins', ':', 'master_host', 'master_port')"
    }
   ]
  },
  {
   "title": "Replication Offset Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "redis:ins:lsn_rate{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Redis Instance Logs",
   "type": "timeseries",
   "description": "Redis Log of this instance: $ins",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ins:$ins job:redis | stats count() as count",
     "legendFormat": "{{ src }}"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 132 },
   "targets": [
    { "expr": "ins:$ins job:redis" }
   ]
  }
 ]
}