{
 "title": "PGCAT Database",
 "description": "PostgreSQL Catalog Explorer for Single Database",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn:text}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn:text}';" },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn:text}';" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Database",
        "type": "string",
        "values": [ "${datname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$ins" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:xact_rt_1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins,instance) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "Databases of this instance\nTmpl: is this database a template?\nConn: is this database connectable?",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.oid::INTEGER, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate,datallowconn,  1 - (datistemplate)::INTEGER + 2 * d.datallowconn::INTEGER AS status, psd.numbackends AS sessions,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,  pg_catalog.array_to_string(d.datacl, E'\\n') AS acl,\n       CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') THEN pg_catalog.pg_database_size(d.datname) ELSE -1 END AS size,\n       t.spcname as tablespace,\n       pg_catalog.shobj_description(d.oid, 'pg_database') as description\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT pg_catalog.shobj_description(d.oid, 'pg_database') as description FROM pg_database d WHERE datname = '$datname';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT d.datname, d.datconnlimit, d.datfrozenxid, age(d.datfrozenxid) AS age, datistemplate, datallowconn,\n       pg_catalog.pg_get_userbyid(d.datdba) as owner, pg_catalog.pg_encoding_to_char(d.encoding) as encoding,\n       d.datcollate, d.datctype,\n       t.spcname as tablespace\nFROM pg_catalog.pg_database d JOIN pg_catalog.pg_tablespace t on d.dattablespace = t.oid JOIN pg_stat_database psd on d.oid = psd.datid\nWHERE d.datname = '$datname'\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT unnest(datacl) AS name FROM pg_database WHERE datname = '$datname';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT json_object_agg(kind, count) AS data\n         FROM (SELECT relkind::TEXT AS kind, count(*) AS count FROM pg_class GROUP BY relkind) d\n     ) j;"
    }
   ]
  },
  { "title": "Schema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Schemas",
   "type": "table",
   "description": "Schemas of current database ${datname}",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n       relnamespace AS \"OID\", nspname AS \"Schema\", nspowner::RegRole::TEXT AS \"Owner\",\n       coalesce((data ->> 'r')::INTEGER, 0) AS \"r\",\n       coalesce((data ->> 'i')::INTEGER, 0) AS \"i\",\n       coalesce((data ->> 'S')::INTEGER, 0) AS \"S\",\n       coalesce((data ->> 't')::INTEGER, 0) AS \"t\",\n       coalesce((data ->> 'v')::INTEGER, 0) AS \"v\",\n       coalesce((data ->> 'm')::INTEGER, 0) AS \"m\",\n       coalesce((data ->> 'c')::INTEGER, 0) AS \"c\",\n       coalesce((data ->> 'f')::INTEGER, 0) AS \"f\",\n       coalesce((data ->> 'p')::INTEGER, 0) AS \"p\",\n       coalesce((data ->> 'I')::INTEGER, 0) AS \"I\"\nFROM (\n         SELECT relnamespace, json_object_agg(kind, count) AS data\n         FROM (SELECT relnamespace, relkind::TEXT AS kind, count(*) AS count FROM pg_class GROUP BY relnamespace,relkind) d\n         GROUP BY relnamespace\n     ) j LEFT JOIN pg_namespace nsp ON j.relnamespace = nsp.oid\nWHERE nspname NOT IN ('pg_toast', 'information_schema', 'pg_catalog');"
    }
   ]
  },
  { "title": "Extension", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Installed Extensions",
   "type": "table",
   "description": "Installed Extension in the Database",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "SELECT * FROM pg_class;",
     "rawSql": "SELECT e.extname , e.extversion, n.nspname, c.description\nFROM pg_catalog.pg_extension e LEFT JOIN pg_catalog.pg_namespace n\nON n.oid = e.extnamespace LEFT JOIN pg_catalog.pg_description c\nON c.objoid = e.oid AND c.classoid = 'pg_catalog.pg_extension'::pg_catalog.regclass\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Available Extensions",
   "type": "table",
   "description": "Available Extensions (not yet installed) in the Database",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "SELECT * FROM pg_class;",
     "rawSql": "SELECT * FROM pg_available_extensions WHERE installed_version IS NULL ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks for ${datname}",
     "type": "table",
     "description": "Block by : Which pid are blocked by this PID ?\n\nBlock N: how many process are blocked by this process?",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "rawSql": "with recursive\n    activity as (select pg_blocking_pids(pid) blocked_by, *,\n                        extract(seconds FROM age(clock_timestamp(), xact_start)) as xact_wait,\n                        extract(seconds FROM age(clock_timestamp(),\n                            -- (select max(l.waitstart) from pg_locks l where a.pid = l.pid)    -- PG 14 and newer\n                             state_change       -- PG 13 and below\n                            )) as lock_wait\n                 from pg_stat_activity a\n                 where state is distinct from 'idle'),\n    blockers as (select array_agg(distinct c order by c) as pids\n                 from (select unnest(blocked_by)\n                       from activity) as dt(c)),\n    tree as (select activity.*,\n                    1                           as level,\n                    activity.pid                as top_blocker_pid,\n                    array [activity.pid]        as path,\n                    array [activity.pid]::int[] as all_blockers_above\n             from activity, blockers\n             where array [pid] <@ blockers.pids and blocked_by = '{}'::int[]\n             union all\n             select activity.*,\n                    tree.level + 1 as level,\n                    tree.top_blocker_pid,\n                    path || array [activity.pid] as path,\n                    tree.all_blockers_above || array_agg(activity.pid) over () as all_blockers_above\n             from activity,\n                  tree\n             where not array [activity.pid] <@ tree.all_blockers_above\n               and activity.blocked_by <> '{}'::int[]\n               and activity.blocked_by <@ tree.all_blockers_above)\nselect pid,\n       blocked_by,\n       case when wait_event_type = 'Lock' then 'waiting' else state end                                      as state,\n       wait_event_type,\n       wait_event,\n       xact_wait,\n       lock_wait,\n       age(backend_xid) AS xid_age,\n       -- 2147483647 - age(backend_xmin) as xmin_ttf,\n       datname, usename, level - 1 AS level,\n       (select count(distinct t1.pid) from tree t1 where array [tree.pid] <@ t1.path and t1.pid <> tree.pid) as blkd,\n       format('%s %s%s', lpad('[' || pid::text || ']', 9, ' '), repeat('.', level - 1) || case when level > 1 then ' ' end, left(query, 1000) ) as query\nfrom tree\nWHERE datname = CURRENT_DATABASE()\norder by top_blocker_pid, level, pid;"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "rawSql": "SELECT pg_blocking_pids(pid) AS blocking_pids,\n       datid,\n       datname,\n       pid,\n       leader_pid,\n       usesysid,\n       usename,\n       application_name,\n       client_addr,\n       client_hostname,\n       client_port,\n       extract(epoch from now() - backend_start) AS conn_time,\n       extract(epoch from now() - xact_start)    AS xact_time,\n       extract(epoch from now() - query_start)   AS query_time,\n       extract(epoch from now() - state_change)  AS state_time,\n       wait_event_type,\n       wait_event,\n       state,\n       backend_xid,\n       backend_xmin,\n       query_id,\n       query,\n       backend_type,\n       query_id::TEXT AS qid -- 14 has query_id, comment this for PG 13 and below \nFROM pg_stat_activity;"
      }
     ]
    }
   ]
  },
  {
   "title": "Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tables",
     "type": "table",
     "description": "Tables of current database ${datname}",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "SELECT * FROM pg_class;",
       "rawSql": "SELECT c.oid,\n       n.nspname,\n       n.nspname || '.' || c.relname                        AS name,\n       CASE WHEN relispartition THEN 'P' ELSE c.relkind END AS kind,\n       age(c.relfrozenxid)::FLOAT / 2147483648              AS relage,\n       (n_tup_ins + n_tup_upd + n_tup_del)                  AS n_tup_mod,\n       seq_scan + idx_scan                                  AS tbl_scan,\n       seq_tup_read + idx_tup_fetch                         AS tup_read,\n       reltuples,\n       relpages,\n       relfilenode,\n       pg_table_size(c.oid)                                 AS size,\n       relnatts,\n       s.seq_scan,\n       s.seq_tup_read,\n       s.idx_scan,\n       s.idx_tup_fetch,\n       s.n_tup_ins,\n       s.n_tup_upd,\n       s.n_tup_del,\n       s.n_tup_hot_upd,\n       -- s.n_tup_newpage_upd, -- PG16\n       s.n_live_tup,\n       s.n_dead_tup,\n       s.n_mod_since_analyze,\n       -- s.n_ins_since_vacuum, -- PG13\n       extract(EPOCH FROM s.last_vacuum) * 1000             AS last_vacuum,\n       extract(EPOCH FROM s.last_autovacuum) * 1000         AS last_autovacuum,\n       extract(EPOCH FROM s.last_analyze) * 1000            AS last_analyze,\n       extract(EPOCH FROM s.last_autoanalyze) * 1000        AS last_autoanalyze,\n       s.vacuum_count,\n       s.autovacuum_count,\n       s.analyze_count,\n       s.autoanalyze_count\nFROM pg_catalog.pg_class c\n         LEFT JOIN pg_namespace n ON n.oid = c.relnamespace\n         LEFT JOIN pg_stat_user_tables s ON c.oid = s.relid\nWHERE c.relkind IN ('r', 'p', '')\nAND schemaname !~ '^pg_' AND schemaname !~ '^_' AND schemaname !~ '^timescaledb' AND schemaname !~ '^citus' AND schemaname !~ '^columnar' \nAND schemaname NOT IN ('pg_catalog','information_schema')\nORDER BY c.oid, n.nspname;"
      }
     ]
    }
   ]
  },
  {
   "title": "Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexes",
     "type": "table",
     "description": "Read = Returned Rows\n\nFetch = Scanned Rows",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "rawSql": "SELECT schemaname || '.' || indexrelname AS \"Index\", \n       schemaname || '.' || relname AS \"Table\", \n       *,\n       pg_get_indexdef(indexrelid) AS def\nFROM pg_stat_user_indexes\nWHERE schemaname !~ '^pg_' AND schemaname !~ '^_' AND schemaname !~ '^timescaledb' AND schemaname !~ '^citus' AND schemaname !~ '^columnar' \nAND schemaname NOT IN ('pg_catalog','information_schema');"
      }
     ]
    }
   ]
  },
  {
   "title": "Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Bloat",
     "type": "table",
     "description": "Bloat ratio & wasted bytes estimation of all heap tables",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_table_bloat;"
      }
     ]
    },
    {
     "title": "Table Wasted Bytes",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_table_bloat;"
      }
     ]
    },
    {
     "title": "Index Bloat",
     "type": "table",
     "description": "Bloat ratio & wasted bytes estimation of all btree indexes",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_index_bloat;"
      }
     ]
    },
    {
     "title": "Index Wasted Bytes",
     "type": "marcusolsson-treemap-panel",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "rawSql": "SELECT *, size * ratio AS waste FROM monitor.pg_index_bloat;"
      }
     ]
    }
   ]
  },
  {
   "title": "Sequence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "rawSql": "SELECT schemaname || '.' || sequencename AS \"Sequence\", *\nFROM pg_sequences;\n-- WHERE schemaname !~ '^pg_' AND schemaname !~ '^_' AND schemaname !~ '^timescaledb' AND schemaname !~ '^citus' AND schemaname !~ '^columnar' \n-- AND schemaname NOT IN ('pg_catalog','information_schema');"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname'\nORDER BY total_exec_time DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL by Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by Calls",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 48 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND calls > 0\nORDER BY calls DESC\nLIMIT 100;"
      }
     ]
    },
    {
     "title": "SQL by Calls",
     "type": "marcusolsson-treemap-panel",
     "description": "Colored by RT",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.calls AS value, s.mean_exec_time AS rt\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND calls > 0\nORDER BY calls DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL by Rows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by Rows",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 49 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND rows > 0\nORDER BY rows DESC\nLIMIT 100;"
      }
     ]
    },
    {
     "title": "SQL by Rows",
     "type": "marcusolsson-treemap-panel",
     "description": "Colored by RT",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.rows AS value, s.mean_exec_time AS rt\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND rows > 0\nORDER BY calls DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL by Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by Time",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 50 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND total_exec_time > 0\nORDER BY total_exec_time DESC\nLIMIT 100;"
      }
     ]
    },
    {
     "title": "SQL by Time",
     "type": "marcusolsson-treemap-panel",
     "description": "Colored by RT",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.total_exec_time AS value, s.mean_exec_time AS rt\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND total_exec_time > 0\nORDER BY total_exec_time DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL by WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by WAL",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 15, "x": 0, "y": 51 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND wal_bytes > 0\nORDER BY wal_bytes DESC\nLIMIT 100;"
      }
     ]
    },
    {
     "title": "SQL by WAL",
     "type": "marcusolsson-treemap-panel",
     "description": "Colored by RT",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.wal_bytes AS value, s.mean_exec_time AS rt\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND wal_bytes > 0\nORDER BY wal_bytes DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL by Dupe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL by Duplication",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE queryid IN (SELECT queryid FROM pg_stat_statements GROUP BY queryid HAVING count(*) > 1)\nLIMIT 100;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Logical Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Slots (Logical)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "rawSql": "SELECT *, \nCASE WHEN pg_is_in_recovery() THEN pg_last_wal_replay_lsn() ELSE pg_current_wal_lsn() END - restart_lsn AS retain \nFROM pg_replication_slots \nWHERE slot_type = 'logical';"
      }
     ]
    },
    {
     "title": "Subscription",
     "type": "stat",
     "description": "The pg_stat_wal_receiver view will contain only one row, showing statistics about the WAL receiver from that receiver's connected server.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_subscription;"
      }
     ]
    },
    {
     "title": "Publication",
     "type": "stat",
     "description": "Publication Information",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "rawSql": "SELECT * FROM pg_publication;" }
     ]
    }
   ]
  }
 ]
}