{
 "title": "PGRDS Cluster",
 "description": "PostgreSQL Monitoring for Remote RDS instances (with limited metrics)",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster",
  "PGRDS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up,cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Leader",
        "type": "string",
        "values": [ "$primary" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (pg_up{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:active_time_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg_uptime{cls=\"$cls\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (address) (label_join(pg_meta_info{ins=\"$primary\"}, \"address\", \":\", \"ip\", \"listen_port\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$primary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "Database of this cluster ${cls}\n\nLoad: active_time, 1 = 100% 1 core usage \n\nConn% : conn usage of instance/database limit\n\nBackend: Postgres num backends\n\nT = is Template?",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cls=\"$cls\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg_db_age{cls=\"$cls\"}) / 2147483647",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cls=\"$cls\"})",
     "legendFormat": "Load"
    },
    {
     "expr": "max by (datname) (pg_db_datid{cls=\"$cls\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cls}",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(pg_in_recovery{cls=\"$cls\"} == 0) * 0 + 1",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:xact_commit_rate1m{cls=\"$cls\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:xact_rollback_rate1m{cls=\"$cls\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:active_time_rate1m{cls=\"$cls\"} / pg:cls:xact_total_rate1m{cls=\"$cls\"}",
     "legendFormat": "RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "Conn%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:active_backends{cls=\"$cls\"}",
     "legendFormat": "Active Conn"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:ixact_backends{cls=\"$cls\"})",
     "legendFormat": "iXact Conn"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:tup_fetched_rate1m{cls=\"$cls\"}",
     "legendFormat": "Row Fetch"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:tup_modified_rate1m{cls=\"$cls\"}",
     "legendFormat": "Row Change"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_db_age{cls=\"$cls\"}) / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:lag_bytes{cls=\"$cls\"}",
     "legendFormat": "Lag (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:lag_seconds{cls=\"$cls\"}",
     "legendFormat": "Lag (s)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Load, 1 = 100% one cpu core usage.\nCalculated by session active time (PG14+)",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:active_time_rate1m{cls=\"$cls\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Load for Cluster Instances in Last 5 minutes",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:active_time_rate5m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "pg:ins:active_time_rate5m{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{cls=\"$cls\", alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}} @ {{ ins }}"
    },
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}} @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Transaction Commits / Rollbacks (rate5m)",
   "type": "timeseries",
   "description": "Transaction Committed & Rollback rate in last 5 minutes on this PostgreSQL Cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cls:xact_commit_rate5m{cls=\"$cls\"}",
     "legendFormat": "Commits"
    },
    {
     "expr": "pg:cls:xact_rollback_rate5m{cls=\"$cls\"}",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Transaction RT (1m)",
   "type": "timeseries",
   "description": "Transaction average response time in last minute.\nCalculated by db_active_time / tps. At cluster level / per instance level. Only available on PG14+",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:cls:active_time_rate1m{cls=\"$cls\"} / pg:cls:xact_total_rate1m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pg:ins:active_time_rate1m{cls=\"$cls\"} / pg:ins:xact_total_rate15m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "TPS by Instance (rate1m)",
   "type": "timeseries",
   "description": "Transaction Committed rate in last 1 minute, group on instance level",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xact_commit_rate1m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "pg:ins:xact_commit_rate1m{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Postgres Load (rate1m)",
   "type": "timeseries",
   "description": "Load 1 = 100% one cpu core usage.\nCalculated by session active time (PG14+)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:active_time_rate1m{cls=\"$cls\", datname!~'template\\\\d'}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Row Fetched (rate1m)",
   "type": "timeseries",
   "description": "Tuples fetched from databases",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (ins) (rate(pg_db_tup_fetched{cls=\"$cls\", ins=\"$primary\"}[1m]))",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "sum by (ins) (rate(pg_db_tup_fetched{cls=\"$cls\", ins!=\"$primary\"}[1m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Row Modified (rate1m)",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_inserted{ins=\"$primary\"}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{ins=\"$primary\"}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{ins=\"$primary\"}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "Locks by Category",
   "type": "timeseries",
   "description": "Cluster lock count by 3 categories:\nRead locks, Write Locks, and exclusive locks.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg:ins:xlock_count{cls=\"$cls\"})",
     "legendFormat": "Exclusive"
    },
    {
     "expr": "sum(pg:ins:wlock_count{cls=\"$cls\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(pg:ins:rlock_count{cls=\"$cls\"})",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{cls=\"$cls\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Long Lived Xact",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_tx_duration{cls=\"$cls\", state!~\"(idle.*|disabled)\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_timeline_id{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Replication Status among cluster ${cls}",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "pg:cls:sender{cls=\"$cls\"}"
    },
    {
     "expr": "pg:cls:receiver{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Replication Lag Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag Time (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_repl_replay_lag{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "LSN Progress (rate1m)",
   "type": "timeseries",
   "description": "Rate of lsn in last minute",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg:ins:lsn_rate1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Age Usage",
   "type": "timeseries",
   "description": "XID Usage of each instance in this cluster.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (datname) (pg:db:age{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Replication LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "max(pg_repl_lsn{cls=\"$cls\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "pg_repl_replay_lsn{cls=\"$cls\"}",
     "legendFormat": "replay @ {{ appname }}"
    },
    {
     "expr": "pg_repl_flush_lsn{cls=\"$cls\"}",
     "legendFormat": "flush @ {{ appname }}"
    },
    {
     "expr": "pg_repl_write_lsn{cls=\"$cls\"}",
     "legendFormat": "write @ {{ appname }}"
    },
    {
     "expr": "pg_slot_restart_lsn{cls=\"$cls\"}",
     "legendFormat": "slot restart @ {{ slot_name }}"
    }
   ]
  },
  {
   "title": "XID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmax{ins=\"$primary\"}",
     "legendFormat": "xmax"
    },
    {
     "expr": "pg_xact_xmin{ins=\"$primary\"}",
     "legendFormat": "xmin"
    },
    {
     "expr": "pg_db_frozen_xid{ins=\"$primary\"}",
     "legendFormat": "frozen {{ datname }}"
    },
    {
     "expr": "pg_checkpoint_oldest_active_xid{ins=\"$primary\"}",
     "legendFormat": "ckpt oldest active xid"
    },
    {
     "expr": "pg_checkpoint_oldest_xid{ins=\"$primary\"}",
     "legendFormat": "ckpt oldest xid"
    },
    {
     "expr": "pg_checkpoint_next_xid{ins=\"$primary\"}",
     "legendFormat": "ckpt next xid"
    },
    {
     "expr": "pg_checkpoint_newest_commit_ts_xid{ins=\"$primary\"}",
     "legendFormat": "ckpt newest cmt ts xid"
    }
   ]
  },
  {
   "title": "Slot Retained Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} reserved for {{ slot_name }}"
    }
   ]
  },
  {
   "title": "Replication Slots",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "max by (ins, slot_name, datname) (pg_slot_retained_bytes{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_active{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_temporary{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_wal_status{cls=\"$cls\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_restart_lsn{cls=\"$cls\"})"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:ins:conn_usage{cls=\"$cls\", datname!~'template\\\\d'}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Idle in Transaction Backends",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\", state=~\"idle in.*\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Backends",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "New Sessions (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum by (ins) (increase(pg_db_sessions{cls=\"$cls\", datname!~'template\\\\d'}[1m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Backends by State",
   "type": "timeseries",
   "description": "Group by pg_stat_activity.state on cluster level",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Backends by Type",
   "type": "timeseries",
   "description": "Group by pg_stat_activity.backend_type on cluster level",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum by (type) (pg_backend_count{cls=\"$cls\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Max Conn Lifespan",
   "type": "timeseries",
   "description": "max by pg_stat_activity connection duration on cluster level",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_conn_duration{cls=\"$cls\", state!=\"idle|disabled\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Backends by Wait Event Type",
   "type": "timeseries",
   "description": "Group by pg_stat_activity.wait_event_type on cluster level",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "sum by (event) (pg_wait_count{cls=\"$cls\"})",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Active% (of Session Time)",
   "type": "timeseries",
   "description": "Time spent executing SQL statements on each instance",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (ins) (rate(pg_db_active_time{cls=\"$cls\"}[1m]))\n/ sum by (ins) (rate(pg_db_session_time{cls=\"$cls\"}[1m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Session Failures in 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum by (ins) (increase(pg_db_sessions_abandoned{cls=\"$cls\"}[1m]))",
     "legendFormat": "[Abandoned] : {{ ins }}"
    },
    {
     "expr": "sum by (ins) (increase(pg_db_sessions_fatal{cls=\"$cls\"}[1m]))",
     "legendFormat": "[Fatal] : {{ ins }}"
    },
    {
     "expr": "sum by (ins) (increase(pg_db_sessions_killed{cls=\"$cls\"}[1m]))",
     "legendFormat": "[Killed] : {{ ins }}"
    }
   ]
  },
  { "title": "Persist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Database Cluster Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg_size_bytes{cls=\"$cls\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Database WAL/Log Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg_size_bytes{cls=\"$cls\", datname=~\"(log|wal)\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Checkpoint Scheduled / Requested in 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "increase(pg_checkpointer_timed{ins=\"$primary\"}[1h])",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "increase(pg_checkpointer_req{ins=\"$primary\"}[1h])",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Checkpoint Time : Sync/Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_checkpointer_sync_time{ins=\"$primary\"}[1m])",
     "legendFormat": "Sync"
    },
    {
     "expr": "- rate(pg_checkpointer_write_time{ins=\"$primary\"}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "BGWriter Buffer Flush",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_buffers_clean{ins=\"$primary\"}[1m]) * 8192",
     "legendFormat": "Clean"
    },
    {
     "expr": "(rate(pg_checkpointer_buffers_written{ins=\"$primary\"}[1m]) or rate(pg_bgwriter_buffers_checkpoint{ins=\"$primary\"}[1m])) * 8192",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "rate(pg_bgwriter_buffers_backend{ins=\"$primary\"}[1m]) * 8192",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "BGWriter Buffer Alloc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pg_bgwriter_buffers_alloc{ins=\"$primary\"}[1m]) * 8192",
     "legendFormat": "Alloc"
    }
   ]
  },
  {
   "title": "Blocks Access 1m",
   "type": "timeseries",
   "description": "Database 4k blocks access",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:db:blks_access_1m{cls=\"$cls\"}) * 4096",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Blocks Hit Ratio (1m)",
   "type": "timeseries",
   "description": "Database 4k blocks hit ratio in last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:ins:blks_hit_ratio1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Blocks Read 1m",
   "type": "timeseries",
   "description": "Database 4k blocks access",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:db:blks_read_1m{cls=\"$cls\"}) * 4096",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Blocks Read/Write Time Spent Rate1m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:db:blk_read_time_seconds_rate1m{cls=\"$cls\"})",
     "legendFormat": "▲ {{ ins }}"
    },
    {
     "expr": "- sum by (ins) (pg:db:blk_write_time_seconds_rate1m{cls=\"$cls\"})",
     "legendFormat": "▼ {{ ins }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "Database Size",
   "type": "timeseries",
   "description": "Database size on cluster primary",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_size_bytes{ins=\"$primary\", datname!~'wal|log|template\\\\d'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Database Size Delta 10m",
   "type": "timeseries",
   "description": "Database Size Change on Cluster Primary in Last 10 minutes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "delta(pg_size_bytes{ins=\"$primary\", datname!~'wal|log|template\\\\d'}[10m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "TPS by Database (rate1m)",
   "type": "timeseries",
   "description": "Database Transaction Commit Rate in last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session by Database",
   "type": "timeseries",
   "description": "Active processs for each database in this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Database Blocks Hit Ratio (1m)",
   "type": "timeseries",
   "description": "Database 4k blocks hit ratio in last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Idle in Transaction Backends",
   "type": "timeseries",
   "description": "number of dangerous idle in transaction backend in different database amoung this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 166 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\", state=~\"idle in.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "timeseries",
   "description": "Connection used ratio of min(\n  max_connections @ instance level,\n  connlimit @ database level\n)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{cls=\"$cls\", datname!~'template\\\\d'}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "New Sessions (increase1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 172 },
   "targets": [
    {
     "expr": "increase(pg_db_sessions{cls=\"$cls\", datname!~'template\\\\d'}[1m])",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Row Fetched",
   "type": "timeseries",
   "description": "Tuples fetched from databases among this cluster",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_tup_fetched{cls=\"$cls\"}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Row Modified",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster group by database",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_inserted{ins=\"$primary\", datname!~'rdsadmin|polardb_admin|template\\\\d'}[1m])) by (datname)",
     "legendFormat": "INSERT.{{ datname }}"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{ins=\"$primary\", datname!~'rdsadmin|polardb_admin|template\\\\d'}[1m])) by (datname)",
     "legendFormat": "UPDATE.{{ datname }}"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{ins=\"$primary\", datname!~'rdsadmin|polardb_admin|template\\\\d'}[1m])) by (datname)",
     "legendFormat": "DELETE.{{ datname }}"
    }
   ]
  },
  { "title": "Table & Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "Table Scan (scan/s)",
   "type": "timeseries",
   "description": "Index Scan + Seq Scan on this table per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname,relname) (\n    pg:table:scan_rate1m{cls=\"$cls\"}\n)",
     "legendFormat": "{{ datname }}.{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple Read (rows/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname,relname)  (\n    rate(pg_table_tup_read{cls=\"$cls\"}[1m])\n)",
     "legendFormat": "{{ datname }}.{{ relname }}"
    }
   ]
  },
  {
   "title": "Query Call",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}.{{ datname }}.{{ query }}"
    }
   ]
  },
  {
   "title": "Query Time",
   "type": "timeseries",
   "description": "Top Query Time Spent among this cluster",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}.{{ datname }}.{{ query }}"
    }
   ]
  }
 ]
}