{
 "title": "PGSQL Alert",
 "description": "PGSQL Alerts and global metrics overview",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Overview",
  "Alert"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"pgsql\"}) or on() vector(0)",
     "legendFormat": "Firing"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", job=\"pgsql\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"pgsql\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\", job=\"pgsql\"})",
     "legendFormat": "[{{ severity }}] {{alertname}} @ {{ cls }}"
    }
   ]
  },
  { "title": "PGSQL Dashboards", "type": "dashlist", "gridPos": { "h": 16, "w": 5, "x": 19, "y": 1 } },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{job=\"pgsql\"}"
    }
   ]
  },
  {
   "title": "PostgresPressureHigh",
   "type": "timeseries",
   "description": "Postgres & Pgbouncer load index: Active Time / Available Time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "ins:pressure1", "legendFormat": "{{ ins }}" }
   ]
  },
  { "title": "Error Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "PostgreSQL Error Logs",
   "type": "logs",
   "description": "PostgreSQL Error logs (code != 00000)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "job:\"postgres\" lv:in('ERROR','FATAL','PANIC') | fields level, ins, _msg"
    }
   ]
  },
  {
   "title": "PGSQL : Liveness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgresDown",
     "type": "timeseries",
     "description": "Postgres Database Service Aliveness",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      { "expr": "pg_up", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "PgbouncerDown",
     "type": "timeseries",
     "description": "Pgbouncer Connection Pooler Aliveness",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      { "expr": "pg_up", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "PatroniDown",
     "type": "timeseries",
     "description": "Patroni Aliveness",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      { "expr": "patroni_up", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "ExporterDown",
     "type": "timeseries",
     "description": "PG/PGB Exporter Aliveness",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      { "expr": "pg_exporter_agent_up", "legendFormat": "{{ ins }}" },
      { "expr": "pgbouncer_exporter_agent_up", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgresPartition",
     "type": "timeseries",
     "description": "Number of leader of a postgres partition",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "pg:cls:partition", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "PostgresReplicationBreak",
     "type": "timeseries",
     "description": "Number of replication streaming slave change",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "changes(pg_downstream_count{state=\"streaming\"}[5m])",
       "legendFormat": "{{ cls }}"
      }
     ]
    },
    {
     "title": "PostgresReplicationLag",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "pg:ins:lag_bytes", "legendFormat": "{{ ins }}" }
     ]
    },
    {
     "title": "PostgresReplicationLagSeconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "pg:ins:lag_seconds", "legendFormat": "{{ ins }}" }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgresWalRateHigh",
     "type": "timeseries",
     "description": "Transaction Rollback",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "pg:cls:lsn_rate1m", "legendFormat": "{{ cls }}" }
     ]
    },
    {
     "title": "PgbouncerQuerySlow",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "pgbouncer:db:query_rt_1m", "legendFormat": "{{ ins }}:{{ datname }}" }
     ]
    },
    {
     "title": "PostgresTpsHigh",
     "type": "timeseries",
     "description": "Transactions in database",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg:db:xact_total_rate1m{datname!~\"template0|template1\"}",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    },
    {
     "title": "PostgresRollbackHigh",
     "type": "timeseries",
     "description": "Transaction Rollback",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg:db:xact_rollback_rate1m{datname!~\"template0|template1\"}",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "PgbouncerClientQueue",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "pgbouncer:db:waiting_clients", "legendFormat": "{{ ins }}:{{ datname }}" }
     ]
    },
    {
     "title": "PostgresConnUsageHigh",
     "type": "timeseries",
     "description": "Database connection Usage",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg:db:conn_usage{datname!~\"template0|template1\"}",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    },
    {
     "title": "PostgresBackendNumHigh",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg:db:num_backends{datname!~'template\\\\d'}",
       "legendFormat": "{{ ins }}:{{ datname }}"
      }
     ]
    },
    {
     "title": "PostgresIdleInXact",
     "type": "timeseries",
     "description": "Idle in Transaction",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg:db:ixact_backends{datname!~\"template0|template1\"}",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL : Persist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgresXidWarpAround",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (ins, datname) (pg:db:age{datname!~\"template0|template1\"})",
       "legendFormat": "{{ ins }}.{{ datname }}"
      }
     ]
    }
   ]
  }
 ]
}