{
 "title": "PGSQL Cluster",
 "description": "PostgreSQL Cluster Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   },
   {
    "name": "node_cls",
    "label": "Node Cluster",
    "query": {
     "query": "label_values(node_load1{ip=~\"$members\"},cls)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$primary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins,instance) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "max by (datname) (pg_db_datid{cls=\"$cls\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_up{cls=\"$cls\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(count by (proxy) (haproxy_server_status{proxy=~\"$cls-.*\"}))",
     "legendFormat": "Service"
    },
    {
     "expr": "count(max by (cls,datname) (pg_db_age{cls=\"$cls\"}))",
     "legendFormat": "Database"
    },
    {
     "expr": "count(group by (ins) (haproxy_backend_current_sessions{cls='$cls'}))",
     "legendFormat": "Proxy"
    },
    {
     "expr": "count(count by (ip) (pg_up{cls=\"$cls\"}))",
     "legendFormat": "Node"
    },
    {
     "expr": "sum(pg:cls:cpu_count{cls=\"$cls\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{ip=~\"$members\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node:fs:size_bytes{ip=~\"$members\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow = Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum by (cls) (pg_up{cls=\"$cls\"})",
     "legendFormat": "postgres"
    },
    {
     "expr": " sum by (cls) (pgbouncer_up{cls=\"$cls\"})",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": " sum by (cls) (patroni_up{cls=\"$cls\"})",
     "legendFormat": "patroni"
    },
    {
     "expr": " sum by (cls) (pg_exporter_agent_up{cls=\"$cls\"})",
     "legendFormat": "pg_exporter"
    },
    {
     "expr": " sum by (cls) (pgbouncer_exporter_agent_up{cls=\"$cls\"})",
     "legendFormat": "pgb_exporter"
    },
    {
     "expr": " sum by (cls) (pgbackrest_exporter_agent_up{cls=\"$cls\"})",
     "legendFormat": "pgbackrest"
    },
    {
     "expr": " sum(node_up{ip=~\"$members\"})",
     "legendFormat": "node"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ping RT",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,vip) (probe_duration_seconds{ip=~\"$members\", job=~\".*vip\"})",
     "legendFormat": "{{ vip }} @ {{ job }}"
    },
    {
     "expr": "probe_duration_seconds{ip=~\"$members\", job=\"ping\"}",
     "legendFormat": "{{ ip }} : {{ ins }}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum by (cls,proxy) (haproxy_server_status{proxy=~\"$cls-.*\", state=\"UP\"}) > bool 0",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "description": "Instances among this cluster and their saturation (postgres or pgbouncer)",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:ins:load1{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "stat",
   "description": "Node of this cluster and their cpu usage.",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ip=~\"$members\"}",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "stat",
   "description": "Proxy backend session number among this cluster",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_backend_current_sessions{proxy=~'$cls.*'})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Component",
   "type": "stat",
   "description": "Load of different compoents.",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:load1{cls=\"$cls\"}",
     "legendFormat": "Postgres"
    },
    {
     "expr": "pgbouncer:cls:load1{cls=\"$cls\"}",
     "legendFormat": "Pgbouncer"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{cls=\"$cls\"}[1m]))",
     "legendFormat": "Exporter"
    },
    {
     "expr": "avg by (cls) (haproxy:ins:usage{ip=~\"$members\"})",
     "legendFormat": "Haproxy"
    },
    {
     "expr": "pg:cls:cpu_usage{cls=\"$cls\"}",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "title": "Service",
   "type": "stat",
   "description": "Registered service among this cluster.\n\nClick goes to PGSQL Service Dashboard",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "c" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (proxy) (haproxy_backend_current_sessions{proxy=~'$cls-.*'}))",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "TPS of each database",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_xact_total{cls=\"$cls\", datname!~'template\\\\d'}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_commit{cls=\"$cls\"}[1m]))\n# pg:cls:xact_commit_rate1m{cls=\"$cls\"}",
     "legendFormat": "Commit"
    },
    {
     "expr": "sum(rate(pg_db_xact_rollback{cls=\"$cls\"}[1m]))\n# pg:cls:xact_commit_rate1m{cls=\"$cls\"}",
     "legendFormat": "Rollback"
    },
    {
     "expr": "sum(rate(pgbouncer_stat_total_xact_count{cls=\"$cls\"}[1m])) \n# pgbouncer:cls:xact_rate1m{cls=\"$cls\"} ",
     "legendFormat": "TPS"
    },
    {
     "expr": "sum(rate(pgbouncer_stat_total_query_count{cls=\"$cls\"}[1m])) \n# pgbouncer:cls:query_rate1m{cls=\"$cls\"} ",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pgbouncer_pool_waiting_clients{cls=\"$cls\"})\n# pgbouncer:cls:waiting_clients{cls=\"$cls\"}",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stat_total_query_time{cls=\"$cls\"}[1m])) / sum(rate(pgbouncer_stat_total_query_count{cls=\"$cls\"}[1m]))\n# pgbouncer:cls:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "Cluster RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stat_total_query_time{cls=\"$cls\", ins=\"$primary\"}[1m])) / sum(rate(pgbouncer_stat_total_query_count{cls=\"$cls\", ins=\"$primary\"}[1m]))\n# pgbouncer:ins:query_rt_1m{ins=\"$primary\"}",
     "legendFormat": "Primary RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_repl_replay_lag{cls=\"$cls\", appname!~'walreceiver|pg_receivewal'})\n# pg:cls:lag_seconds{cls=\"$cls\"}",
     "legendFormat": "Lag (s)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_repl_replay_diff{cls=\"$cls\", appname!~'walreceiver|pg_receivewal'})\n# pg:cls:lag_bytes{cls=\"$cls\"}",
     "legendFormat": "Lag (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (cls) (pg_db_age{cls=\"$cls\", datname!~\"template[0-9]\"})  / 2147483647\n# pg:cls:age{cls=\"$cls\"} / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{ip=~\"$members\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cls:load1{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:ins:load1{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "pg:ins:load1{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}} @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Leadership", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:cls:leader{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cls}",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(pg_in_recovery{cls=\"$cls\"} == 0) * 0 + 1",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_timeline_id{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Traffic Routes (primary service instance)",
   "type": "timeseries",
   "description": "Haproxy will route $cls-primary traffic to which instance ?",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{proxy=\"$cls-primary\"})",
     "legendFormat": "$cls-primary ➔ {{ server }}"
    }
   ]
  },
  { "title": "Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "table",
   "description": "All nodes among cluster ${cls}",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "node_up{ip=~\"$members\"}"
    },
    {
     "expr": "group without(ins,cls,instance) (node_uname_info{ip=~\"$members\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_usage{ip=~\"$members\"})"
    },
    {
     "expr": "max by (ip) (node:ins:mem_usage{ip=~\"$members\"})"
    },
    {
     "expr": "sum by (ip,instance) (node:ins:space_usage_max{ip=~\"$members\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_count{ip=~\"$members\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{ip=~\"$members\"}) / 1073741824"
    },
    {
     "expr": "sum(node:fs:size_bytes{ip=~\"$members\"}) by (ip) / 1073741824"
    },
    {
     "expr": "count by (ip) (up{ip=~\"$members\"})"
    },
    {
     "expr": "max by (ip) (probe_duration_seconds{ip=~\"$members\", job=\"ping\"})"
    },
    {
     "expr": "sum by (ip) (haproxy_backend_current_sessions{ip=~\"$members\"})"
    },
    {
     "expr": "min by (ip) (node_up{ip=~\"$members\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow = Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ip=~\"$members\"}",
     "legendFormat": "postgres {{ ins }}"
    },
    {
     "expr": "pgbouncer_up{ip=~\"$members\"}",
     "legendFormat": "pgbouncer {{ ins }}"
    },
    {
     "expr": "patroni_up{ip=~\"$members\"}",
     "legendFormat": "patroni {{ ins }}"
    },
    {
     "expr": "pg_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pg_exporter {{ ins }}"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pgb_exporter {{ ins }}"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pgbackrest {{ ins }}"
    },
    {
     "expr": "node_up{ip=~\"$members\"}",
     "legendFormat": "node {{ ins }}"
    },
    {
     "expr": "haproxy_up{ip=~\"$members\"}",
     "legendFormat": "haproxy {{ ins }}"
    },
    {
     "expr": "docker_up{ip=~\"$members\"}",
     "legendFormat": "docker {{ ins }}"
    },
    {
     "expr": "vector_up{ip=~\"$members\"}",
     "legendFormat": "vector {{ ins }}"
    },
    {
     "expr": "max by (ins) (up{job=\"juice\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"nginx\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"grafana\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmetrics\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vlogs\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vtraces\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmalert\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"alertmanager\", ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "etcd_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "redis_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "minio_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mysql_up{ip=~\"$members\"}",
     "legendFormat": "mysql {{ ins }}"
    },
    {
     "expr": "mysql_exporter_up{ip=~\"$members\"}",
     "legendFormat": "mysql_exporter"
    }
   ]
  },
  {
   "title": "Patroni Members",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "max by (ins) (patroni_primary{cls=\"$cls\"}) + \nmax by (ins) (patroni_standby_leader{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cls,ins,scope) (patroni_version{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_server_version{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_is_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_cluster_unlocked{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_pending_restart{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_failsafe_mode_is_active{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_xlog_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_running{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_dcs_last_seen{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_postmaster_start_time{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_up{cls=\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Instances",
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "pg_in_recovery{cls=\"$cls\"}"
    },
    {
     "expr": "min by (ins,ip) (up{cls=\"$cls\", job=\"pgsql\"})"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\"}"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:xact_rt_1m{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:conn_usage{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pgbouncer:ins:query_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pgbouncer:ins:waiting_clients{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:lag_bytes{cls=\"$cls\", ins=~'$cls.*'})"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "table",
   "description": "Important configuration entries of this instance",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$primary\"}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "table",
   "description": "Database of this cluster ${cls}\n\nLoad: active_time / backends (PG14 only)\n\nQuery RT : max query rt of this database\n\nClient: Pgbouncer Active Clients\n\nServer: Pgbouncer Active Servers\n\nBackend: Postgres num backends\n\nT = is Template?\n\nD = Disabled in Pgbouncer ?\n\nP = Paused in Pgbouncer ?",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cls=\"$cls\", datname!~\"wal|log\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "max by (datname) (pg:db:age{cls=\"$cls\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:query_rt_1m{ins=\"$primary\"})",
     "legendFormat": "RT"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_disabled{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_paused{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cls=\"$cls\"}) / sum by (datname) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Load"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_clients{cls=\"$cls\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cls=\"$cls\"})",
     "legendFormat": "Server"
    },
    {
     "expr": "max by (datname,host) (pgbouncer_database_pool_size{cls=\"$cls\", datname!=\"pgbouncer\"} + pgbouncer_database_reserve_pool{cls=\"$cls\", datname!=\"pgbouncer\"})",
     "legendFormat": "PoolSize"
    },
    {
     "expr": "max by (datname) (pg_db_datid{cls=\"$cls\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "title": "Service",
   "type": "table",
   "description": "Service map tells whether a server can be used as a specific service/role/svc.\ne.g Offline marks this server can be used as offline server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "max by (proxy,server) (\n    haproxy_server_current_sessions{proxy=~\"$cls.*\"}\n)"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "table",
   "description": "All haproxy among this cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "count by (ins,instance) (haproxy_backend_current_sessions{proxy=~\"$cls-.*\"})",
     "legendFormat": "Service"
    },
    {
     "expr": "count by(ins) (group by(ins,server) (haproxy_server_current_sessions{proxy=~\"$cls-.*\"}))",
     "legendFormat": "Session"
    },
    {
     "expr": "sum by (ins) (haproxy_backend_current_sessions{proxy=~\"$cls-.*\"})",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "table",
   "description": "Replication Status among cluster ${cls}",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "pg:cls:sender{cls=\"$cls\"}"
    },
    {
     "expr": "pg:cls:receiver{cls=\"$cls\"}"
    }
   ]
  },
  { "title": "Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Cluster (5m) & Instance (1m) CPU Usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cls:cpu_usage_5m{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:ins:cpu_usage_1m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "pg:ins:cpu_usage_1m{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Xacts (5m)",
   "type": "timeseries",
   "description": "Total transactions (commit + rollback) per second from PostgreSQL in last 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_total{cls=\"$cls\"}[5m])) \n# pg:cls:xact_commit_rate1m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "sum by (ins) (rate(pg_db_xact_total{cls=\"$cls\", ins=\"$primary\"}[5m])) \n# pg:cls:xact_commit_rate1m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "sum by (ins) (rate(pg_db_xact_total{cls=\"$cls\", ins!=\"$primary\"}[5m])) \n# pg:cls:xact_commit_rate1m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Session",
   "type": "timeseries",
   "description": "Number of backends for each instances among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "CRUD",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_fetched{cls=\"$cls\"}[1m]))",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum(rate(pg_db_tup_inserted{cls=\"$cls\"}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{cls=\"$cls\"}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{cls=\"$cls\"}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Average transaction response time from pgbouncer\n(You can get from postgres directly after PG14)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:cls:active_time_rate1m{cls=\"$cls\"} / pg:cls:xact_total_rate1m{cls=\"$cls\"} # PG14",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:ins:active_time_rate1m{cls=\"$cls\", ins=\"$primary\"} / pg:ins:xact_total_rate1m{cls=\"$cls\", ins=\"$primary\"} # PG14",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "pg:ins:active_time_rate1m{cls=\"$cls\", ins!=\"$primary\"} / pg:ins:xact_total_rate1m{cls=\"$cls\", ins!=\"$primary\"} # PG14",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "Replication Lag (WAL Replay Lag) measured in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Query Time Spent",
   "type": "timeseries",
   "description": "Time spent per second for each query of each instances.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}-{{ query }}"
    }
   ]
  },
  {
   "title": "XID Usage",
   "type": "stat",
   "description": "Ratio of XID used for each database among this cluster",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (datname) (pg_db_age{cls=\"$cls\", datname!~\"template[0-9]\"}) / 2147483647",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Disk / Network",
   "type": "timeseries",
   "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:ins:disk_read_bytes_rate1m{ip=~\"$members\"} * on(ip) group_right pg_up{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}-R▲"
    },
    {
     "expr": "node:ins:network_tx_bytes_rate1m{ip=~\"$members\"} * on(ip) group_right pg_up{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}-TX▲"
    },
    {
     "expr": "- node:ins:network_rx_bytes_rate1m{ip=~\"$members\"} * on(ip) group_right pg_up{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}-RX▼"
    },
    {
     "expr": "- node:ins:disk_write_bytes_rate1m{ip=~\"$members\"} * on(ip) group_right pg_up{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}-W▼"
    }
   ]
  },
  {
   "title": "Space Usage (Max)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node:fs:space_usage{ip=~\"$members\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Total Logs",
   "type": "stat",
   "description": "Total log events in the current time window",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ip:in(${members:doublequote}) job:postgres | stats count() as count",
     "legendFormat": "postgres"
    },
    {
     "expr": "ip:in(${members:doublequote}) job:patroni | stats count() as count",
     "legendFormat": "patroni"
    },
    {
     "expr": "ip:in(${members:doublequote}) job:syslog app:pgbouncer | stats count() as count",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": "ip:in(${members:doublequote}) job:pgbackrest | stats count() as count",
     "legendFormat": "pgbackrest"
    },
    {
     "expr": "ip:in(${members:doublequote}) job:syslog app:in(\"pg_exporter\",\"pgbouncer_exporter\",\"pgbackrest_exporter\") | stats count() as count",
     "legendFormat": "pgexporter"
    },
    {
     "expr": "ip:in(${members:doublequote}) job:syslog app:vip-manager | stats count() as count",
     "legendFormat": "vip-manager"
    }
   ]
  },
  {
   "title": "PG Logs",
   "type": "timeseries",
   "description": "PGSQL Logs Event",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ip:in(${members:doublequote}) job:postgres | stats count() as count",
     "legendFormat": "postgres"
    },
    {
     "expr": "job:pgbackrest ip:in(${members:doublequote})\n| stats count() as count",
     "legendFormat": "pgbackrest"
    },
    {
     "expr": "ip:in(${members:doublequote}) job:patroni\n| stats count() as count",
     "legendFormat": "patroni"
    },
    {
     "expr": "job:syslog ip:in(${members:doublequote})\napp:in(\"postgres\", \"pgbouncer\", \"pg_exporter\", \"pgbouncer_exporter\", \"pgbackrest_exporter\", \"vip-manager\") \n| stats by (app) count() as count",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "job:postgres ip:in(${members:doublequote}) \n| fields level,ins,_msg",
     "legendFormat": "{{ src }}"
    }
   ]
  },
  {
   "title": "PGSQL service logs",
   "type": "logs",
   "description": "service logs from \"postgres\", \"pgbouncer\", \"pg_exporter\", \"pgbouncer_exporter\", \"pgbackrest_exporter\", \"vip-manager\"",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "job:syslog ip:in(${members:doublequote}) \napp:in(\"postgres\", \"pgbouncer\", \"pg_exporter\", \"pgbouncer_exporter\", \"pgbackrest_exporter\", \"vip-manager\") \n| fields level, unit, _msg",
     "legendFormat": "{{ src }}"
    }
   ]
  }
 ]
}