{
 "title": "PGSQL Databases",
 "description": "PostgreSQL Databases",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{cls=\"$cls\"}, datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Cluster" }
   ]
  },
  {
   "title": "Database",
   "type": "table",
   "description": "Database of this cluster ${cls}\n\nLoad: active_time / backends (PG14 only)\n\nQuery RT : max query rt of this database\n\nClient: Pgbouncer Active Clients\n\nServer: Pgbouncer Active Servers\n\nBackend: Postgres num backends\n\nT = is Template?\n\nD = Disabled in Pgbouncer ?\n\nP = Paused in Pgbouncer ?",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cls=\"$cls\", datname!~\"wal|log\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "max by (datname) (pg:db:age{cls=\"$cls\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:query_rt_1m{ins=\"$primary\"})",
     "legendFormat": "RT"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_disabled{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_paused{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cls=\"$cls\"}) / sum by (datname) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Load"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_clients{cls=\"$cls\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cls=\"$cls\"})",
     "legendFormat": "Server"
    },
    {
     "expr": "max by (datname,host) (pgbouncer_database_pool_size{cls=\"$cls\", datname!=\"pgbouncer\"} + pgbouncer_database_reserve_pool{cls=\"$cls\", datname!=\"pgbouncer\"})",
     "legendFormat": "PoolSize"
    },
    {
     "expr": "max by (datname) (pg_db_datid{cls=\"$cls\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "title": "Conn / PGSQL",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (ins,datname) (pg_db_numbackends{cls=\"$cls\", datname!~\"wal|log|template\\\\d\"})",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "TPS / PGCAT",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (ins,datname) (rate(pg_db_xact_commit{cls=\"$cls\", datname=\"$datname\"}[1m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:xact_rt_1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins,instance) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:xact_commit_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:xact_rollback_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:xact_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:query_rate1m{cls=\"$cls\",datname=\"$datname\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:query_time_rate1m{cls=\"$cls\",  datname=\"$datname\"}) / sum(pgbouncer:db:query_rate1m{cls=\"$cls\",  datname=\"$datname\"})",
     "legendFormat": "Query RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_clients{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Pool Client"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_servers{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Server"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_db_numbackends{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cls) (pgbouncer_pool_waiting_clients{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:ixact_backends{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "iXact"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_db_age{cls=\"$cls\", datname=\"$datname\"}) / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_size_bytes{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Size"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Row Fetched (rate5m)",
   "type": "timeseries",
   "description": "Tuples fetched from databases",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(pg_db_tup_fetched{cls=\"$cls\", ins=\"$primary\", datname=\"$datname\"}[5m])",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "rate(pg_db_tup_fetched{cls=\"$cls\", ins!=\"$primary\", datname=\"$datname\"}[5m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Row Modified (rate5m)",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_inserted{ins=\"$primary\"}[5m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{ins=\"$primary\"}[5m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{ins=\"$primary\"}[5m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "TPS (rate5m)",
   "type": "timeseries",
   "description": "`pg_stat_databases`:\n\n`xact_commit` + `xact_rollback` rate in last 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate5m{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate5m{cls=\"$cls\", ins!=\"$primary\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Long Lived Xact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (ins) (pg_activity_max_tx_duration{cls=\"$cls\", ins=\"$primary\", state=\"active\"})",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "max by (ins) (pg_activity_max_tx_duration{cls=\"$cls\", ins!=\"$primary\", state=\"active\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{cls=\"$cls\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Blocks Hit Ratio (1m)",
   "type": "timeseries",
   "description": "Database 4k blocks hit ratio in last 1 minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{cls=\"$cls\", ins=\"$primary\", datname=\"$datname\"}",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "pg:db:blks_hit_ratio1m{cls=\"$cls\", ins!=\"$primary\", datname=\"$datname\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Pgbouncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Active Clients (Pgbouncer)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (ins) (pgbouncer:db:active_clients{cls=\"$cls\", ins=\"primary\", datname=\"$datname\"})",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "sum by (ins) (pgbouncer:db:active_clients{cls=\"$cls\", ins!=\"primary\",  datname=\"$datname\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Query RT (Pgbouncer 1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:query_time_rate1m{cls=\"$cls\", datname=\"$datname\"}) / \nsum(pgbouncer:db:query_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:db:query_rt_1m{cls=\"$cls\", ins=\"$primary\", datname=\"$datname\"}",
     "legendFormat": "{{ ins }}⭐️"
    },
    {
     "expr": "pgbouncer:db:query_rt_1m{cls=\"$cls\", ins!=\"$primary\", datname=\"$datname\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Active Servers (Pgbouncer)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (ins) (pgbouncer:db:active_servers{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (pool_mode,user,datname) (pgbouncer_pool_active_clients{cls=\"$cls\"})",
     "legendFormat": "[{{ pool_mode }}]] {{ user }}@{{ datname }}"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Tables",
   "type": "table",
   "description": "`pg_class` and `pg_stat_user_tables` metrics",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "max by (relname, relid) (pg_table_relid{ins=\"$primary\"})",
     "legendFormat": "OID"
    },
    {
     "expr": "max by (relname) (pg_table_size_bytes{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Table Size"
    },
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Table Scan"
    },
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{ins=\"$primary\", datname=\"$datname\"})",
     "legendFormat": "Primary Scan"
    },
    {
     "expr": "sum by (relname) (pg_table_seq_scan{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "Seq Scan"
    },
    {
     "expr": "sum by (relname) (rate(pg_table_tup_read{cls=\"$cls\", datname=\"$datname\"}[1m]))",
     "legendFormat": "Tup Read"
    },
    {
     "expr": "sum by (relname) (rate(pg_table_n_tup_mod{cls=\"$cls\", datname=\"$datname\"}[1m]))",
     "legendFormat": "Tup Mod"
    },
    {
     "expr": "max by (relname) (pg_table_n_live_tup{ins=\"$primary\", datname=\"$datname\"})",
     "legendFormat": "Tup Live"
    },
    {
     "expr": "max by (relname) (pg_table_n_dead_tup{ins=\"$primary\", datname=\"$datname\"})",
     "legendFormat": "Tup Dead"
    },
    {
     "expr": "max by (relname) (pg_table_n_dead_tup{ins=\"$primary\", datname=\"$datname\"} / \n(pg_table_n_live_tup{ins=\"$primary\", datname=\"$datname\"} + pg_table_n_dead_tup{ins=\"$primary\", datname=\"$datname\"}))",
     "legendFormat": "Dead%"
    }
   ]
  },
  {
   "title": "Table Size & Access",
   "type": "marcusolsson-treemap-panel",
   "description": "Index Scan + Seq Scan on this table per second.\n\nSize by table size, Color by table scan rate.",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (relname) (pg_table_size_bytes{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ relname }}"
    },
    {
     "expr": "sum by (relname) (\n    pg:table:scan_rate1m{cls=\"$cls\", datname=\"$datname\"}\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Scan (scan/s)",
   "type": "timeseries",
   "description": "Index Scan + Seq Scan on this table per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (\n    pg:table:scan_rate1m{cls=\"$cls\", datname=\"$datname\"}\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple Read (rows/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (\n    rate(pg_table_tup_read{cls=\"$cls\", datname=\"$datname\"}[1m])\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Statements",
   "type": "table",
   "description": "`pg_stat_statements` metrics of database ${datname} in this cluster: ${cls}.\n\nClick the `Instance` Column will goes to PGSQL Database Dashboard.",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins, query) (pg_query_calls{cls=\"$cls\", datname=\"$datname\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "sum by (query) (pg_query_exec_time{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:call_rate1m{cls=\"$cls\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (rate(pg_query_rows{cls=\"$cls\", datname=\"$datname\"}[5m])\n/ rate(pg_query_calls{cls=\"$cls\", datname=\"$datname\"}[5m])\n)",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "sum by (query) (rate(pg_query_wal_bytes{cls=\"$cls\", datname=\"$datname\"}[5m]) / rate(pg_query_calls{cls=\"$cls\", datname=\"$datname\"}[5m])\n)",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query Time Spent & RT",
   "type": "marcusolsson-treemap-panel",
   "description": "Area represent time spent in last 1h\ncolor represent RT of this query",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{cls=\"$cls\", datname=\"$datname\"}[1h])",
     "select": [
      [
       { "params": [ "video_duration" ], "type": "column" }
      ]
     ],
     "table": "predefined_message_translations1",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{cls=\"$cls\", datname=\"$datname\"})",
     "select": [
      [
       { "params": [ "video_duration" ], "type": "column" }
      ]
     ],
     "table": "predefined_message_translations1",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Query QPS (1m)",
   "type": "timeseries",
   "description": "`dM/dt`, where `M` is `calls`, which is queries per second, in last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{cls=\"$cls\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query RT (1m)",
   "type": "timeseries",
   "description": "dM/dC, where M is total_exec_time and C is calls, which means query latency in last 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:query:rt_1m{cls=\"$cls\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}