{
 "title": "PGSQL Instance",
 "description": "PostgreSQL Instance Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , ip)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"},nodename)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\",datname!~'template0|template1'}, datname)"
    }
   },
   {
    "name": "node_ins",
    "label": "Node Instance",
    "query": {
     "query": "label_values(node_load1{ip=\"$ip\"},ins)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$ins" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Node IP",
        "type": "string",
        "values": [ "${ip}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Hostname",
        "type": "string",
        "values": [ "${node}" ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 14, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins,instance) (haproxy_backend_current_sessions{cls=\"$cls\", proxy!=\"stats\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "max by (datname) (pg_db_datid{ins=\"$ins\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ins=\"$ins\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_up{ins=\"$ins\"}",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": "patroni_up{ins=\"$ins\"}",
     "legendFormat": "patroni"
    },
    {
     "expr": " pg_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "pg_exporter"
    },
    {
     "expr": " pgbouncer_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "pgb_exporter"
    },
    {
     "expr": " pgbackrest_exporter_agent_up{ins=\"$ins\"}",
     "legendFormat": "pgbackrest"
    },
    {
     "expr": " node_up{ip=~\"$ip\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_uptime{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_version{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_conf_reload_time{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg:ins:timeline{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_is_wal_replay_paused{ins=\"$ins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_in_recovery{ins=\"$ins\"}",
     "legendFormat": "recovery"
    },
    {
     "expr": "(pg_recv_init_lsn{ins=\"$ins\"} > bool 0) or on() vector(0)",
     "legendFormat": "{{ sender_host }} "
    },
    {
     "expr": "count(pg_repl_lsn{ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "Downstream"
    },
    {
     "expr": "pg_sync_standby_enabled{ins=\"$ins\"}",
     "legendFormat": "Sync Commit"
    },
    {
     "expr": "count by (ins)(pg_pubrel_count{ins=\"$ins\"}) > bool 0 or on() vector(0)",
     "legendFormat": "Publication"
    },
    {
     "expr": "count by (ins)(pg_sub_id{ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "Subscription"
    }
   ]
  },
  {
   "title": "HA Status",
   "type": "stat",
   "description": "HA Agent - Patroni Metrics",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_primary{ins=\"$ins\"} + patroni_standby_leader{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "patroni_version{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "patroni_postgres_server_version{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "patroni_is_paused{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "patroni_pending_restart{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "patroni_failsafe_mode_is_active{ins=\"$ins\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - patroni_dcs_last_seen{ins=\"$ins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service",
   "type": "stat",
   "description": "The number of proxies that serve corresponding service and have route to this ${ins} server.\n\nClick goes to PGSQL Service Dashboard",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (proxy) (haproxy_server_status{proxy=~\"$cls.*\", server=\"$ins\", state=\"UP\"})",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "TPS (1m) of each database on this postgres server",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_xact_total{ins=\"$ins\", datname!~'template\\\\d'}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ins:pressure1{ins=\"$ins\"}",
     "legendFormat": "PG LOAD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ip=\"$ip\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:lsn_rate1m{ins=\"$ins\"}",
     "legendFormat": "LSN Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(datname) (pg_db_numbackends{ins=\"$ins\"}) / pg_setting_max_connections{ins=\"$ins\"}",
     "legendFormat": "Conn%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cls,ins)(pg_repl_replay_lag{ins=\"$ins\"} or pg:ins:lag_seconds{ins=\"$ins\"} or pg_lag{ins=\"$ins\"})",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:fs:space_usage{ip=\"$ip\"}",
     "legendFormat": "Space: {{ mountpoint }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cls:load1{cls=\"$cls\"}",
     "legendFormat": "Postgres"
    },
    {
     "expr": "pgbouncer:cls:load1{cls=\"$cls\"}",
     "legendFormat": "Pgbouncer"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{cls=\"$cls\"}[1m]))",
     "legendFormat": "Exporter"
    },
    {
     "expr": "avg by (cls) (haproxy:ins:usage{ip=~\"$ip\"})",
     "legendFormat": "Haproxy"
    },
    {
     "expr": "pg:cls:cpu_usage{cls=\"$cls\"}",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:ins:load1{ins=\"$ins\"}",
     "legendFormat": "p1"
    },
    {
     "expr": "pg:ins:load5{ins=\"$ins\"}",
     "legendFormat": "p5"
    },
    {
     "expr": "pg:ins:load15{ins=\"$ins\"}",
     "legendFormat": "p15"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}"
    },
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}"
    }
   ]
  },
  { "title": "Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "table",
   "description": "Database of this cluster ${cls}\n\nLoad: active_time / backends (PG14 only)\n\nQuery RT : max query rt of this database\n\nClient: Pgbouncer Active Clients\n\nServer: Pgbouncer Active Servers\n\nBackend: Postgres num backends\n\nT = is Template?\n\nD = Disabled in Pgbouncer ?\n\nP = Paused in Pgbouncer ?",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cls=\"$cls\", datname!~\"wal|log\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "max by (datname) (pg:db:age{cls=\"$cls\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:query_rt_1m{ins=\"$primary\"})",
     "legendFormat": "RT"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cls=\"$cls\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_disabled{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_paused{ins=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cls=\"$cls\"}) / sum by (datname) (pg_db_numbackends{cls=\"$cls\"})",
     "legendFormat": "Load"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_clients{cls=\"$cls\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cls=\"$cls\"})",
     "legendFormat": "Server"
    },
    {
     "expr": "max by (datname,host) (pgbouncer_database_pool_size{cls=\"$cls\", datname!=\"pgbouncer\"} + pgbouncer_database_reserve_pool{cls=\"$cls\", datname!=\"pgbouncer\"})",
     "legendFormat": "PoolSize"
    },
    {
     "expr": "max by (datname) (pg_db_datid{cls=\"$cls\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow = Agent (Patroni / PG Exporters)\n\nPink = MinIO",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ip=\"$ip\"}",
     "legendFormat": "postgres {{ ins }}"
    },
    {
     "expr": "pgbouncer_up{ip=\"$ip\"}",
     "legendFormat": "pgbouncer {{ ins }}"
    },
    {
     "expr": "patroni_up{ip=\"$ip\"}",
     "legendFormat": "patroni {{ ins }}"
    },
    {
     "expr": "pg_exporter_agent_up{ip=\"$ip\"}",
     "legendFormat": "pg_exporter {{ ins }}"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ip=\"$ip\"}",
     "legendFormat": "pgb_exporter {{ ins }}"
    },
    {
     "expr": "node_up{ip=\"$ip\"}",
     "legendFormat": "node {{ ins }}"
    },
    {
     "expr": "haproxy_up{ip=\"$ip\"}",
     "legendFormat": "haproxy {{ ins }}"
    },
    {
     "expr": "docker_up{ip=\"$ip\"}",
     "legendFormat": "docker {{ ins }}"
    },
    {
     "expr": "vector_up{ip=\"$ip\"}",
     "legendFormat": "vector {{ ins }}"
    },
    {
     "expr": "max by (ins) (up{job=\"juice\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"nginx\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"grafana\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmetrics\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vlogs\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vtraces\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmalert\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"alertmanager\", ip=\"$ip\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "etcd_up{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "redis_up{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "minio_up{ip=\"$ip\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mysql_up{ip=\"$ip\"}",
     "legendFormat": "mysql {{ ins }}"
    },
    {
     "expr": "mysql_exporter_up{ip=\"$ip\"}",
     "legendFormat": "mysql_exporter"
    }
   ]
  },
  {
   "title": "Patroni Members",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by (ins) (patroni_primary{cls=\"$cls\"}) + \nmax by (ins) (patroni_standby_leader{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cls,ins,scope) (patroni_version{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_server_version{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_is_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_cluster_unlocked{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_pending_restart{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_failsafe_mode_is_active{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_xlog_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_running{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_dcs_last_seen{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_postmaster_start_time{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_up{cls=\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$ins\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(node:cpu:usage{ip=\"$ip\"}[1m])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_repl_replay_lag{cls=\"$cls\", appname=\"$ins\"}",
     "legendFormat": "upstream's View"
    },
    {
     "expr": "pg_lag{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}'s View"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Average transaction response time from Pgbouncer.\nYou can use PostgreSQL metric after PG14",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "#pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}\npg:ins:active_time_rate1m{ins=\"$ins\"} / pg:ins:xact_total_rate1m{ins=\"$ins\"} # PG14",
     "legendFormat": "instance"
    },
    {
     "expr": "# pgbouncer:db:xact_rt_1m{ins=\"$ins\"}\npg:db:active_time_rate1m{ins=\"$ins\", datname!~'template\\\\d'} / pg:db:xact_total_rate1m{ins=\"$ins\", datname!~'template\\\\d'} # PG14",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "pg_db_numbackends{ins=\"$ins\", datname!~'template\\\\d'}",
     "legendFormat": "client backend @ {{ datname }}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Transactions per seconds for each database in Last 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_db_xact_total{ins=\"$ins\",datname!~\"template[0-9]\"}[5m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "CRUD",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_fetched{ins=\"$ins\"}[1m]))",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum(rate(pg_db_tup_inserted{ins=\"$ins\"}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{ins=\"$ins\"}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{ins=\"$ins\"}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "Statements RT",
   "type": "timeseries",
   "description": "Time spent per second for each query of each instances.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ datname }}-{{ query }}"
    }
   ]
  },
  {
   "title": "Disk / Network",
   "type": "timeseries",
   "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:dev:disk_read_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "{{ device }}-R▲"
    },
    {
     "expr": "node:dev:network_tx_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "{{ device }}-TX▲"
    },
    {
     "expr": "- node:dev:network_rx_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "{{ device }}-RX▼"
    },
    {
     "expr": "- node:dev:disk_write_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "{{ device }}-W▼"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "PG Logs",
   "type": "timeseries",
   "description": "PGSQL Logs Event",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ins:$ins job:postgres | stats count() as count",
     "legendFormat": "postgres"
    },
    {
     "expr": "job:pgbackrest ins:$ins\n| stats count() as count",
     "legendFormat": "pgbackrest"
    },
    {
     "expr": "ins:$ins job:patroni\n| stats count() as count",
     "legendFormat": "patroni"
    },
    {
     "expr": "job:syslog ip:$ip\napp:in(\"postgres\", \"pgbouncer\", \"pg_exporter\", \"pgbouncer_exporter\", \"pgbackrest_exporter\", \"vip-manager\") \n| stats by (app) count() as count",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "PostgreSQL Logs",
   "type": "logs",
   "description": "Recent logs for PGSQL components: postgres & patroni & pgbouncer & pgbackrest & exporters & vip-manager",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 78 },
   "targets": [
    { "expr": "ins:$ins job:postgres" }
   ]
  }
 ]
}