{
 "title": "PGSQL Patroni",
 "description": "PostgreSQL Cluster Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   },
   {
    "name": "node_cls",
    "label": "Node Cluster",
    "query": {
     "query": "label_values(node_load1{ip=~\"$members\"},cls)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Patroni Members",
   "type": "table",
   "description": "Patroni Member metrics of this cluster ${cls}",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "max by (ins) (patroni_primary{cls=\"$cls\"}) + \nmax by (ins) (patroni_standby_leader{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cls,ins,scope) (patroni_version{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_server_version{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_is_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_cluster_unlocked{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_pending_restart{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_failsafe_mode_is_active{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_xlog_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_running{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_dcs_last_seen{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_postmaster_start_time{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins,ip) (patroni_up{cls=\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"etcd\", cls=\"etcd\"}) by (cls) /\n count(up{job=\"etcd\", cls=\"etcd\"}) by (cls)\nor on() vector(0)",
     "legendFormat": "ETCD Status"
    },
    {
     "expr": "max(patroni_failsafe_mode_is_active{cls=\"$cls\"})",
     "legendFormat": "Failsafe Mode"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Failsafe Activated",
   "type": "timeseries",
   "description": "`patroni_up` of this cluster ${cls}. 1 means this patroni agent is alive, 0 means dead",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "patroni_up{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "`patroni_primary` of this cluster ${cls}. 1 means this member is leader of the cluster.\n\n2 `sleader` means this is a standby leader",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "patroni_primary{cls=\"$cls\"}\n+ patroni_standby_leader{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Cluster Locked",
   "type": "timeseries",
   "description": "`patroni_cluster_unlocked` of this cluster ${cls}. 1 means this cluster is locked from this member's perspective",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "patroni_cluster_unlocked{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Failsafe Activated",
   "type": "timeseries",
   "description": "`patroni_failsafe_mode_is_active` of this cluster ${cls}. 1 means this cluster's failsafe mode is activated",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "patroni_failsafe_mode_is_active{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Pending Restart",
   "type": "timeseries",
   "description": "`patroni_pending_restart` of this cluster ${cls}. 1 means this member needs to be restarted to make config change effect.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "patroni_pending_restart{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "WAL Paused",
   "type": "timeseries",
   "description": "`patroni_xlog_paused` of this cluster ${cls} members. 1 means PostgresQL WAL is paused.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "patroni_xlog_paused{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Patroni DCS Last Seen",
   "type": "timeseries",
   "description": "Time since patroni last successful connect to DCS:etcd service",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - patroni_dcs_last_seen{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Postmaster Uptime",
   "type": "timeseries",
   "description": "now - `patroni_postmaster_start_time`.\n\nIndicate postgres restart event",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - patroni_postmaster_start_time{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Health Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Service",
   "type": "table",
   "description": "Service map tells whether a server can be used as a specific service/role/svc.\ne.g Offline marks this server can be used as offline server",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "max by (proxy,server) (\n    haproxy_server_status{proxy=~\"$cls.*\", state=\"UP\"}\n)"
    }
   ]
  },
  {
   "title": "Active Session",
   "type": "timeseries",
   "description": "Session are created between proxies(haproxy) and servers(postgres).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (proxy,server) (\n    haproxy_server_status{proxy=~\"$cls.*\", state=\"UP\"}\n)",
     "legendFormat": "{{ proxy }} ➔ {{ server }}"
    }
   ]
  },
  { "title": "ETCD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"etcd\", cls=\"etcd\"}) by (cls) /\n count(up{job=\"etcd\", cls=\"etcd\"}) by (cls)\nor on() vector(0)",
     "legendFormat": "ETCD Health"
    }
   ]
  },
  {
   "title": "ETCD Aliveness",
   "type": "state-timeline",
   "description": "etcd is the DCS used by patroni",
   "gridPos": { "h": 7, "w": 13, "x": 4, "y": 51 },
   "targets": [
    {
     "expr": "min(etcd_server_has_leader{job=\"etcd\", cls=\"etcd\"}) or on() vector(0)",
     "legendFormat": "ETCD Cluster Healthy"
    },
    {
     "expr": "up{job=\"etcd\", cls=\"etcd\"}",
     "legendFormat": "{{ ins }} @ {{ ip }}"
    }
   ]
  },
  {
   "title": "DCS Last Seen",
   "type": "stat",
   "description": "How long since patroni the HA agent successfully connect to DCS:etcd.\n\nvalue larger than 20s needs extra attention",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - patroni_dcs_last_seen{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Patroni : ${cls}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Patroni Logs",
   "type": "timeseries",
   "description": "patroni logs rate of cluster ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "job:syslog ip:in(${members:doublequote}) app:patroni | stats by (ins) count() as count",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "job:syslog ip:in(${members:doublequote}) app:patroni | fields level, ins, ip, _msg"
    }
   ]
  }
 ]
}