{
 "title": "PGSQL Overview",
 "description": "PostgreSQL Monitoring HQ",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Environment", "query": "pgsql" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cls) (pg_up{job=\"$job\"}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "count(pg_up{job=\"$job\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(count by (proxy) (haproxy_server_status{job=\"$job\"}))",
     "legendFormat": "Service"
    },
    {
     "expr": "count(count(pg_up{job=\"$job\"}) by (ip))",
     "legendFormat": "Node"
    },
    {
     "expr": "count(max by (cls,datname) (pg_db_age{job=\"$job\", datname!~'template0|template1'}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(pg:cls:cpu_count{job=\"$job\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(pg:ins:mem_size{job=\"$job\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(max by (cls,datname)(pg_size_bytes{datname!~\"log|wal\", job=\"$job\"}))",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "type": "stat",
   "description": "ETCD Health server ratio, and number of Postgres cluster in Failsafe mode",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"etcd\", cls=\"etcd\"}) by (cls) /\n count(up{job=\"etcd\", cls=\"etcd\"}) by (cls)\nor on() vector(0)",
     "legendFormat": "ETCD Status"
    },
    {
     "expr": "sum(max by (cls) (patroni_failsafe_mode_is_active{}))",
     "legendFormat": "Failsafe Mode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:cpu_usage{job=\"$job\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cls:num_backends{job=\"$job\"})",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:xact_commit_rate1m{job=\"$job\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:xact_rollback_rate1m{job=\"$job\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:space_usage{job=\"$job\"})",
     "legendFormat": "Space Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:age{job=\"$job\"}",
     "legendFormat": "Age Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:lag_bytes{job=\"$job\"})",
     "legendFormat": "Lag Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cls:ixact_backends{job=\"$job\"})",
     "legendFormat": "iXact Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgbouncer:cls:waiting_clients{job=\"$job\"})",
     "legendFormat": "Queue Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:ins:conn_usage{job=\"$job\"})",
     "legendFormat": "Conn Max"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cls:pressure1{job=\"pgsql\"}",
     "legendFormat": "{{ cls }}"
    },
    {
     "expr": "pg:cls:xact_commit_rate1m{job=\"pgrds\"}",
     "legendFormat": "{{ cls }}"
    },
    {
     "expr": "sum(etcd_server_id{job=\"etcd\", cls=\"etcd\"}) by (cls) / count(etcd_server_id{job=\"etcd\", cls=\"etcd\"}) by (cls)\n",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nAzure = Patroni\n\nPurple = Postgres Exporter\n\nDeep Purple = Pgbouncer Exporter\n\nGray = Pgbackrest Exporter\n\nOrange = PG VIP",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " min by (ins) (pg_up{job=\"pgsql\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min by (ins) (pg_up{job=\"pgrds\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": " min by (ins) (pgbouncer_up{job=\"pgsql\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": " patroni_up{job=\"pgsql\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "pg_exporter_up{job=\"pgsql\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "pgbouncer_exporter_up{job=\"pgsql\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{job=\"pgsql\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min by (job,cls,vip) (probe_success{job=\"pgsql-vip\"})",
     "legendFormat": "{{ cls }} @ {{ vip }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=~\"pgsql|pgrds\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=~\"pgsql|pgrds\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\", job=~\"pgsql|pgrds\"})",
     "legendFormat": "[{{ severity }}] {{ alertname }} @ {{ cls }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  {
   "title": "Cluster Std Load5",
   "type": "timeseries",
   "description": "PostgreSQL Cluster Load 5\nLoad = active session time / total cpu time, among the cluster, average in last 5 minute",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cls:load5{job=\"$job\"} != -1",
     "legendFormat": "{{ cls }}"
    }
   ]
  },
  {
   "title": "Instance TPS",
   "type": "timeseries",
   "description": "Transactions committed + rollback per second in last 1 minute for all instances",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xact_total_rate5m{job=~\"pgrds\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "pg:ins:xact_total_rate5m{job=~\"pgsql\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "PGSQL Instances",
   "type": "table",
   "description": "All postgresql instances in this pigsty deployment",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "min by (cls,ins,ip) (up{job=\"$job\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:load1{job=\"$job\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:space_usage{job=\"$job\"})  / 1073741824"
    },
    {
     "expr": "max by (ins) (pg:ins:cpu_usage{job=\"$job\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:cpu_count{job=\"$job\"})"
    },
    {
     "expr": "min by (ins) (pg_in_recovery{job=\"$job\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{job=\"$job\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:active_clients{job=\"$job\", proxy!=\"stats\"})"
    },
    {
     "expr": "group by (ins,cluster_id,extensions,version,ver_str) (pg_meta_info{job=\"$job\", proxy!=\"stats\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:mem_size{job=\"$job\"}) / 1073741824"
    },
    {
     "expr": "max by (ins) (pg:ins:fs_size{job=\"$job\"}) / 1073741824"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 22, "w": 7, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ins:pressure1{job=\"$job\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "min by (ins) (up{job=\"$job\"}) == 0",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Patroni Members",
   "type": "table",
   "description": "Patroni responsible for Postgres HA\n\nDCS Seen: time since last seen etcd\n\nPaused: is in maintenance mode? (auto failover disabled)\n \nRestart: is there any pending config change that requires restart?\n\nFailsafe: in case of DCS failure, the failsafe mode is enabled to avoid split brain\n\nLock: if failsafe is active, the cluster is locked to prevent any failover\n\nPostgres: the status of it's managed Postgres instance",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "max by (ins,cls,ip) (patroni_up{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_primary{}) + \nmax by (ins) (patroni_standby_leader{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cls,ins,scope) (patroni_version{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_server_version{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_is_paused{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_cluster_unlocked{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_pending_restart{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_failsafe_mode_is_active{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_xlog_paused{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_running{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_dcs_last_seen{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_postmaster_start_time{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DCS: etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 14, "w": 4, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(etcd_server_id{job=\"etcd\", cls=\"etcd\"}) by (cls) /\n count(etcd_server_id{job=\"etcd\", cls=\"etcd\"}) by (cls)\nor on() vector(0)",
       "legendFormat": "ETCD Health"
      },
      {
       "expr": "sum(patroni_failsafe_mode_is_active{})",
       "legendFormat": "Failsafe Active"
      }
     ]
    },
    {
     "title": "ETCD Aliveness",
     "type": "state-timeline",
     "description": "etcd is the DCS used by patroni",
     "gridPos": { "h": 7, "w": 13, "x": 4, "y": 57 },
     "targets": [
      {
       "expr": "min(etcd_server_has_leader{job=\"etcd\", cls=\"etcd\"}) or on() vector(0)",
       "legendFormat": "ETCD Cluster Healthy"
      },
      {
       "expr": "up{job=\"etcd\", cls=\"etcd\"}",
       "legendFormat": "{{ ins }} @ {{ ip }}"
      }
     ]
    },
    {
     "title": "DCS Last Seen",
     "type": "stat",
     "description": "How long since patroni the HA agent successfully connect to DCS:etcd.\nMax amoung cluster\n\nvalue larger than 20s needs extra attention",
     "gridPos": { "h": 14, "w": 7, "x": 17, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (cls) (time() - patroni_dcs_last_seen{job=\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Patroni DCS Last Seen",
     "type": "timeseries",
     "description": "Time since patroni last successful connect to DCS:etcd service",
     "gridPos": { "h": 7, "w": 13, "x": 4, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (cls) (time() - patroni_dcs_last_seen{job=\"$job\"})",
       "legendFormat": "{{ cls }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Session",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum by (cls,proxy) (haproxy_backend_current_sessions{proxy!=\"stats\"})",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Service Health",
     "type": "state-timeline",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "sum by (cls,proxy) (haproxy_server_status{state=\"UP\"}) > bool 0",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "type": "stat",
     "description": "Services SLI is measured by Average Service UP time of last 1 day",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(haproxy:cls:service_up{}[1d])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Database of this cluster ${cls}",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "max by (cls,ins,datname) (pg_size_bytes{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "Age"
      },
      {
       "expr": "max by (ins,datname) (pg:db:age{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "Commit"
      },
      {
       "expr": "sum by (ins,datname) (pg:db:xact_commit_rate1m{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "TPS"
      },
      {
       "expr": "max by (ins,datname) (pg_db_conn_limit{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "Conn Limit"
      },
      {
       "expr": "sum by (ins,datname) (pg_db_numbackends{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "Conn Limit"
      }
     ]
    }
   ]
  }
 ]
}