{
 "title": "PGSQL PITR",
 "description": "PostgreSQL PITR Auxiliary Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "stanza",
    "label": "Stanza",
    "query": {
     "query": "label_values(pgbackrest_repo_status{cls=\"$cls\"},stanza)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   },
   {
    "name": "node_cls",
    "label": "Node Cluster",
    "query": {
     "query": "label_values(node_load1{ip=~\"$members\"},cls)"
    }
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  { "title": "Instance & Stanza", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance",
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nArchive: archive_mode of this instance\n\nClusterID: systemd id, may change if PITR from another cluster.",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{job=\"pgsql\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg_setting_archive_mode{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip) (pg_in_recovery{cls=\"$cls\"})"
    },
    {
     "expr": "min by (ins,ip, cluster_id) (pg_meta_info{cls=\"$cls\"})"
    }
   ]
  },
  {
   "title": "Stanza",
   "type": "table",
   "description": "Backup repository & stanza\n\nStanza: Cluster level backup repo, click will list available backups in this stanza\n\nStatus:\n\n0 - ok,\n1 - missing stanza path,\n2 - no valid backups,\n3 - missing stanza data,\n4 - different across repos,\n5 - database mismatch across repos,\n6 - requested backup not found,\n99 - other.\n\nLock:\n\n0 - no active operation with stanza,\n1 - one of the commands is running for stanza: backup, expire or stanza-*.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "pgbackrest_repo_status{ins=\"$primary\"}"
    },
    {
     "expr": "pgbackrest_stanza_lock_status{ins=\"$primary\"}"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Backup of Stanza ${stanza}",
   "type": "table",
   "description": "Backup detail info for selected stanzas, repos, backup types, block incremental statuses and backup names.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pgbackrest_backup_info{ins=\"$primary\",stanza=~\"$stanza\"}"
    },
    {
     "expr": "max by (backup_name,start_time,stop_time) (pgbackrest_backup_duration_seconds{ins=\"$primary\",stanza=~\"$stanza\"})"
    },
    {
     "expr": "max by (backup_name) (pgbackrest_backup_error_status{ins=\"$primary\",stanza=~\"$stanza\"})"
    },
    {
     "expr": "max by (backup_name) (pgbackrest_backup_size_bytes{ins=\"$primary\",stanza=~\"$stanza\"})"
    },
    {
     "expr": "max by (backup_name) (pgbackrest_backup_delta_bytes{ins=\"$primary\",stanza=~\"$stanza\"})"
    },
    {
     "expr": "max by (backup_name) (pgbackrest_backup_repo_delta_bytes{ins=\"$primary\",stanza=~\"$stanza\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_archive_mode{cls=\"$cls\"})",
     "legendFormat": "WAL Archive"
    }
   ]
  },
  {
   "title": "Postgres & Patroni PITR Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 14 },
   "targets": [
    {
     "expr": "max by (ins) (patroni_primary{cls=\"$cls\"}) + \nmax by (ins) (patroni_standby_leader{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_timeline_id{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_xact_xmax{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_is_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_lsn{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (ins) (pg_repl_lsn{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins,state) (pg_recv_flush_tli{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_xlog_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_running{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_timeline_id{cls=\"$cls\"} < bool on(cls) group_left() max by (cls)(pg_timeline_id{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_postmaster_start_time{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_up{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins,ip) (pg_up{cls=\"$cls\", job=\"pgsql\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins) (pg_in_recovery{cls=\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PITR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "XID Progress",
   "type": "timeseries",
   "description": "TransactionID xmax on each instance",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmax{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "LSN Progress",
   "type": "timeseries",
   "description": "Current WAL Sequence Number on each Instance",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "pg_lsn{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Base Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Basebackup Progress",
     "type": "timeseries",
     "description": "pg_basebackup progress (re-create replica)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_backup_sent_bytes{cls=\"$cls\"} / pg_backup_total_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    },
    {
     "title": "Basebackup Progress",
     "type": "table",
     "description": "pg_basebackup progress (re-create replica)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "pg_backup_sent_phase{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      },
      {
       "expr": "pg_backup_sent_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      },
      {
       "expr": "pg_backup_total_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      },
      {
       "expr": "pg_backup_sent_bytes{cls=\"$cls\"} / pg_backup_total_bytes{cls=\"$cls\"}",
       "legendFormat": "{{ ins }}"
      }
     ]
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Replication",
   "type": "table",
   "description": "Replication Status among cluster ${cls}",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "pg:cls:sender{cls=\"$cls\"}"
    },
    {
     "expr": "pg:cls:receiver{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Replication Lag in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{cls=\"$cls\"}",
     "legendFormat": "{{ ins }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:cls:leader{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cls}",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(pg_in_recovery{cls=\"$cls\"} == 0) * 0 + 1",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_timeline_id{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Logs",
   "type": "timeseries",
   "description": "PostgreSQL / PgBackrest Logs Event",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "job:in(\"postgres\", \"pgbackrest\") ip:in(${members:doublequote}) | stats by (ins,job) count() as count",
     "legendFormat": "{{ ins }}.{{ job }}"
    }
   ]
  },
  {
   "title": "Pgbackrest Logs",
   "type": "logs",
   "description": "Recent logs for pgbackrest",
   "gridPos": { "h": 17, "w": 16, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "job:pgbackrest ip:in(${members:doublequote}) $search | fields level, topic, ins, _msg"
    }
   ]
  },
  {
   "title": "PostgreSQL Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "direction": "desc",
     "expr": "job:postgres ip:in(${members:doublequote}) $search \n| fields level,ins,_msg"
    }
   ]
  },
  { "title": "Docs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "PITR Docs",
   "type": "text",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "[Pigsty Backup & Restore Docs](https://pigsty.io/docs/pgsql/backup)\n\n### By Time\n\nThe most frequently used target is the time point; you can specify the time point to restore to:\n\n```bash title=\"restore to a timepoint\"\n./pgsql-pitr.yml -l ${cls} -e '{\"pg_pitr\": { \"time\": \"2025-07-13 10:00:00+00\" }}'\n```\n\nTime should be a valid PostgreSQL [`TIMESTAMP`](https://www.postgresql.org/docs/17/datatype-datetime.html#DATATYPE-DATETIME-INPUT-TIME-STAMPS), `YYYY-MM-DD HH:MM:SS+TZ` is recommended.\n\n\n### By Name\n\nYou can create a named restore point with [`pg_create_restore_point`](https://www.postgresql.org/docs/current/functions-admin.html#id-1.5.8.34.5.5.2.2.1.1.1.1):\n\n```sql\nSELECT pg_create_restore_point('shit_incoming');\n```\n\nAnd use that named restore point in PITR:\n\n```bash\n./pgsql-pitr.yml -l ${cls} -e '{\"pg_pitr\": { \"name\": \"shit_incoming\" }}'\n```\n\n\n### By XID\n\nIf you have a transaction that accidentally deleted some data, the best way to recover is to restore the database to the state before that transaction.\n\n```bash title=\"restore right before a transaction\"\n./pgsql-pitr.yml -l ${cls} -e '{\"pg_pitr\": { \"xid\": \"250000\", exclusive: true }}'\n```\n\nYou can find the exact transaction id from monitoring dashboard, or find it from `TXID` from the CSVLOG.\n\n\n### By LSN\n\nPostgreSQL uses the [LSN](https://www.postgresql.org/docs/current/datatype-pg-lsn.html) (Log Sequence Number) to identify the position of a WAL record.\nYou can find it everywhere, like the PG LSN panel from Pigsty dashboards.\n\n```bash title=\"restore to a LSN\"\n./pgsql-pitr.yml -l ${cls} -e '{\"pg_pitr\": { \"lsn\": \"0/4001C80\", timeline: \"1\" }}'\n```\n\nTo restore to an exact point in the WAL stream, you may also specify the [`timeline`](https://www.postgresql.org/docs/current/runtime-config-wal.html#RECOVERY-TARGET-TIMELINE) parameter (default to `latest`)"
   }
  }
 ]
}