{
 "title": "PGSQL Query",
 "description": "PGSQL Query Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Database",
  "Query"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up{}, ins)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\"}, datname)"
    }
   },
   {
    "name": "query",
    "label": "Query",
    "query": {
     "query": "label_values(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}, query)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview : ${query}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Query",
        "type": "string",
        "values": [ "${query}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Database",
        "type": "string",
        "values": [ "${datname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$ins" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (datname, query) (pg_query_calls{ins=\"$ins\", datname=\"$datname\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "QPS (1m)",
   "type": "timeseries",
   "description": "Queries per second according to \n`pg_stat_statements`.`calls`\nin last minute",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "RT (1m)",
   "type": "timeseries",
   "description": "Average Query Latency according to `pg_stat_statements`: rate of `total_exec_time` / rate of `calls` in last minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) /\n rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "RT"
    }
   ]
  },
  { "title": "Query Metrics : QPS & RT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Query Calls (QPS 1m/5m/15m)",
   "type": "timeseries",
   "description": "Queries per second according to \n`pg_stat_statements`.`calls`\nin last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RT Variation σ/µ (5m)",
   "type": "timeseries",
   "description": "coefficient of variation, CV of Query Latency in last 5 minutes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) /\navg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "RT CV"
    }
   ]
  },
  {
   "title": "Query Latency (RT 1m/5m/15m)",
   "type": "timeseries",
   "description": "Average Query Latency according to `pg_stat_statements`: rate of `total_exec_time` / rate of `calls` in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) /\n increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) /\n increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) /\n increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "QPS Variation σ/µ (5m)",
   "type": "timeseries",
   "description": "coefficient of variation, CV of QPS in last 5 minutes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) /\navg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "QPS CV"
    }
   ]
  },
  {
   "title": "QPS Distribution (15m)",
   "type": "timeseries",
   "description": "QPS distribution in last 15 minute (offset 8min)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) + 3 * stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) - 3 * stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) + stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) - stddev_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}  OFFSET 450s",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "RT Distribution (15m)",
   "type": "timeseries",
   "description": "Average Response time distribution in last 15 minute (offset 8min)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) - 3 * stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) + 3 * stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) + stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) - stddev_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}  OFFSET 450s",
     "legendFormat": "RT"
    }
   ]
  },
  { "title": "Query Metrics / Call", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Rows Returned per Query (1m, 5m, 15m)",
   "type": "timeseries",
   "description": "Average number of rows returned by this query. Rate of `pg_stat_statements`: `rows` / `call` in last 1m, 5m, 15m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Execution Time per Query (1m, 5m, 15m)",
   "type": "timeseries",
   "description": "Average execution time of this query. Rate of `pg_stat_statements`: `total_exec_time`/`call` in last 1m, 5m, 15m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "WAL Bytes per Query (1m, 5m, 15m)",
   "type": "timeseries",
   "description": "Average number of WAL Bytes generated by this query. Rate of `pg_stat_statements`.`wal_bytes` in last 1m, 5m, 15m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) /\nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])/\nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])/\nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "I/O Time per Query (1m, 5m, 15m)",
   "type": "timeseries",
   "description": "Avery seconds of IO(blocks read+write) time spent by this query. Rate of `pg_stat_statements`: `blk_read_time` + `blk_write_time` in last 1m, 5m, 15m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m]) / \nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Shared Blocks Read/Write per Query (5m)",
   "type": "timeseries",
   "description": "Average number of bytes (blocks multiply default 8K page size) read/written from/to (disk/fs cache) by this query\n\n`pg_stat_statements`: `shared_blks_read` , `shared_blks_written` , write is plot with negative Y axis",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_query_sblk_read{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) * 8192\n/\nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "read"
    },
    {
     "expr": "- rate(pg_query_sblk_written{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) * 8192 /\nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Shared Blocks Hit/Dirtied per Query (5m)",
   "type": "timeseries",
   "description": "Average number of bytes (blocks multiply default 8K page size) hit/dirtied from/to (disk/fs cache) by this query\n\n`pg_stat_statements`: `shared_blks_hit` , `shared_blks_dirtied` , dirty is plot with negative Y axis",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_query_sblk_hit{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) * 8192\n/\nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "hit"
    },
    {
     "expr": "- rate(pg_query_sblk_dirtied{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) * 8192 /\nrate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "dirty"
    }
   ]
  },
  { "title": "Query Metrics / Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Rows Returned per Second (1m, 5m, 15m)",
   "type": "timeseries",
   "description": "Number of rows returned by this query per second. Rate of `pg_stat_statements`.`rows` in last 1m, 5m, 15m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Execution Time per Second (1m, 5m, 15m)",
   "type": "timeseries",
   "description": "Seconds of exec time spent by this query per second. Rate of `pg_stat_statements`.`total_exec_time` in last 1m, 5m, 15m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "WAL Bytes per Second (1m, 5m, 15m)",
   "type": "timeseries",
   "description": "Number of WAL Bytes generated by this query per second. Rate of `pg_stat_statements`.`wal_bytes` in last 1m, 5m, 15m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "I/O Time per Second (1m, 5m, 15m)",
   "type": "timeseries",
   "description": "Seconds of IO(blocks read+write) time spent by this query per second. Rate of `pg_stat_statements`: `blk_read_time` + `blk_write_time` in last 1m, 5m, 15m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_io_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Shared Blocks Dirtied/Write per Second (5m)",
   "type": "timeseries",
   "description": "Number of bytes (blocks multiply default 8K page size) dirtied / written by this query per second.\n\n`pg_stat_statements`: `shared_blks_dirtied` , `shared_blks_written` \n\nDirtied >= Write because a block may by updated multiple time before written to disk.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_query_sblk_dirtied{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) * 8192",
     "legendFormat": "dirty"
    },
    {
     "expr": "rate(pg_query_sblk_written{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) * 8192",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Shared Blocks Read per Second (5m) & Blocks Hit Ratio",
   "type": "timeseries",
   "description": "Number of bytes (blocks multiply default 8K page size) read / hit by this query per second.\n\n`pg_stat_statements`: `shared_blks_read`, `shared_blks_hit` and `hit` / `(read+hit)`\n\nUsually, Hit >> Read, which means hit ratio ~ 1.0",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_query_sblk_read{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) * 8192",
     "legendFormat": "read"
    },
    {
     "expr": "rate(pg_query_sblk_hit{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) / \n(rate(pg_query_sblk_hit{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) + rate(pg_query_sblk_read{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m]) * 8192)",
     "legendFormat": "hit ratio"
    }
   ]
  },
  { "title": "Query Metrics / Total %", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Query QPS (5m)",
   "type": "timeseries",
   "description": "Query QPS of this database ${datname} on ${ins} in last 5 minutes.\n\nrate 5m of `pg_stat_statements`.`calls`\nClick datapoint to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stat_total_query_count{ins=\"$ins\", datname=\"$datname\"}[5m])",
     "legendFormat": "Pgbouncer QPS"
    },
    {
     "expr": "rate(pg_db_xact_commit{ins=\"$ins\", datname=\"$datname\"}[5m])",
     "legendFormat": "Postgres TPS"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "This Query ⭐️"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query!=\"$query\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query RT (1m)",
   "type": "timeseries",
   "description": "Query RT of this database ${datname} on ${ins}.\n\nrate 1m of `total_exec_time` / `calls`\n\nClick datapoint to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stat_total_query_time{ins=\"$ins\", datname=\"$datname\"}[5m]) /\nrate(pgbouncer_stat_total_query_count{ins=\"$ins\", datname=\"$datname\"}[5m])",
     "legendFormat": "Pgbouncer RT"
    },
    {
     "expr": "rate(pg_db_active_time{ins=\"$ins\", datname=\"$datname\"}[5m]) /\nrate(pg_db_xact_commit{ins=\"$ins\", datname=\"$datname\"}[5m])",
     "legendFormat": "Postgres RT"
    },
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}",
     "legendFormat": "This Query ⭐️"
    },
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\",datname=\"$datname\", query!=\"$query\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Exec Time / RT Matrix (1h)",
   "type": "marcusolsson-treemap-panel",
   "description": "Size by exec time spent in last hour, Colored by RT in last hour",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (query) (increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"}[1h]))",
     "legendFormat": "__auto",
     "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.rows AS value, s.mean_exec_time AS rt\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND rows > 0\nORDER BY calls DESC\nLIMIT 100;"
    },
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\"}[1h]) / increase(pg_query_calls{ins=\"$ins\", datname=\"$datname\"}[1h])",
     "legendFormat": "__auto",
     "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.rows AS value, s.mean_exec_time AS rt\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND rows > 0\nORDER BY calls DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Rows Returned (5m)",
   "type": "timeseries",
   "description": "Numbers of rows returned of each query in this database ${datname} on ${ins} in last 5 minutes.\n\nrate 5m of `pg_stat_statements`.`calls`\nClick datapoint to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(pg_db_tup_returned{ins=\"$ins\", datname=\"$datname\"}[5m])",
     "legendFormat": "Postgres RPS"
    },
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "This Query ⭐️"
    },
    {
     "expr": "rate(pg_query_rows{ins=\"$ins\", datname=\"$datname\", query!=\"$query\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Exec Time Spent (1h)",
   "type": "piechart",
   "description": "Time spent on executing statements during last 1 hour.\n\nincrease1h of `pg_stat_statements`.`total_exec_time`",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1h])",
     "legendFormat": "⭐️{{ query }}"
    },
    {
     "expr": "increase(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query!=\"$query\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Exec Time Spent (5m)",
   "type": "timeseries",
   "description": "Exec Time Spent of this database ${datname} on ${ins}.\n\nrate 5m of `pg_stat_statements`.`calls`\nClick datapoint to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stat_total_query_time{ins=\"$ins\", datname=\"$datname\"}[5m])",
     "legendFormat": "Pgbouncer Time"
    },
    {
     "expr": "rate(pg_db_active_time{ins=\"$ins\", datname=\"$datname\"}[5m])",
     "legendFormat": "Postgres Time"
    },
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "This Query ⭐️"
    },
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query!=\"$query\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Blocks Access (1h)",
   "type": "piechart",
   "description": "Shared blocks access & read size in bytes, in last 1 hour of each query.\n\n`pg_stat_statements`: `share_blks_read` + `shared_blks_hit`",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(pg_query_sblk_read{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1h]) +\nincrease(pg_query_sblk_hit{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1h])) * 8192",
     "legendFormat": "⭐️{{ query }}"
    },
    {
     "expr": "(increase(pg_query_sblk_read{ins=\"$ins\", datname=\"$datname\", query!=\"$query\"}[1h]) +\nincrease(pg_query_sblk_hit{ins=\"$ins\", datname=\"$datname\", query!=\"$query\"}[1h])) * 8192",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "WAL Bytes (5m)",
   "type": "timeseries",
   "description": "Numbers of wal bytes generated of each query in this database ${datname} on ${ins} in last 5 minutes.\n\nrate 5m of `pg_stat_statements`.`wal_bytes`\n\nClick the data-point to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_lsn{ins=\"$ins\"}[5m])",
     "legendFormat": "Postgres LSN"
    },
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "This Query ⭐️"
    },
    {
     "expr": "rate(pg_query_wal_bytes{ins=\"$ins\", datname=\"$datname\", query!=\"$query\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  { "title": "Query Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "ip:$ip job:postgres query:\"${query}\""
    }
   ]
  }
 ]
}