{
 "title": "PGSQL Service",
 "description": "Postgres Cluster Service",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster",
  "Service"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "svc",
    "label": "Service",
    "query": {
     "query": "label_values(haproxy_server_status,proxy)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(haproxy_server_status{proxy='$svc'},cls)"
    }
   },
   {
    "name": "proxies",
    "label": "Proxies",
    "query": {
     "query": "label_values(haproxy_server_status{proxy='$svc'},ins)"
    }
   },
   {
    "name": "servers",
    "label": "Servers",
    "query": {
     "query": "label_values(haproxy_server_status{proxy='$svc'},server)"
    }
   },
   {
    "name": "pg_cls",
    "label": "PG Cluster",
    "query": {
     "query": "label_values(pg_up{ins=~'$servers'},cls)"
    }
   },
   {
    "name": "node_cls",
    "label": "Node Cluster",
    "query": {
     "query": "label_values(node_load1{ins=~'$servers'},cls)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Service",
        "type": "string",
        "values": [ "${svc}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "LB Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {}
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "PG Cluster",
        "type": "string",
        "values": [ "${pg_cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "Service among cluster. Number of routes from proxy to server",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (proxy) (haproxy_backend_current_sessions{proxy=~\"$pg_cls-.*\"})"
    },
    {
     "expr": "sum by (proxy) (haproxy_server_status{proxy=~\"$pg_cls-.*\"})"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by (cls,proxy) (haproxy_server_status{proxy=~\"$pg_cls-.*\", state=\"UP\"}) # > bool 0",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(haproxy_server_current_sessions{proxy=\"$svc\"})",
     "legendFormat": "Active Session"
    },
    {
     "expr": "count(sum by (server) (haproxy_server_current_sessions{proxy=\"$svc\"}))",
     "legendFormat": "Active Server"
    },
    {
     "expr": "count(sum by (ins)(haproxy_server_current_sessions{proxy=\"$svc\"}))",
     "legendFormat": "Active Proxy"
    }
   ]
  },
  {
   "title": "Active Session",
   "type": "timeseries",
   "description": "Session are created between proxies(haproxy) and servers(postgres).",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins,server) (haproxy_server_current_sessions{proxy=\"$svc\"})",
     "legendFormat": "[LB] {{ ins }} ➔ {{ server }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Services SLI is measured by Average Service UP time of last 1 day",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(haproxy:cls:service_up{cls=\"$cls\", proxy=\"$svc\"}[30d])",
     "legendFormat": "SLI (30d)"
    }
   ]
  },
  {
   "title": "${pg_cls} Session Matrix",
   "type": "table",
   "description": "Service map tells whether a server can be used as a specific service/role/svc.\ne.g Offline marks this server can be used as offline server",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (proxy,server) (\n    haproxy_server_current_sessions{proxy=~\"$pg_cls.*\", cls=~'$cls'}\n)"
    }
   ]
  },
  {
   "title": "${svc} Session Matrix",
   "type": "table",
   "description": "Columns are proxies, Rows are target servers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "max by (ins,server) (\n    haproxy_server_current_sessions{proxy=\"$svc\"}\n)"
    }
   ]
  },
  { "title": "HAProxy for ${svc}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "table",
   "description": "All haproxy instances in this cluster ${cls}",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "min by (ins) (haproxy_up{cls=\"$cls\"})"
    },
    {
     "expr": "sum without (proxy) (haproxy_backend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})"
    },
    {
     "expr": "sum by (ins,ip) (haproxy_server_status{cls=\"$cls\", proxy=\"$svc\"})"
    },
    {
     "expr": "max by (ins) ((100 - haproxy_process_idle_time_percent{cls=\"$cls\", proxy=\"$svc\"}))  / 100"
    }
   ]
  },
  {
   "title": "Active Session (by Proxy)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_frontend_current_sessions{cls=\"$cls\", proxy=\"$svc\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Proxy Saturation",
   "type": "timeseries",
   "description": "HAProxy CPU Usage (busy ratio)",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "haproxy:ins:usage{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Traffic (by Proxy)",
   "type": "timeseries",
   "description": "▲ for out traffic\n▼ for incoming traffic",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (ins) (rate(haproxy_frontend_bytes_out_total{cls=\"$cls\", proxy=\"$svc\"}[5m]))",
     "legendFormat": "{{ ins }}-TX▲"
    },
    {
     "expr": "- sum by (ins) (rate(haproxy_frontend_bytes_in_total{cls=\"$cls\", proxy=\"$svc\"}[5m]))",
     "legendFormat": "{{ ins }}-RX▼"
    }
   ]
  },
  { "title": "PG Server for ${svc}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "table",
   "description": "All postgres instance among this cluster",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (server)(haproxy_server_status{proxy=~\"$svc\"})",
     "legendFormat": "Route"
    },
    {
     "expr": "max by (server) (haproxy_server_weight{proxy=~\"$svc\"})"
    },
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{proxy=~\"$svc\"})"
    }
   ]
  },
  {
   "title": "Active Session (by Server)",
   "type": "timeseries",
   "description": "Session by postgres instance",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{cls=\"$cls\", proxy=\"$svc\"})",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "PG Server Saturation",
   "type": "timeseries",
   "description": "PostgreSQL Instance Saturation (busy ratio)",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ins:pressure1{cls=\"$pg_cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Traffic (by Server)",
   "type": "timeseries",
   "description": "▲ for out traffic\n▼ for incoming traffic",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(haproxy_server_bytes_out_total{cls=\"$cls\", proxy=\"$svc\"}[5m]))",
     "legendFormat": "{{ server }}-TX▲"
    },
    {
     "expr": "- sum by (server) (rate(haproxy_server_bytes_in_total{cls=\"$cls\", proxy=\"$svc\"}[5m]))",
     "legendFormat": "{{ server }}-RX▼"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "\n1 * min by(ins,server) (haproxy_server_status{proxy=\"$svc\", state=\"UP\"})\n+ 2 * min  by(ins,server)  (haproxy_server_status{proxy=\"$svc\", state=\"DRAIN\"})\n+ 4 * min  by(ins,server)  (haproxy_server_status{proxy=\"$svc\", state=\"MAINT\"})\n+ 8 * min  by(ins,server)  (haproxy_server_status{proxy=\"$svc\", state=\"NOLB\"})\n",
     "legendFormat": "{{ ins }} -> {{ server }}"
    }
   ]
  }
 ]
}