{
 "title": "Ferret Overview",
 "description": "MongoDB (FerretDB) Service Overview",
 "tags": [
  "Pigsty",
  "MONGO",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(ferretdb_up,cls)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ferretdb_up{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cls=\"$cls\", job=\"mongo\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cls=\"$cls\", job=\"mongo\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "QPS (5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (ins) (rate(ferretdb_client_requests_total{cls=\"$cls\", job=\"mongo\"}[5m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Client Accept",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(ferretdb_client_accepts_total{cls=\"$cls\", job=\"mongo\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "job:syslog app:ferretdb", "legendFormat": "{{ ins }}" }
   ]
  }
 ]
}