{
 "title": "Alert Manager",
 "description": "Dashboard showing Prometheus Alertmanager metrics for observing status of the cluster and possible debbuging.",
 "tags": [
  "Pigsty",
  "INFRA",
  "ALERT",
  "INSTANCE"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(alertmanager_build_info{cls=\"alertmanager\"},ins)"
    }
   },
   {
    "name": "ip",
    "query": {
     "query": "label_values(alertmanager_build_info{ins=\"$ins\"},ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alertmanager_build_info{ins=\"$ins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "All AlertManager instances",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{cls=\"alertmanager\"})"
    },
    {
     "expr": "sum by (ins) (alertmanager_alerts{cls=\"alertmanager\"})"
    },
    {
     "expr": "sum by (ins) (alertmanager_silences{cls=\"alertmanager\", state=\"active\"})"
    },
    {
     "expr": "sum by (ins) (rate(alertmanager_notifications_total{cls=\"alertmanager\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by (ins) (process_resident_memory_bytes{cls=\"alertmanager\"})"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{ins=~\"$ins\"})",
     "legendFormat": "Active Alerts"
    }
   ]
  },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "stat",
   "description": "How long the AlertManager instance has been running",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{ins=~\"$ins\"})",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total number of active alerts",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{ins=~\"$ins\"})",
     "legendFormat": "Active Alerts"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Number of active silences",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmanager_silences{ins=~\"$ins\", state=\"active\"})",
     "legendFormat": "Silences"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Rate of notifications sent",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(alertmanager_notifications_total{ins=~\"$ins\"}[$__rate_interval]))",
     "legendFormat": "Notifications"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Rate of failed notifications",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(alertmanager_notifications_failed_total{ins=~\"$ins\"}[$__rate_interval]))",
     "legendFormat": "Notif Failed"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Current resident memory usage of the process",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{ins=~\"$ins\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Number of AlertManager cluster members",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(alertmanager_cluster_members{ins=~\"$ins\"})",
     "legendFormat": "Cluster Size"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Rate of cluster gossip messages",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(alertmanager_cluster_messages_received_total{ins=~\"$ins\"}[$__rate_interval]))",
     "legendFormat": "Gossip Msgs"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "job:syslog ip:$ip app:alertmanager | stats count() as count",
     "legendFormat": "syslog"
    }
   ]
  },
  {
   "type": "logs",
   "description": "syslog of alertmanager in $ins @ $ip",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "job:syslog ip:$ip unit:alertmanager"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Notifications sent from $ins",
   "type": "timeseries",
   "description": "Number of sent notifications to distinct integrations such as PagerDuty, Slack and so on. On negative axis are displayed failed notifications.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{ins=~\"$ins\"}[$__interval])) by (integration)",
     "legendFormat": "{{ integration}}"
    },
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{ins=~\"$ins\"}[$__interval])) by (integration)",
     "legendFormat": "Failed {{ integration }}"
    }
   ]
  },
  {
   "title": "Notification durations per integration on $ins",
   "type": "timeseries",
   "description": "Duration of notification sends in 0.99 and 0.9 quantiles per integration.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.9,rate(alertmanager_notification_latency_seconds_bucket{ins=~\"$ins\"}[$__interval]))) by (integration)",
     "legendFormat": "0.9q {{ integration }}"
    },
    {
     "expr": "sum(histogram_quantile(0.99,rate(alertmanager_notification_latency_seconds_bucket{ins=~\"$ins\"}[$__interval]))) by (integration)",
     "legendFormat": "0.99q {{ integration }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active alerts in $ins",
     "type": "timeseries",
     "description": "Number of alerts by state such as `active`, `suppressed` etc.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(alertmanager_alerts{ins=~\"$ins\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Received alerts by status for $ins",
     "type": "timeseries",
     "description": "Number of received alerts from Prometheus by status `firing` on positive axis and `resolved` on negative axis.",
     "gridPos": { "h": 6, "w": 24, "x": 12, "y": 40 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(alertmanager_alerts_received_total{ins=~\"$ins\"}[$__interval])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster health score for $ins",
     "type": "timeseries",
     "description": "Shows cluster score representing cluster health. From Hashicorps official documentation: \n> This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\".\n\nFor more info see https://www.consul.io/docs/agent/telemetry.html#cluster-health",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_cluster_health_score{ins=~\"$ins\"}",
       "legendFormat": "Cluster health score"
      }
     ]
    },
    {
     "title": "Cluster members count on $ins",
     "type": "timeseries",
     "description": "Shows gossip cluster members count in time and failing peers in case of any in red color.",
     "gridPos": { "h": 6, "w": 24, "x": 12, "y": 41 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_cluster_members{ins=~\"$ins\"}",
       "legendFormat": "Number of cluster members"
      },
      {
       "expr": "alertmanager_cluster_failed_peers{ins=~\"$ins\"}",
       "legendFormat": "Number of failed peers"
      }
     ]
    },
    {
     "title": "Cluster peers left/joined on $ins",
     "type": "timeseries",
     "description": "On positive axis shows number of peers that joined the cluster and on negative axis number of peers that left the cluster.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_peers_left_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Cluster joined peers"
      },
      {
       "expr": "increase(alertmanager_cluster_peers_joined_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Cluster left peers"
      }
     ]
    },
    {
     "title": "Cluster reconnections on $ins",
     "type": "timeseries",
     "description": "On positive axis is number of attempts to reconnect the cluster. On negative axis if number of failed attempts.",
     "gridPos": { "h": 6, "w": 24, "x": 12, "y": 47 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "increase(alertmanager_cluster_reconnections_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Successful reconnections"
      },
      {
       "expr": "increase(alertmanager_cluster_reconnections_failed_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Failed reconnections"
      }
     ]
    },
    {
     "title": "Cluster messages count on $ins",
     "type": "timeseries",
     "description": "On positive axis is number of sent cluster messages by type `update` or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_total{ins=~\"$ins\"}[$__interval])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_total{ins=~\"$ins\"}[$__interval])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages size on $ins",
     "type": "timeseries",
     "description": "On positive axis is size of sent cluster messages by type `update` or `full_state` and on negative axis the same for received messages.",
     "gridPos": { "h": 6, "w": 24, "x": 12, "y": 53 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "sum(increase(alertmanager_cluster_messages_sent_size_total{ins=~\"$ins\"}[$__interval])) by (msg_type)",
       "legendFormat": "sent {{msg_type}}"
      },
      {
       "expr": "sum(increase(alertmanager_cluster_messages_received_size_total{ins=~\"$ins\"}[$__interval])) by (msg_type)",
       "legendFormat": "received {{msg_type}}"
      }
     ]
    },
    {
     "title": "Cluster messages queue on $ins",
     "type": "timeseries",
     "description": "On positive axis is number of queued cluster messages and on negative axis number of pruned messages.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 59 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_cluster_messages_pruned_total{ins=~\"$ins\"}",
       "legendFormat": "Pruned messages"
      },
      {
       "expr": "alertmanager_cluster_messages_queued{ins=~\"$ins\"}",
       "legendFormat": "Queued messages"
      }
     ]
    }
   ]
  },
  {
   "title": "Gossip messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of oversized gossip messages on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "increase(alertmanager_oversized_gossip_message_sent_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_dropped_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "dropped {{key}}"
      },
      {
       "expr": "increase(alertmanager_oversized_gossip_message_failure_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "failed {{key}}"
      }
     ]
    },
    {
     "title": "Duration of oversized gossip messages on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_oversize_gossip_message_duration_seconds_bucket{ins=~\"$ins\"}[$__interval]))",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Number of propagated gossip messages on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "increase(alertmanager_silences_gossip_messages_propagated_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "silences"
      },
      {
       "expr": "increase(alertmanager_nflog_gossip_messages_propagated_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "nf_log"
      }
     ]
    }
   ]
  },
  {
   "title": "Nflog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nflog queries count for $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "increase(alertmanager_nflog_queries_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Nflog query count"
      },
      {
       "expr": "increase(alertmanager_nflog_query_errors_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Nflog query errors"
      }
     ]
    },
    {
     "title": "Nflog query duration for $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_nflog_query_duration_seconds_bucket{ins=~\"$ins\"}[$__interval]))",
       "legendFormat": "Nflog query duration"
      }
     ]
    },
    {
     "title": "Nflog snapshot size for $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_nflog_snapshot_size_bytes{ins=~\"$ins\"}",
       "legendFormat": "Nflog snapshot size"
      }
     ]
    },
    {
     "title": "Nflog snapshot duration for $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "rate(alertmanager_nflog_snapshot_duration_seconds_sum{ins=~\"$ins\"}[$__interval]) / rate(alertmanager_nflog_snapshot_duration_seconds_count{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Nflog snapshot duration"
      }
     ]
    },
    {
     "title": "Nflog Go GC time for $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_nflog_gc_duration_seconds{ins=~\"$ins\"}",
       "legendFormat": "Nflog GC duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Silences",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Silences count by state on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_silences{ins=~\"$ins\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Silences query count on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "increase(alertmanager_silences_queries_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Silences query count"
      },
      {
       "expr": "increase(alertmanager_silences_query_errors_total{ins=~\"$ins\"}[$__interval])",
       "legendFormat": "Silences query fails"
      }
     ]
    },
    {
     "title": "Silences query duration on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "histogram_quantile(1,rate(alertmanager_silences_query_duration_seconds_bucket{ins=~\"$ins\"}[$__interval]))",
       "legendFormat": "Silences query duration"
      }
     ]
    },
    {
     "title": "Silences snapshot size on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_size_bytes{ins=~\"$ins\"}",
       "legendFormat": "Silences snapshot size"
      }
     ]
    },
    {
     "title": "Silences snapshot duration on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_silences_snapshot_duration_seconds{ins=~\"$ins\", quantile=\"0.99\"}",
       "legendFormat": "Silences snapshot duration"
      }
     ]
    },
    {
     "title": "Silences GC duration on $ins",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 74 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "alertmanager_silences_gc_duration_seconds{ins=~\"$ins\"}",
       "legendFormat": "Silences GC duration"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage/s for $ins",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{ins=~\"$ins\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max(kube_pod_container_resource_limits_cpu_cores{pod=~\"$ins\"}) by (pod)",
       "legendFormat": "Limit {{pod}}"
      }
     ]
    },
    {
     "title": "Memory usage for $ins",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "process_resident_memory_bytes{ins=~\"$ins\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{pod=~\"$ins\"}) by (pod)",
       "legendFormat": "Limit {{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}