{
 "title": "Grafana Overview",
 "description": "Pigsty Grafana Overview",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Grafana",
    "query": {
     "query": "label_values(grafana_build_info, ins)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(grafana_build_info{ins=\"$ins\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (grafana_build_info{ins=\"$ins\"})",
     "legendFormat": "Grafana"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ins=\"$ins\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ins=\"$ins\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{ins=\"$ins\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_folder{ins=\"$ins\"}",
     "legendFormat": "Folders"
    },
    {
     "expr": "grafana_stat_totals_dashboard{ins=\"$ins\"}",
     "legendFormat": "Dashboards"
    },
    {
     "expr": "grafana_stat_total_orgs{ins=\"$ins\"}",
     "legendFormat": "Organizations"
    },
    {
     "expr": "grafana_stat_total_users{ins=\"$ins\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "grafana_stat_active_users{ins=\"$ins\"}",
     "legendFormat": "Active User"
    }
   ]
  },
  { "title": "Grafana Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "job:syslog ip:$ip app:grafana| stats by (ins) count() as count",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Grafana Log",
   "type": "logs",
   "description": "syslog of grafana-server in $ins @ $ip",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "job:syslog ip:$ip app:grafana" }
   ]
  },
  { "title": "Grafana API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Grafana API QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (method, handler) (rate(grafana_http_request_duration_seconds_count{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  { "title": "Data Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Data Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_datasource{ins=\"$ins\"}",
     "legendFormat": "{{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Plugin QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 33 },
   "targets": [
    {
     "expr": "rate(grafana_plugin_request_total{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ plugin_id }}.{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Grafana Plugins",
   "type": "table",
   "gridPos": { "h": 20, "w": 10, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "grafana_plugin_build_info{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Plugin RT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(grafana_plugin_request_duration_milliseconds_sum{ins=\"$ins\"}[1m]) /\nincrease(grafana_plugin_request_duration_milliseconds_count{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ plugin_id }}.{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Data Source QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 43 },
   "targets": [
    {
     "expr": "rate(grafana_datasource_request_total{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ datasource }}:{{ method }}:{{ code }}"
    }
   ]
  },
  {
   "title": "Data Source RT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(grafana_datasource_request_duration_seconds_sum{ins=\"$ins\"}[1m]) / increase(grafana_datasource_request_duration_seconds_count{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ datasource }}{{ datasource }}:{{ method }}:{{ code }}"
    }
   ]
  },
  {
   "title": "Data Source Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(grafana_datasource_response_size_bytes_sum{ins=\"$ins\"}[1m]) / increase(grafana_datasource_response_size_bytes_count{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ datasource }}{{ datasource }}:{{ method }}:{{ code }}"
    }
   ]
  }
 ]
}