{
 "title": "Infra Overview",
 "description": "Pigsty Infrastructure Overview",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure",
   "type": "table",
   "description": "All infra components and links",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (ip,ins) (nginx_up{cls=\"nginx\"})"
    },
    {
     "expr": "max by (ip,ins) (grafana_build_info{cls=\"grafana\"})"
    },
    {
     "expr": "max by (ip,ins) (vm_app_version{cls=\"vmetrics\"})"
    },
    {
     "expr": "max by (ip,ins) (vm_app_version{cls=\"vlogs\"})"
    },
    {
     "expr": "max by (ip,ins) (vm_app_version{cls=\"vtraces\"})"
    },
    {
     "expr": "max by (ip,ins) (vm_app_version{cls=\"vmalert\"})"
    },
    {
     "expr": "max by (ip,ins) (alertmanager_build_info{cls=\"alertmanager\"})"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "pigsty" },
    { "expr": "1", "legendFormat": "cmdb" },
    { "expr": "1", "legendFormat": "nginx" },
    { "expr": "1", "legendFormat": "grafana" },
    { "expr": "1", "legendFormat": "vmetrics" },
    { "expr": "1", "legendFormat": "vlogs" },
    { "expr": "1", "legendFormat": "vtraces" },
    { "expr": "1", "legendFormat": "vmalert" },
    { "expr": "1", "legendFormat": "alertmanager" }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ins) (up{cls=\"nginx\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"grafana\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmetrics\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vlogs\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vtraces\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"vmalert\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (up{cls=\"alertmanager\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 7 } },
  {
   "title": "Infra Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "up{job=\"infra\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "ALERT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"}) or on() vector(0)",
       "legendFormat": "Firing Alert"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 3, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"}) by (alertname, severity)",
       "legendFormat": "{{ alertname }}"
      }
     ]
    },
    {
     "title": "Firing Alerts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"})",
       "legendFormat": "[{{ severity }}] {{alertname}} @ {{ cls }}"
      }
     ]
    },
    { "title": "Grafana Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 19, "y": 18 } },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ALERTS{job=~\"infra|etcd\"}"
      }
     ]
    }
   ]
  },
  { "title": "NGINX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{cls=\"nginx\"}",
     "legendFormat": "{{ ins }} @ {{ ip }}"
    }
   ]
  },
  {
   "title": "Nginx Conn Accept/Handle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{}[5m])",
     "legendFormat": "{{ ins }} Accept"
    },
    {
     "expr": "rate(nginx_connections_handled{}[5m])",
     "legendFormat": "{{ ins }} Handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (nginx_connections_active{})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"infra\"}) by (ip)",
     "legendFormat": "infra @ {{ ip }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "vCore" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"infra\"}[1m])) by (ip)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"infra\"}) by (ip)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{cls=\"vmetrics\"}) by (ip)\n+ sum(vl_data_size_bytes{cls=\"vlogs\"}) by (ip)\n+ sum(vt_data_size_bytes{cls=\"vtraces\"}) by (ip)",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_data_size_bytes{cls=\"vmetrics\"}[1m])) by (ip)\n+ sum(rate(vl_data_size_bytes{cls=\"vlogs\"}[1m])) by (ip)\n+ sum(rate(vt_data_size_bytes{cls=\"vtraces\"}[1m])) by (ip)",
     "legendFormat": "Data Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_threads{job=\"infra\"}) by (ip)",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=\"infra\"}) by (ip)",
     "legendFormat": "OpenFDs"
    }
   ]
  },
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "grafana_build_info{cls=\"grafana\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"grafana\"}",
     "legendFormat": "{{ ins }} uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{cls=\"grafana\"}[1m])) by (ins)",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grafana_http_request_duration_seconds_bucket[5m])) by (ins,le)\n)",
     "legendFormat": "RT P50"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "c" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafana_database_conn_open{cls=\"grafana\"}) by (ins)",
     "legendFormat": "DB Conn"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cls=\"grafana\"}) by (ins)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cls=\"grafana\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "Victoria Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{cls=\"vmetrics\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"vmetrics\"}",
     "legendFormat": "{{ ins }} uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{cls=\"vmetrics\",type=\"storage/hour_metric_ids\"}) by (ins)",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ins) (rate(vm_rows_inserted_total{cls=\"vmetrics\"}[1m]))",
     "legendFormat": "Sample / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_targets{cls=\"vmetrics\"}) by (ins)",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cls=\"vmetrics\"}) by (ins)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{cls=\"vmetrics\"}) by (ins)",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Victoria Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{cls=\"vlogs\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"vlogs\"}",
     "legendFormat": "{{ ins }} Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total lines of log stored",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vl_storage_rows{cls=\"vlogs\"}) by (ins)",
     "legendFormat": "Lines"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vl_rows_ingested_total{cls=\"vlogs\"}[1m])) by (ins)",
     "legendFormat": "Lines / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vl_rows_dropped_total{cls=\"vlogs\"}[5m])) by (ins)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cls=\"vlogs\"}) by (ins)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vl_data_size_bytes{cls=\"vlogs\"}) by (ins)",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Victoria Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{cls=\"vtraces\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"vtraces\"}",
     "legendFormat": "{{ ins }} uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vt_rows_dropped_total{cls=\"vtraces\"}[1m])) by (ins)",
     "legendFormat": "Dropped / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vt_storage_rows{cls=\"vtraces\"}) by (ins)",
     "legendFormat": "Rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "stream/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vt_streams_created_total{cls=\"vtraces\"}[5m])) by (ins)",
     "legendFormat": "Streams"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cls=\"vtraces\"}) by (ins)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vt_data_size_bytes{cls=\"vtraces\"}) by (ins)",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Victoria Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{cls=\"vmalert\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"vmalert\"}",
     "legendFormat": "{{ ins }} uptime"
    }
   ]
  },
  {
   "type": "stat",
   "description": "eval rules per second",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vmalert_iteration_total[1m])) by (ins)",
     "legendFormat": "Eval Rate"
    }
   ]
  },
  {
   "type": "stat",
   "description": "5m alert sending",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vmalert_alerts_sent_total{cls=\"vmalert\"}[5m])) by (ins)\n",
     "legendFormat": "Alert 5m"
    }
   ]
  },
  {
   "type": "stat",
   "description": "5m alert sending",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vmalert_iteration_missed_total{cls=\"vmalert\"}[5m])) by (ins)",
     "legendFormat": "Missed"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cls=\"vmalert\"}) by (ins)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(process_cpu_seconds_total{cls=\"vmalert\"}[1m])) by (ins)",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}