{
 "title": "Logs Instance",
 "description": "Logs for Single Node/Instance",
 "tags": [
  "Pigsty",
  "INFRA",
  "Instance",
  "NODE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "" } },
   { "name": "job", "label": "Job", "query": { "query": "" } },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ins:$ins job:$job | stats by (ins,job) count() as count",
     "legendFormat": "{{ ins }}.{{ job }}"
    }
   ]
  },
  {
   "title": "Searched Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ins:$ins job:$job $search | stats by (ins,job) count() as count",
     "legendFormat": "{{ ins }}.{{ job }}"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "ins:$ins job:$job $search " }
   ]
  }
 ]
}