{
 "title": "Nginx Instance",
 "description": "Nginx metrics, access log & error logs",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(nginx_http_requests_total, ins)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(nginx_http_requests_total{ins=\"$ins\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{ins=\"$ins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "All Nginx instances",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{cls=\"nginx\"})"
    },
    {
     "expr": "min by (ins) (nginx_up{cls=\"nginx\"})"
    },
    {
     "expr": "sum by (ins) (rate(nginx_http_requests_total{cls=\"nginx\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by (ins) (nginx_connections_active{cls=\"nginx\"})"
    },
    {
     "expr": "sum by (ins) (process_resident_memory_bytes{cls=\"nginx\"})"
    }
   ]
  },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{ins=~\"$ins\"}[$__rate_interval]))",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Legacy Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "stat",
   "description": "How long the Nginx instance has been running",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - nginx_start_time{ins=~\"$ins\"})",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Rate of HTTP requests processed",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{ins=~\"$ins\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Number of active client connections",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_active{ins=~\"$ins\"})",
     "legendFormat": "Active Conn"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Connections reading request header",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_reading{ins=~\"$ins\"})",
     "legendFormat": "Reading"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Connections writing response",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_writing{ins=~\"$ins\"})",
     "legendFormat": "Writing"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Keep-alive connections waiting for requests",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_waiting{ins=~\"$ins\"})",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Rate of accepted connections",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted{ins=~\"$ins\"}[$__rate_interval]))",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Rate of handled connections",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_handled{ins=~\"$ins\"}[$__rate_interval]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Nginx Aliveness",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{ins=\"$ins\"}",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Nginx Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ ip }} REQ/s"
    }
   ]
  },
  {
   "title": "Nginx Conn Accept/Handle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ ip }} Accept"
    },
    {
     "expr": "irate(nginx_connections_handled{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ ip }} Handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_active{ins=\"$ins\"}",
     "legendFormat": "{{ ip }} active"
    },
    {
     "expr": "nginx_connections_reading{ins=\"$ins\"}",
     "legendFormat": "{{ ip }} reading"
    },
    {
     "expr": "nginx_connections_waiting{ins=\"$ins\"}",
     "legendFormat": "{{ ip }} waiting"
    },
    {
     "expr": "nginx_connections_writing{ins=\"$ins\"}",
     "legendFormat": "{{ ip }} writing"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Line by Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ins:$ins cls:nginx status:!\"\" | stats by (status) count() as count",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Lines by Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "ins:$ins cls:nginx server:!\"\" | stats by (server) count() as count",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  { "title": "Nginx Access Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ins:$ins cls:nginx | stats by (server) count() as count",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Nginx Access Log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "targets": [
    { "expr": "ins:$ins cls:nginx " }
   ]
  },
  { "title": "Nginx Error Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ins:$ins cls:nginx-error | stats by (server) count() as count",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 62 },
   "targets": [
    { "expr": "ins:$ins cls:nginx-error" }
   ]
  }
 ]
}