{
 "title": "Victoria Alert",
 "description": "Overview for VictoriaMetrics vmalert v1.117.0 or higher",
 "tags": [
  "Pigsty",
  "INFRA",
  "VICTORIA",
  "VMALERT",
  "INSTANCE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "ins",
    "query": {
     "query": "label_values(vm_app_version{cls=\"vmalert\"},ins)"
    }
   },
   {
    "name": "ip",
    "query": {
     "query": "label_values(vm_app_version{ins=\"$ins\"},ip)"
    }
   },
   {
    "name": "file",
    "query": {
     "query": "label_values(vmalert_iteration_total{ins=~\"$ins\"},file)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(vmalert_iteration_total{ins=~\"$ins\"}, group)"
    }
   },
   { "name": "topk", "query": "5, 10, 20, 30, 40, 50" },
   { "name": "filter" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_app_version{ins=\"$ins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "All VMAlert instances",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "min by (ins,ip) (up{cls=\"vmalert\"})"
    },
    {
     "expr": "min by (ins) (vm_app_uptime_seconds{cls=\"vmalert\"})"
    },
    {
     "expr": "sum by (ins) (vmalert_alerting_rules_last_evaluation_samples{cls=\"vmalert\"})"
    },
    {
     "expr": "sum by (ins) (vmalert_alerts_firing{cls=\"vmalert\"})"
    },
    {
     "expr": "sum by (ins) (vmalert_alerts_pending{cls=\"vmalert\"})"
    },
    {
     "expr": "sum by (ins) (process_resident_memory_bytes{cls=\"vmalert\"})"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vmalert_alerts_firing{ins=~\"$ins\"})",
     "legendFormat": "Firing Alerts"
    }
   ]
  },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "stat",
   "description": "How long the VMAlert instance has been running",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(vm_app_uptime_seconds{ins=~\"$ins\"})",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total number of loaded alerting rules across selected instances and groups",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmalert_alerting_rules_last_evaluation_samples{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"})",
     "legendFormat": "Alert Rules"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Number of alerts currently in firing state",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmalert_alerts_firing{ins=~\"$ins\"})",
     "legendFormat": "Firing"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Number of alerts currently in pending state",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmalert_alerts_pending{ins=~\"$ins\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total number of loaded recording rules across selected instances and groups",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmalert_recording_rules_last_evaluation_samples{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"})",
     "legendFormat": "Record Rules"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total errors from alerting and recording rules",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vmalert_alerting_rules_errors_total{ins=~\"$ins\"}[$__rate_interval])) + sum(increase(vmalert_recording_rules_errors_total{ins=~\"$ins\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Recording rules that produce no data (may be misconfigured)",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmalert_recording_rules_last_evaluation_samples{ins=~\"$ins\"} < 1)",
     "legendFormat": "No Data"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Current resident memory usage of the process",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{ins=~\"$ins\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Alerts fired total ($ins)",
   "type": "timeseries",
   "description": "Shows the number of fired alerts by job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vmalert_alerts_fired_total{ins=~\"$ins\"}[$__rate_interval])) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Top $topk groups avg evaluation duration ($group)",
   "type": "timeseries",
   "description": "Top $topk groups by evaluation duration. Shows groups that take the most of time during the evaluation across all instances.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($topk, max(sum(\n    rate(vmalert_iteration_duration_seconds_sum{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])\n/\n    rate(vmalert_iteration_duration_seconds_count{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])\n) by(job, instance, group, file)) \nby(job, group, file))",
     "legendFormat": "({{job}}) {{group}}({{file}})"
    }
   ]
  },
  {
   "title": "Rules execution rate ($ins)",
   "type": "timeseries",
   "description": "Shows how many requests (executions) per second vmalert sends to the configured datasource.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vmalert_execution_total{ins=~\"$ins\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rules execution errors ($ins)",
   "type": "timeseries",
   "description": "Shows the error rate while executing configured rules. Non-zero value means there are some issues with existing rules. Check the logs to get more details.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vmalert_execution_errors_total{ins=~\"$ins\"}[$__rate_interval])) by(job) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "job:syslog ip:$ip unit:vmalert | stats count() as count",
     "legendFormat": "syslog"
    }
   ]
  },
  {
   "type": "logs",
   "description": "syslog of vmalert in $ins @ $ip",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "job:syslog ip:$ip unit:vmalert "
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage % ($ins)",
     "type": "timeseries",
     "description": "How much resident memory (RAM) the process is actually using, compared to its allowed container or system limit.\n\n- Good: Below 70% most of the time, maybe spiking a bit under load.\n- Bad: Above 90% for more than 5 minutes = risk of out-of-memory (OOM) kill.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_bytes{ins=~\"$ins\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{ins=~\"$ins\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage % ($ins)",
     "type": "timeseries",
     "description": "Shows the CPU usage percentage per vmalert instance. \nIf you think that usage is abnormal or unexpected please file an issue and attach CPU profile if possible.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n  rate(process_cpu_seconds_total{ins=~\"$ins\"}[$__rate_interval]) \n  / \n  process_cpu_cores_available{ins=~\"$ins\"}\n) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RSS anonymous memory % usage",
     "type": "timeseries",
     "description": "Share for memory allocated by the process itself. When memory usage reaches 100% it will be likely OOM-killed.\nSafe memory usage % considered to be below 80%",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_anon_bytes{ins=~\"$ins\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{ins=~\"$ins\"}\n) by(instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage ($ins)",
     "type": "timeseries",
     "description": "Shows the max number of CPU cores used by a `job` and the corresponding limit.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(rate(process_cpu_seconds_total{ins=~\"$ins\"}[$__rate_interval])) by(job)",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "min(process_cpu_cores_available{ins=~\"$ins\"}) by(job)",
       "legendFormat": "limit ({{job}})"
      }
     ]
    },
    {
     "title": "Memory usage ($ins)",
     "type": "timeseries",
     "description": "Amount of used RSS memory\n\nIf you think that usage is abnormal or unexpected, please file an issue and attach memory profile if possible.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_bytes{ins=~\"$ins\"}[$__rate_interval])\n) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CPU pressure",
     "type": "timeseries",
     "description": "CPU pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html). Helps troubleshoot high CPU usage or throttling.\nLower is better.\n\n- waiting: The percentage of time at least one task in the process was ready to run (runnable) but couldn't get scheduled on the CPU.\n- stalled: The percentage of time all tasks in the process (except idle ones) were unable to get CPU time — a full CPU stall.\n\nIf there's a CPU burst, it's normal to see waiting or stalled > 1%. It only becomes a concern if it consistently climbs above 5–10% and aligns with latency spikes or GC slowdowns.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_pressure_cpu_waiting_seconds_total{ins=~\"$ins\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{instance}} - waiting"
      },
      {
       "expr": "sum(rate(process_pressure_cpu_stalled_seconds_total{ins=~\"$ins\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{instance}} - stalled"
      }
     ]
    },
    {
     "title": "Memory pressure",
     "type": "timeseries",
     "description": "Shows memory pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html).\nLower is better.\n\n- waiting: Time fraction where at least one thread was blocked on memory.\n- stalled: Time fraction where every thread was blocked on memory (severe pressure).\n\nIf queries slow down and both series spike, the host is likely limited by RAM or I/O throughput.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_pressure_memory_waiting_seconds_total{ins=~\"$ins\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{instance}} - waiting"
      },
      {
       "expr": "sum(rate(process_pressure_memory_stalled_seconds_total{ins=~\"$ins\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{instance}} - stalled"
      }
     ]
    },
    {
     "title": "Goroutines ($ins)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(go_goroutines{ins=~\"$ins\"}) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Open FDs usage % ($ins)",
     "type": "timeseries",
     "description": "Panel shows the percentage of open file descriptors in the OS.\nReaching the limit of open files can cause various issues and must be prevented.\n\nSee how to change limits here https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_open_fds{ins=~\"$ins\"}[$__rate_interval])\n    /\n    process_max_fds{ins=~\"$ins\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go scheduling latency",
     "type": "timeseries",
     "description": "Shows the time goroutines have spent in runnable state before actually running. The lower is better.\n\nHigh values or values exceeding the threshold is usually a sign of insufficient CPU resources or CPU throttling. \n\nVerify that service has enough CPU resources. Otherwise, the service could work unreliably with delays in processing.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{}[$__rate_interval])) by (job, instance, le))) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU spent on GC ($ins)",
     "type": "timeseries",
     "description": "Shows the percent of CPU spent on garbage collection.\n\nIf % is high, then CPU usage can be decreased by changing GOGC to higher values. Increasing GOGC value will increase memory usage, and decrease CPU usage.\n\nTry searching for keyword `GOGC` at https://docs.victoriametrics.com/victoriametrics/troubleshooting/ ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n  rate(go_gc_cpu_seconds_total{ins=~\"$ins\"}[$__rate_interval]) \n / rate(process_cpu_seconds_total{ins=~\"$ins\"}[$__rate_interval])\n ) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory allocations rate",
     "type": "timeseries",
     "description": "Shows the rate of allocations in memory. Sudden increase in allocations would mean increased pressure on Go Garbage Collector and can saturate CPU resources of the application.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(go_memstats_alloc_bytes_total{ins=~\"$ins\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-default flags",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(flag{is_set=\"true\", ins=~\"$ins\"}) by(job, instance, name, value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Missed evaluations ($ins)",
     "type": "timeseries",
     "description": "Missed evaluation means that group evaluation time takes longer than the configured evaluation interval. \nThis may result in missed alerting notifications or recording rules samples. Try increasing evaluation interval or concurrency for such groups. See https://docs.victoriametrics.com/victoriametrics/vmalert/#groups\n\nIf rule expressions are taking longer than expected, please see https://docs.victoriametrics.com/victoriametrics/troubleshooting/#slow-queries.\"",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vmalert_iteration_missed_total{ins=~\"$ins\"}[$__rate_interval])) by(job, group, file) > 0",
       "legendFormat": "({{job}}) {{group}}({{file}})"
      }
     ]
    },
    {
     "title": "Restarts ($job)",
     "type": "timeseries",
     "description": "Shows the number of restarts per job. The chart can be useful to identify periodic process restarts and correlate them with potential issues or anomalies. Normally, processes shouldn't restart unless restart was initiated by user. The reason of restarts should be figured out by checking the logs of each specific service. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(changes(vm_app_start_timestamp{ins=~\"$ins\"}[$__rate_interval]) > 0) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerting rules ($ins)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topk active alerts ($group)",
     "type": "timeseries",
     "description": "Shows top $topk current active (firing) alerting rules.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, sum(vmalert_alerts_firing{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"}) by(job, group, file, alertname) > 0)",
       "legendFormat": "({{job}}) {{group}}.{{alertname}}({{file}})"
      }
     ]
    },
    {
     "title": "Errors ($group)",
     "type": "timeseries",
     "description": "Shows the events when rule execution resulted into an error. Check the logs for more details.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vmalert_alerting_rules_errors_total{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])) by(job, group, file, alertname) > 0",
       "legendFormat": "({{job}}) {{group}}.{{alertname}}({{file}})"
      }
     ]
    },
    {
     "title": "Pending ($group)",
     "type": "timeseries",
     "description": "Shows the current pending alerting rules per group.\nBy pending means the rule which remains active less than configured `for` parameter.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vmalert_alerts_pending{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"}) by(job, group, file, alertname) > 0",
       "legendFormat": "({{job}}) {{group}}.{{alertname}}({{file}})"
      }
     ]
    },
    {
     "title": "Errors rate to Alertmanager",
     "type": "timeseries",
     "description": "Shows the error rate for the attempts to send alerts to Alertmanager. If not zero it means there issues on attempt to send notification to Alertmanager and some alerts may be not delivered properly. Check the logs for more details.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vmalert_alerts_send_errors_total{ins=~\"$ins\"}[$__rate_interval])) by(instance, addr) > 0",
       "legendFormat": "{{instance}} => {{addr}}"
      }
     ]
    },
    {
     "title": "Requests rate to Alertmanager by job",
     "type": "timeseries",
     "description": "Shows how many alerts are sent to Alertmanager per second. Only active alerts are sent.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vmalert_alerts_sent_total{ins=~\"$ins\"}[$__rate_interval])) by(job, addr) > 0",
       "legendFormat": "{{job}} => {{addr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Recording rules ($ins)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topk rules by produced samples ($group)",
     "type": "timeseries",
     "description": "Shows the top $topk recording rules which generate the most of [samples](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#raw-samples). Each generated sample is basically a time series which then ingested into configured remote storage. Rules with high numbers may cause the most pressure on the remote database and become a source of too high cardinality.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, \n  max(\n    sum(vmalert_recording_rules_last_evaluation_samples{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"}) by(job, instance, group, file, recording) > 0\n  ) by(job, group, file, recording)\n)",
       "legendFormat": "({{job}}) {{group}}.{{recording}}({{file}})"
      }
     ]
    },
    {
     "title": "Rules with 0 produced samples ($group)",
     "type": "timeseries",
     "description": "Shows the rules which do not produce any [samples](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#raw-samples) during the evaluation. Usually it means that such rules are misconfigured, since they give no output during the evaluation.\nPlease check if rule's expression is correct and it is working as expected.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(vmalert_recording_rules_last_evaluation_samples{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"} < 1) by(job, group, file, recording)",
       "legendFormat": "({{job}}) {{group}}.{{recording}}({{file}})"
      }
     ]
    },
    {
     "title": "Errors ($group)",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vmalert_recording_rules_errors_total{ins=~\"$ins\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])) by(job, group, file, recording) > 0",
       "legendFormat": "({{job}}) {{group}}.{{recording}}({{file}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datapoints send rate ($ins)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(rate(vmalert_remotewrite_sent_rows_total{ins=~\"$ins\"}[$__rate_interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Datapoints drop rate ($ins)",
     "type": "timeseries",
     "description": "Shows the number of datapoints dropped by vmalert while sending to the configured remote write URL. vmalert performs up to 5 retries before dropping the data. Check vmalert's error logs for the specific error message.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "sum(rate(vmalert_remotewrite_dropped_rows_total{ins=~\"$ins\"}[$__rate_interval])) by(job) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connections ($ins)",
     "type": "timeseries",
     "description": "Shows current number of established connections to remote write endpoints.\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(vmalert_remotewrite_conns{ins=~\"$ins\"}[$__rate_interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes write rate ($ins)",
     "type": "timeseries",
     "description": "Shows the global rate for number of written bytes via remote write connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(vmalert_remotewrite_conn_bytes_written_total{ins=~\"$ins\"}[$__rate_interval])) by(job) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}